# Generated by Django 5.2.12 on 2026-03-20 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0002_alter_notificationqueue_notification_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationqueue',
            name='body',
            field=models.TextField(help_text='Corpo del messaggio della notifica.', verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='notificationqueue',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('push', 'Push notification'), ('in_app', 'In-app notification')], help_text='Canale di invio: email, push o in-app.', max_length=10, verbose_name='channel'),
        ),
        migrations.AlterField(
            model_name='notificationqueue',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Tipo di contenuto che ha generato la notifica.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='notificationqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e ora di creazione nella coda.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='notificationqueue',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Messaggio di errore in caso di invio fallito.', verbose_name='error message'),
        ),
        migrations.AlterField(
            model_name='notificationqueue',
            name='notification_type',
            field=models.CharField(choices=[('news_published', 'News published'), ('event_published', 'Event published'), ('event_reminder', 'Event reminder'), ('weekend_favorites', 'Weekend favorites'), ('registration_opens', 'Registration opens'), ('photo_approved', 'Photo approved'), ('membership_expiring', 'Membership expiring'), ('partner_news', 'Partner news'), ('partner_events', 'Partner events'), ('partner_event_interest', 'Partner event interest'), ('partner_event_comment', 'Partner event comment'), ('partner_event_cancelled', 'Partner event cancelled'), ('aid_request', 'Aid request'), ('mutual_aid_request', 'Mutual aid request'), ('mutual_aid_access_request', 'Mutual aid access request'), ('event_registered', 'Event registration confirmed'), ('payment_instructions', 'Payment instructions'), ('payment_confirmed', 'Payment confirmed'), ('payment_expired', 'Payment expired'), ('registration_cancelled', 'Registration cancelled'), ('waitlist_promoted', 'Promoted from waitlist')], db_index=True, help_text='Tipo di notifica da inviare.', max_length=50, verbose_name='notification type'),
        ),
        migrations.AlterField(
            model_name='notificationqueue',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text="ID dell'oggetto che ha generato la notifica.", null=True, verbose_name='object ID'),
        ),
        migrations.AlterField(
            model_name='notificationqueue',
            name='recipient',
            field=models.ForeignKey(help_text='Destinatario della notifica.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient'),
        ),
        migrations.AlterField(
            model_name='notificationqueue',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Data e ora di invio effettivo.', null=True, verbose_name='sent at'),
        ),
        migrations.AlterField(
            model_name='notificationqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', help_text='Stato di invio della notifica.', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='notificationqueue',
            name='title',
            field=models.CharField(help_text='Titolo della notifica.', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='notificationqueue',
            name='url',
            field=models.CharField(blank=True, default='', help_text='URL di destinazione quando si clicca la notifica.', max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data di registrazione della sottoscrizione.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='is_active',
            field=models.BooleanField(default=True, help_text='La sottoscrizione è attiva e valida.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='last_used',
            field=models.DateTimeField(blank=True, help_text='Ultima volta che la sottoscrizione è stata usata.', null=True, verbose_name='last used'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(help_text='Utente proprietario della sottoscrizione push.', on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='user_agent',
            field=models.TextField(blank=True, default='', help_text="Browser e dispositivo dell'utente.", verbose_name='user agent'),
        ),
        migrations.AlterField(
            model_name='unsubscribetoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data di generazione del token.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='unsubscribetoken',
            name='notification_type',
            field=models.CharField(choices=[('news_published', 'News published'), ('event_published', 'Event published'), ('event_reminder', 'Event reminder'), ('weekend_favorites', 'Weekend favorites'), ('registration_opens', 'Registration opens'), ('photo_approved', 'Photo approved'), ('membership_expiring', 'Membership expiring'), ('partner_news', 'Partner news'), ('partner_events', 'Partner events'), ('partner_event_interest', 'Partner event interest'), ('partner_event_comment', 'Partner event comment'), ('partner_event_cancelled', 'Partner event cancelled'), ('aid_request', 'Aid request'), ('mutual_aid_request', 'Mutual aid request'), ('mutual_aid_access_request', 'Mutual aid access request'), ('event_registered', 'Event registration confirmed'), ('payment_instructions', 'Payment instructions'), ('payment_confirmed', 'Payment confirmed'), ('payment_expired', 'Payment expired'), ('registration_cancelled', 'Registration cancelled'), ('waitlist_promoted', 'Promoted from waitlist')], help_text='Tipo di notifica da cui disiscriversi.', max_length=50, verbose_name='notification type'),
        ),
        migrations.AlterField(
            model_name='unsubscribetoken',
            name='token',
            field=models.CharField(help_text='Token univoco HMAC per la disiscrizione.', max_length=64, unique=True, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='unsubscribetoken',
            name='user',
            field=models.ForeignKey(help_text='Utente che può disiscriversi con questo token.', on_delete=django.db.models.deletion.CASCADE, related_name='unsubscribe_tokens', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
