# Generated by Django 5.2.12 on 2026-03-15 14:09

import django.db.models.deletion
import uuid
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0003_add_club_description'),
        ('mutual_aid', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidprivacysettings',
            name='show_bio_on_aid',
            field=models.BooleanField(default=False, help_text='Mostra la bio nella scheda aiuto.', verbose_name='Show bio'),
        ),
        migrations.AlterField(
            model_name='aidprivacysettings',
            name='show_email_on_aid',
            field=models.BooleanField(default=False, help_text="Mostra l'email nella scheda aiuto.", verbose_name='Show email address'),
        ),
        migrations.AlterField(
            model_name='aidprivacysettings',
            name='show_hours_on_aid',
            field=models.BooleanField(default=False, help_text='Mostra gli orari di disponibilità.', verbose_name='Show availability hours'),
        ),
        migrations.AlterField(
            model_name='aidprivacysettings',
            name='show_mobile_on_aid',
            field=models.BooleanField(default=False, help_text='Mostra il cellulare nella scheda aiuto.', verbose_name='Show mobile number'),
        ),
        migrations.AlterField(
            model_name='aidprivacysettings',
            name='show_phone_on_aid',
            field=models.BooleanField(default=False, help_text='Mostra il telefono fisso nella scheda aiuto.', verbose_name='Show phone number'),
        ),
        migrations.AlterField(
            model_name='aidprivacysettings',
            name='show_photo_on_aid',
            field=models.BooleanField(default=False, help_text='Mostra la foto profilo nella scheda aiuto.', verbose_name='Show profile photo'),
        ),
        migrations.AlterField(
            model_name='aidprivacysettings',
            name='show_whatsapp_on_aid',
            field=models.BooleanField(default=False, help_text='Mostra la disponibilità WhatsApp.', verbose_name='Show WhatsApp availability'),
        ),
        migrations.AlterField(
            model_name='aidprivacysettings',
            name='user',
            field=models.OneToOneField(help_text='Utente a cui si applicano le impostazioni privacy.', on_delete=django.db.models.deletion.CASCADE, related_name='aid_privacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e ora di invio della richiesta.'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='federation_access',
            field=models.ForeignKey(blank=True, help_text='Accesso federato che ha generato la richiesta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aid_requests', to='mutual_aid.federatedaidaccess', verbose_name='Federation access'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='helper',
            field=models.ForeignKey(help_text='Soccorritore a cui è indirizzata la richiesta.', on_delete=django.db.models.deletion.CASCADE, related_name='aid_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='Helper'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='is_from_federation',
            field=models.BooleanField(default=False, help_text='La richiesta proviene da un club federato.', verbose_name='From federation'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='issue_type',
            field=models.CharField(choices=[('breakdown', 'Breakdown'), ('flat_tire', 'Flat tire'), ('fuel', 'Out of fuel'), ('accident', 'Accident'), ('tow', 'Need towing'), ('tools', 'Need tools'), ('transport', 'Need transport'), ('accommodation', 'Need accommodation'), ('other', 'Other')], default='other', help_text='Tipo di problema riscontrato.', max_length=20, verbose_name='Issue type'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='requester_email',
            field=models.EmailField(blank=True, help_text='Email di chi richiede aiuto.', max_length=254, verbose_name='Requester email'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='requester_name',
            field=models.CharField(help_text='Nome di chi richiede aiuto.', max_length=100, verbose_name='Requester name'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='requester_phone',
            field=models.CharField(blank=True, help_text='Telefono di chi richiede aiuto.', max_length=30, verbose_name='Requester phone'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='requester_user',
            field=models.ForeignKey(blank=True, help_text='Socio richiedente (se autenticato).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aid_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='Requester (if member)'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='open', help_text='Stato corrente della richiesta di aiuto.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text="Data e ora dell'ultimo aggiornamento."),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low - can wait'), ('medium', 'Medium - within a day'), ('high', 'High - urgent'), ('emergency', 'Emergency - immediate')], default='medium', help_text='Livello di urgenza della richiesta.', max_length=20, verbose_name='Urgency'),
        ),
        migrations.AlterField(
            model_name='contactunlock',
            name='federated_access',
            field=models.ForeignKey(help_text='Accesso federato che ha sbloccato il contatto.', on_delete=django.db.models.deletion.CASCADE, related_name='contact_unlocks', to='mutual_aid.federatedaidaccess', verbose_name='Federated access'),
        ),
        migrations.AlterField(
            model_name='contactunlock',
            name='helper',
            field=models.ForeignKey(help_text='Soccorritore il cui contatto è stato sbloccato.', on_delete=django.db.models.deletion.CASCADE, related_name='contact_unlocks_received', to=settings.AUTH_USER_MODEL, verbose_name='Helper'),
        ),
        migrations.AlterField(
            model_name='contactunlock',
            name='unlocked_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e ora dello sblocco.'),
        ),
        migrations.AlterField(
            model_name='federatedaidaccess',
            name='access_level',
            field=models.CharField(choices=[('view_list', 'View helpers list only'), ('contact', 'Can contact helpers')], default='view_list', help_text='Livello di accesso alla directory soccorritori.', max_length=20, verbose_name='Access level'),
        ),
        migrations.AlterField(
            model_name='federatedaidaccess',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text="Amministratore che ha approvato l'accesso.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AlterField(
            model_name='federatedaidaccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text="Data di concessione dell'accesso."),
        ),
        migrations.AlterField(
            model_name='federatedaidaccess',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text="Scadenza dell'accesso. Vuoto = nessuna scadenza.", null=True, verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='federatedaidaccess',
            name='external_display_name',
            field=models.CharField(help_text="Nome visualizzato dell'utente federato.", max_length=100, verbose_name='External display name'),
        ),
        migrations.AlterField(
            model_name='federatedaidaccess',
            name='external_user_id',
            field=models.CharField(help_text="ID dell'utente nel sistema del club partner.", max_length=100, verbose_name='External user ID'),
        ),
        migrations.AlterField(
            model_name='federatedaidaccess',
            name='is_active',
            field=models.BooleanField(default=True, help_text="L'accesso è attualmente attivo."),
        ),
        migrations.AlterField(
            model_name='federatedaidaccess',
            name='source_club',
            field=models.ForeignKey(help_text="Club federato che ha concesso l'accesso.", on_delete=django.db.models.deletion.CASCADE, related_name='aid_access_grants', to='federation.federatedclub', verbose_name='Source club'),
        ),
        migrations.AlterField(
            model_name='federatedaidaccessrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e ora di invio della richiesta.'),
        ),
        migrations.AlterField(
            model_name='federatedaidaccessrequest',
            name='federated_access',
            field=models.ForeignKey(help_text='Accesso federato di riferimento.', on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='mutual_aid.federatedaidaccess', verbose_name='Federated access'),
        ),
        migrations.AlterField(
            model_name='federatedaidaccessrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Data e ora della valutazione.', null=True, verbose_name='Reviewed at'),
        ),
        migrations.AlterField(
            model_name='federatedaidaccessrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Amministratore che ha valutato la richiesta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by'),
        ),
        migrations.AlterField(
            model_name='federatedaidaccessrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', help_text='Stato della richiesta di accesso.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='mutualaidpage',
            name='body',
            field=wagtail.fields.StreamField([('emergency_contact', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Name', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Role', 'max_length': 100}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Phone', 'max_length': 30}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 1), ('phone', 2)]], {})}, help_text="Contatti di emergenza configurabili dall'admin.", verbose_name='Emergency contacts'),
        ),
        migrations.CreateModel(
            name='FederatedHelper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(help_text='Helper ID on the partner system.', max_length=100, verbose_name='External ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display name')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('radius_km', models.PositiveIntegerField(default=25, verbose_name='Radius (km)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('photo_url', models.URLField(blank=True, verbose_name='Photo URL')),
                ('is_approved', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='federated_helpers', to='federation.federatedclub', verbose_name='Source club')),
            ],
            options={
                'verbose_name': 'Federated Helper',
                'verbose_name_plural': 'Federated Helpers',
                'ordering': ['city', 'display_name'],
                'unique_together': {('source_club', 'external_id')},
            },
        ),
    ]
