# Total keys: 1523
KEYS = [
    'Core',
    'Events',
    'Federation',
    'Members',
    'Mutual Aid',
    'Notifications',
    'Website',
    'Federated Club',
    'Federated Clubs',
    'External Event',
    'External Events',
    'External Event Interest',
    'External Event Interests',
    'External Event Comment',
    'External Event Comments',
    'Club User',
    'Club Users',
    'Event Registration',
    'Event Registrations',
    'Event Favorite',
    'Event Favorites',
    'Event page',
    'Confirmed',
    'Waitlist',
    'Pending',
    'Paid',
    'Refunded',
    'Stripe',
    'PayPal',
    'Bank Transfer',
    'User',
    'Status',
    'Number of guests',
    'Payment status',
    'Payment provider',
    'Payment ID',
    'External payment reference from the provider.',
    'Payment session ID',
    'Checkout Session ID (Stripe) or Order ID (PayPal).',
    'Payment amount',
    'Unique reference for bank transfers (e.g. EVT-00123-A7B3).',
    'Payment expires at',
    'Deadline for bank transfer payments.',
    'Guest',
    'Days before event',
    'Hours before event',
    'Minutes before event',
    'Discount percent',
    'Label',
    "Display label for this tier, e.g. 'Early Bird'.",
    'The time offset must be greater than zero.',
    'Added at',
    'Registered',
    'Registered at',
    'Cancelled',
    'Event',
    'Payment reference',
    'Is registration deadline',
    'Payment expired: {event}',
    'Your bank transfer for {event} was not received in time. Your registration has been cancelled.',
    'Spot available: {event}',
    'A spot has opened up! You have been promoted from the waitlist for {event}.',
    'Your membership does not include event registration. Please upgrade your membership.',
    'Please wait before toggling again.',
    'Payment instructions: {event}',
    'Please complete the bank transfer of €{amount} with reference {ref} by {expires}.',
    'Payment service temporarily unavailable. Please try again.',
    'Display name of the partner club',
    'URL-safe identifier',
    'Partner site base URL',
    'Optional logo URL',
    'Their public API key (given to us)',
    'Our key we gave them (auto-generated)',
    'Share our events with this partner',
    'Auto-approve imported events',
    'Sanitized HTML',
    'Select member',
    'Number of extra people coming with you (not counting yourself or your passenger). Example: 2',
    'List each guest on a separate line. Example:\\nMario Rossi\\nLucia Bianchi',
    'Allergies, dietary needs, special requests, or anything the organizers should know.',
    'Check this if someone will ride with you as a passenger on your motorcycle.',
    'If your passenger is already a club member, enable this to select them from the list.',
    'Example: Marco',
    'Example: Verdi',
    'Example: marco.verdi@email.com',
    'Italian tax identification code, 16 characters. Example: VRDMRC85M01H501Z',
    'Example: 1985-08-01',
    'Name and phone number to call in case of emergency. Example: Anna Verdi +39 340 7654321',
    'Your legal first name. Example: Maria',
    'Your family name. Example: Rossi',
    'Guest names',
    'Passenger first name',
    'Emergency contact',
    'Start typing a name to search registered members.',
    'Include country prefix. Example: +39 333 1234567',
    'We will send your registration confirmation here.',
    'Personal',
    'Identity',
    'Address',
    'Membership',
    'Privacy',
    'Username',
    'First name',
    'Last name',
    'Email',
    'Display name',
    'Phone',
    'Mobile',
    'Birth date',
    'Birth place',
    'Photo',
    'Bio',
    'Fiscal code',
    'Document type',
    'Document number',
    'Document expiry',
    'City',
    'Province',
    'Postal code',
    'Country',
    'Card number',
    'Membership date',
    'Membership expiry',
    'Is active',
    'Products',
    'Show in directory',
    'Public profile',
    'Show real name to members',
    'Newsletter',
    'Email notifications',
    'Push notifications',
    'News updates',
    'Event updates',
    'Event reminders',
    'Membership alerts',
    'Partner updates',
    'Aid requests',
    'Partner events',
    'Partner event comments',
    'Digest frequency',
    'Aid available',
    'Aid radius km',
    'Aid location city',
    'Aid coordinates',
    'Aid notes',
    'Spam detected. Access denied.',
    'This submission looks like spam.',
    'Too many requests. Please try again later.',
    'Are you human?',
    'Verify',
    'I am human',
    'Verification failed. Please try again.',
    'Remember me',
    'Home Page',
    'Content Page',
    'News Page',
    'News Index Page',
    'Gallery Page',
    'Gallery Index Page',
    'Events Index Page',
    'Contact Page',
    'Title',
    'Subtitle',
    'Body',
    'Image',
    'Caption',
    'Author',
    'Date',
    'Published',
    'Draft',
    'Summary',
    'Tags',
    'Category',
    'Categories',
    'Slug',
    'SEO Title',
    'Search Description',
    'Description',
    'Content',
    'Location',
    'Start date',
    'End date',
    'Start time',
    'End time',
    'All day',
    'Registration required',
    'Max participants',
    'Price',
    'Free',
    'Featured',
    'Promoted',
    'Featured image',
    'Heading',
    'Paragraph',
    'Quote',
    'Rich Text',
    'Rich text',
    'Link',
    'URL',
    'Button',
    'Button text',
    'Button link',
    'Call to Action',
    'Background color',
    'Background image',
    'Text color',
    'Alignment',
    'Left',
    'Center',
    'Right',
    'Full width',
    'Card',
    'Cards',
    'Column',
    'Columns',
    'Section',
    'Hero',
    'Hero section',
    'Embed',
    'Embed URL',
    'Video',
    'Document',
    'Documents',
    'File',
    'Download',
    'Gallery',
    'Slider',
    'Testimonial',
    'Testimonials',
    'Icon',
    'Feature',
    'Features',
    'Table',
    'Map',
    'Code',
    'Accordion',
    'Tab',
    'Tabs',
    'Spacer',
    'Divider',
    'HTML',
    'Raw HTML',
    'Site Settings',
    'Site settings',
    'Site Name',
    'Site name',
    'Tagline',
    'Logo',
    'Favicon',
    'Social Media',
    'Facebook',
    'Instagram',
    'Twitter',
    'YouTube',
    'LinkedIn',
    'Footer',
    'Footer text',
    'Copyright',
    'Analytics',
    'Google Analytics ID',
    'Theme',
    'Color scheme',
    'Primary color',
    'Secondary color',
    'Accent color',
    'Dark mode',
    'Light mode',
    'Auto',
    'Notification',
    'Notification Type',
    'Notification type',
    'Message',
    'Read',
    'Unread',
    'Sent',
    'Mark as read',
    'Mark all as read',
    'Delete',
    'No notifications',
    'Notification Settings',
    'Notification settings',
    'Enable email notifications',
    'Enable push notifications',
    'Notification Preference',
    'Notification Preferences',
    'Channel',
    'Channels',
    'Aid Request',
    'Aid Requests',
    'Aid Offer',
    'Aid Offers',
    'Aid Category',
    'Aid Categories',
    'Urgency',
    'Low',
    'Medium',
    'High',
    'Critical',
    'Open',
    'Closed',
    'In Progress',
    'Resolved',
    'Latitude',
    'Longitude',
    'Radius',
    'Available',
    'Unavailable',
    'Skills',
    'Equipment',
    'Notes',
    'Active',
    'Inactive',
    'Expires at',
    'Created at',
    'Updated at',
    'Created by',
    'Save',
    'Cancel',
    'Edit',
    'Add',
    'Remove',
    'Search',
    'Filter',
    'Sort',
    'View',
    'Details',
    'Back',
    'Next',
    'Previous',
    'Submit',
    'Confirm',
    'Close',
    'Update',
    'Yes',
    'No',
    'None',
    'All',
    'Name',
    'Type',
    'Actions',
    'Loading...',
    'Error',
    'Success',
    'Warning',
    'Info',
    'Snippet',
    'Snippets',
    'Menu item',
    'Menu items',
    'Navigation',
    'External link',
    'Internal link',
    'Page',
    'Pages',
    'Parent page',
    'Order',
    'Sort order',
    'Show in menu',
    'Upload',
    'Uploads',
    'Album',
    'Albums',
    'Upload date',
    'File size',
    'File type',
    'Width',
    'Height',
    'Alt text',
    'Thumbnail',
    'Partner',
    'Partners',
    'Partner Category',
    'Partner Categories',
    'Discount',
    'Benefit',
    'Benefits',
    'Valid from',
    'Valid until',
    'Terms and conditions',
    'Press Release',
    'Press Releases',
    'Registration',
    'Register',
    'Login',
    'Logout',
    'Sign up',
    'Sign in',
    'Password',
    'Confirm password',
    'Forgot password?',
    'Reset password',
    'Change password',
    'Account',
    'Profile',
    'Settings',
    'Preferences',
    'Upcoming events',
    'Past events',
    'No upcoming events',
    'Event details',
    'Register for event',
    'Cancel registration',
    'Registration closed',
    'Event full',
    'Spots available',
    'Organizer',
    'Route',
    'Route map',
    'Distance',
    'Difficulty',
    'Easy',
    'Moderate',
    'Hard',
    'Expert',
    'GPX file',
    'Route description',
    'Waypoints',
    'Departure',
    'Arrival',
    'Duration',
    'Verified',
    'Not verified',
    'Verification',
    'Verification code',
    'Verification token',
    'Approved',
    'Rejected',
    'Pending review',
    'Moderation',
    'Report',
    'Reported',
    'Ban',
    'Banned',
    'Interested',
    'Maybe',
    'Going',
    'Interest level',
    'Comment',
    'Comments',
    'Add comment',
    'Edit comment',
    'Delete comment',
    'Reply',
    'Last sync',
    'Last error',
    'Is approved',
    'Source club',
    'External ID',
    'Event name',
    'Location name',
    'Location address',
    'Event status',
    'Image URL',
    'Detail URL',
    'Is hidden',
    'Fetched at',
    'Short code',
    'Base URL',
    'Logo URL',
    'API key',
    'Scheduled',
    'Moved Online',
    'Postponed',
    'EventScheduled',
    'EventCancelled',
    'EventPostponed',
    'EventMovedOnline',
    'True',
    'False',
    'Enabled',
    'Disabled',
    'Structured data',
    'Schema type',
    'JSON-LD',
    'Open Graph',
    'Twitter Card',
    'Canonical URL',
    'Robots',
    'Sitemap',
    'sitemap.xml',
    'Dashboard',
    'Explorer',
    'Images',
    'Search terms',
    'Search promotions',
    'Redirects',
    'Users',
    'Groups',
    'Sites',
    'Collections',
    'Workflows',
    'Tasks',
    'Locked pages',
    'Aging pages',
    'Reports',
    'Language',
    'English',
    'Italian',
    'French',
    'German',
    'Spanish',
    'Select language',
    'This field is required.',
    'Enter a valid email address.',
    'Enter a valid URL.',
    'Enter a valid value.',
    'Ensure this value is greater than or equal to %(limit_value)s.',
    'Ensure this value is less than or equal to %(limit_value)s.',
    "I accept the <a href='/privacy/' target='_blank' rel='noopener'>terms and conditions</a>",
    'light',
    'dark',
    'auto',
    'Light',
    'Dark',
    'Install app',
    'Subscribe to notifications',
    'Unsubscribe from notifications',
    'Offline',
    'Online',
    'Update available',
    'Refresh',
    'Contribution',
    'Contributions',
    'Contributor',
    'Contributors',
    'Suggestion',
    'Suggestions',
    'Pending approval',
    'Today',
    'Tomorrow',
    'Yesterday',
    'This week',
    'Next week',
    'This month',
    'Next month',
    'Daily',
    'Weekly',
    'Monthly',
    'Never',
    'Product',
    'Product name',
    'Product type',
    'Includes event registration',
    'Annual',
    'Welcome',
    'Goodbye',
    'Thank you',
    'Confirmation',
    'Reminder',
    'Alert',
    'Important',
    'New',
    'address',
    'city',
    'province',
    'postal code',
    'country',
    'phone',
    'mobile',
    'email',
    'first name',
    'last name',
    'display name',
    'birth date',
    'birth place',
    'photo',
    'bio',
    'fiscal code',
    'document type',
    'document number',
    'document expiry',
    'card number',
    'membership date',
    'membership expiry',
    'is active',
    'show in directory',
    'public profile',
    'show real name to members',
    'newsletter',
    'email notifications',
    'push notifications',
    'news updates',
    'event updates',
    'event reminders',
    'membership alerts',
    'partner updates',
    'aid requests',
    'partner events',
    'partner event comments',
    'digest frequency',
    'aid available',
    'aid radius km',
    'aid location city',
    'aid coordinates',
    'aid notes',
    'products',
    'request',
    'offer',
    'Roadside assistance',
    'Mechanical help',
    'Transport',
    'Accommodation',
    'Medical',
    'Other',
    'other',
    'Description of the problem or assistance needed',
    'Title of the aid request',
    'Aid request',
    'Aid offer',
    'Responder',
    'Requester',
    'Response',
    'Responses',
    'Aid Response',
    'Aid Responses',
    'Response message',
    'Estimated arrival',
    'Can help',
    'On the way',
    'Arrived',
    'Completed',
    'Did not show',
    'event_registration',
    'event_reminder',
    'event_update',
    'membership_expiry',
    'aid_request',
    'aid_response',
    'partner_event',
    'system',
    'general',
    'email',
    'push',
    'in_app',
    'both',
    'Are you sure?',
    'This action cannot be undone.',
    'No results found.',
    'Showing %(start)s to %(end)s of %(total)s results',
    'Page %(current)s of %(total)s',
    'Items per page',
    'Apply',
    'Reset',
    'Clear',
    'Select all',
    'Deselect all',
    'Export',
    'Import',
    'CSV',
    'PDF',
    'Print',
    'Passenger',
    'Has passenger',
    'Passenger is member',
    'Passenger name',
    'Number of extra guests',
    'Special requests',
    'Total',
    'Subtotal',
    'Tax',
    'Registration date',
    'Registration status',
    'Confirm registration',
    'cancel',
    'Extra content',
    'Hero image',
    'Intro',
    'intro',
    'Related pages',
    'Related links',
    'Sidebar',
    'Header',
    'Main content',
    'Call to action',
    'call to action',
    'Banner',
    'Promo',
    'Highlight',
    'Text',
    'text',
    'Block type',
    'An error occurred.',
    'Permission denied.',
    'Not found.',
    'Page not found',
    'Server error',
    'Bad request',
    'Forbidden',
    'Unauthorized',
    'Service unavailable',
    'Early Bird',
    'Regular',
    'Late',
    'VIP',
    'Standard',
    'Premium',
    'Basic',
    'Published date',
    'Publish date',
    'Expire date',
    'Go live date',
    'First published at',
    'Last published at',
    'Latest revision created at',
    'Live',
    'Has unpublished changes',
    'Locked',
    'Locked by',
    'Locked at',
    'Menu label',
    'Admin display title',
    'Accept',
    'Reject',
    'Withdraw',
    'Confirm arrival',
    'Mark as resolved',
    'Request help',
    'Offer help',
    'Your location',
    'Distance from you',
    'km',
    'You have %(count)s new notifications',
    'No new notifications',
    'View all notifications',
    'Notification sent',
    'Notification deleted',
    'ID Card',
    'Passport',
    'Driving License',
    'Check-in',
    'Checked in',
    'Not checked in',
    'QR Code',
    'Scan QR code',
    'per year',
    'per month',
    'valid',
    'invalid',
    'required',
    'optional',
    'default',
    'custom',
    'public',
    'private',
    'visible',
    'hidden',
    'enabled',
    'disabled',
    'No membership card available.',
    'QR code generation not available.',
    'Barcode generation not available.',
    'Your name',
    'Phone number',
    'Email address',
    'Your current location',
    'Description must be 5000 characters or fewer.',
    'Why do you need access? (optional)',
    'Role',
    'Emergency Contact',
    'Introduction',
    'Emergency contacts',
    'Default map radius (km)',
    'Enable federation',
    'Mutual Aid Page',
    'Mutual Aid Pages',
    'Show phone number',
    'Show mobile number',
    'Show WhatsApp availability',
    'Show email address',
    'Show exact location',
    'If disabled, only the city name is shown.',
    'Show profile photo',
    'Show bio',
    'Show availability hours',
    'Aid Privacy Settings',
    'Low - can wait',
    'Medium - within a day',
    'High - urgent',
    'Emergency - immediate',
    'Accepted',
    'In progress',
    'Breakdown',
    'Flat tire',
    'Out of fuel',
    'Accident',
    'Need towing',
    'Need tools',
    'Need transport',
    'Need accommodation',
    'Helper',
    'Requester name',
    'Requester phone',
    'Requester email',
    'Requester (if member)',
    'Issue type',
    'Where are you? Address or coordinates.',
    'From federation',
    'Federation access',
    'Can contact helpers',
    'External user ID',
    'External display name',
    'Contacts unlocked',
    'Access level',
    'Approved by',
    'Federated Aid Access',
    'Federated Aid Access Grants',
    'Denied',
    'Federated access',
    'Why are you requesting access?',
    'Reviewed by',
    'Reviewed at',
    'Federated Aid Access Request',
    'Federated Aid Access Requests',
    'Contact Unlock',
    'Contact Unlocks',
    'Active membership required.',
    'News published',
    'Event published',
    'Event reminder',
    'Weekend favorites',
    'Registration opens',
    'Photo approved',
    'Membership expiring',
    'Partner news',
    'Partner event interest',
    'Partner event comment',
    'Partner event cancelled',
    'Mutual aid request',
    'Mutual aid access request',
    'Payment instructions',
    'Payment confirmed',
    'Payment expired',
    'Registration cancelled',
    'Promoted from waitlist',
    'Push notification',
    'In-app notification',
    'Failed',
    'Skipped',
    'notification type',
    'content type',
    'object ID',
    'recipient',
    'channel',
    'status',
    'title',
    'body',
    'scheduled for',
    'If set, notification will not be sent before this time.',
    'sent at',
    'created at',
    'error message',
    'notification',
    'notifications',
    'user',
    'endpoint',
    'Push service URL',
    'p256dh key',
    'Client public encryption key',
    'auth key',
    'Client auth secret',
    'active',
    'last used',
    'user agent',
    'push subscription',
    'push subscriptions',
    'token',
    'unsubscribe token',
    'unsubscribe tokens',
    'Invalid JSON body',
    'Endpoint is required',
    'Endpoint must use HTTPS',
    'Encryption keys are required',
    'Article gallery',
    'Event gallery',
    'Event location map',
    'Card thumbnail image.',
    'Optional badge text (e.g. date, category label).',
    'Card title.',
    'Short description text.',
    'Link to page',
    'External URL',
    'Used only if no internal page is selected.',
    'Button / link label.',
    'Optional section title above the grid.',
    '2 columns',
    '3 columns',
    '4 columns',
    'Number of columns on desktop.',
    'Default',
    'Outlined',
    'Elevated / shadow',
    'Minimal',
    'Visual style for the cards.',
    'Cards grid',
    'CTA headline.',
    'Supporting text.',
    'Button label.',
    'Button page link',
    'Button external URL',
    'Primary colour',
    'Gradient',
    'Image background',
    'Background style for this section.',
    "Background image (only used with 'Image background' style).",
    "The numeric value or short text (e.g. '1500+').",
    "Description of the stat (e.g. 'Members').",
    'Optional icon class name.',
    'Statistic',
    'Optional section title.',
    'Statistics',
    'The quote text.',
    'Name of the person quoted.',
    "Role or title of the author (e.g. 'President').",
    'Optional portrait of the author.',
    "Year or date label (e.g. '2015').",
    'Event or milestone title.',
    'Detailed description of this event.',
    'Timeline entry',
    'Timeline entries',
    'Timeline',
    'Position or title.',
    'Short biography.',
    'Team member',
    "Optional section title (e.g. 'Board of Directors').",
    'Team members',
    'Team grid',
    'Stay updated',
    'Form heading.',
    'Short text explaining what subscribers will receive.',
    'Subscribe',
    'Newsletter signup',
    'Alert message content.',
    'Danger',
    'Visual style and severity of the alert.',
    'Allow users to dismiss this alert.',
    'Slide background image.',
    'Slide headline.',
    'Optional subtitle text.',
    'CTA text',
    'CTA page link',
    'CTA external URL',
    'Slide',
    'Slides',
    'Automatically advance slides.',
    'Time between slides in milliseconds.',
    'Half screen',
    'Three-quarter screen',
    'Full screen',
    'Slider height.',
    'Show navigation arrows.',
    'Show dot indicators.',
    'Hero slider',
    'Hero background image.',
    "Small badge text above the title (e.g. 'Est. 2010').",
    'Main headline.',
    'Supporting text below the title.',
    'Secondary CTA text',
    'Optional secondary button label.',
    'Secondary CTA page link',
    'Secondary CTA external URL',
    'Light overlay',
    'Dark overlay',
    'Gradient overlay',
    'Overlay style over the background image.',
    'Bottom left',
    'Bottom right',
    'Position of the text overlay.',
    'Hero banner',
    'Select an event to count down to.',
    'Optional background image. Falls back to event cover image.',
    'Override the event title in the hero.',
    'Hero countdown',
    'URL to the video file (MP4 recommended).',
    'Displayed on mobile or when video cannot play.',
    'Mute the video (required for autoplay on most browsers).',
    'Loop the video.',
    'Hero video',
    'Accordion panel header.',
    'Panel content revealed when expanded.',
    'Accordion item',
    'Optional section title above the accordion.',
    'Panels',
    'Tab label.',
    'Tab panel content.',
    'Left column',
    'Right column',
    '50 / 50',
    '33 / 67',
    '67 / 33',
    '25 / 75',
    '75 / 25',
    'Column width ratio.',
    'Two columns',
    'Optional section heading.',
    'Section body content.',
    'Secondary colour',
    'Light grey',
    'Background style.',
    'Small',
    'Large',
    'Extra large',
    'Vertical padding.',
    'Horizontal line',
    'Dots',
    'Blank space',
    'Separator visual style.',
    'Small (1rem)',
    'Medium (2rem)',
    'Large (4rem)',
    'Extra large (6rem)',
    'Amount of vertical space.',
    'Optional caption displayed below the image.',
    'Gallery image',
    'Optional gallery title.',
    '6 columns',
    'Enable lightbox for full-size image viewing.',
    'Auto (original)',
    'Square (1:1)',
    'Landscape (4:3)',
    'Widescreen (16:9)',
    'Portrait (3:4)',
    'Thumbnail aspect ratio.',
    'Paste a video URL (YouTube, Vimeo, etc.).',
    'Optional caption displayed below the video.',
    'Autoplay the video (muted).',
    'Video embed',
    'Centred',
    'Float left',
    'Float right',
    'Image alignment within the content area.',
    'Optional description of the document.',
    'Section title for the document list.',
    'Document list',
    'Display address (shown in the info popup).',
    "Latitude,Longitude (e.g. '45.4642,9.1900').",
    'Map zoom level (1-20).',
    'Map height in pixels.',
    'Optional marker label.',
    "Waypoint name (e.g. 'Passo dello Stelvio').",
    'Optional address or location description.',
    "Latitude,Longitude (e.g. '46.5287,10.4531').",
    'Start',
    'Waypoint',
    'Fuel stop',
    'Food / restaurant',
    'Photo spot',
    'End',
    'Marker icon type on the map.',
    'Route name.',
    'Brief route description.',
    'At least two waypoints (start and end) are required.',
    'Scenic ride',
    'Touring',
    'Sport / twisties',
    'Off-road / adventure',
    'Commute / practical',
    'Type of route.',
    "Approximate distance (e.g. '320 km').",
    "Elevation gain (e.g. '2500 m').",
    "Estimated riding time (e.g. '5-6 hours').",
    'Challenging',
    'Route difficulty level.',
    'Enter member card number',
    'Verification type',
    'Select which piece of information to verify against.',
    'Verification value',
    'Enter the value to verify',
    'Photos',
    'Select up to 20 images (JPG, PNG, or WebP, max 10 MB each).',
    'Title prefix',
    'Optional prefix added to each photo title.',
    'e.g. Summer Rally 2025',
    'Optionally link photos to an event.',
    '-- No event --',
    'You can upload a maximum of %(max)d files at a time.',
    "File '%(name)s' exceeds the maximum size of 10 MB.",
    "File '%(name)s' is not an allowed format. Only JPG, PNG, and WebP are accepted.",
    'Hero title',
    'Main headline displayed in the hero section.',
    'Hero subtitle',
    'Hero background image',
    'Primary CTA text',
    'Primary CTA link',
    'Primary CTA external URL',
    'Secondary CTA link',
    'Featured event',
    'Select an EventDetailPage to highlight on the homepage.',
    'Call-to-action buttons',
    'Featured content',
    'Home page',
    'Home pages',
    'Displayed below the page title.',
    'Cover image',
    'About page',
    'About pages',
    'Use team-member blocks here.',
    'Board page',
    'Board pages',
    'Optional content displayed above the article listing.',
    'News index page',
    'News index pages',
    'Introduction / excerpt',
    'Short summary shown in listings.',
    'Display date',
    'Publication date shown to readers.',
    'Article metadata',
    'Categorisation',
    'News page',
    'News pages',
    'Optional content above the event listing.',
    'Events page',
    'Events pages',
    'Short description shown in listings.',
    'Start date & time',
    'End date & time',
    'Venue name',
    'Coordinates',
    "Latitude,Longitude (e.g. '45.4642,9.1900')",
    'Registration open',
    'Registration deadline',
    'Max attendees',
    '0 = unlimited.',
    'Event participation cost in EUR.  0 = free.',
    'Early-bird discount (%)',
    'Early-bird deadline',
    'Percentage discount for active members.',
    'Allow guest registration',
    'Meeting point',
    'Where participants should gather before the event start.',
    'Difficulty level',
    'Schedule',
    'Registration settings',
    'Pricing',
    'Promote',
    'Event detail page',
    'Event detail pages',
    'Root collection',
    'Starting collection for gallery display.  Sub-collections become albums.',
    'Gallery page',
    'Gallery pages',
    'Form title',
    'Success message',
    'Confirmation shown after form submission.',
    'Enable captcha',
    'Honeypot + Time check',
    'Cloudflare Turnstile',
    'hCaptcha',
    'Captcha provider',
    'Captcha site key',
    'Captcha secret key',
    'Anti-spam settings',
    'Anti-spam',
    'Contact page',
    'Contact pages',
    'Last updated',
    'Date the policy was last revised.',
    'Privacy page',
    'Privacy pages',
    'Use document-list and accordion blocks for organising documents.',
    'Transparency page',
    'Transparency pages',
    'Press email',
    'Press phone',
    'Press contact person',
    'Press contact',
    'Press page',
    'Press pages',
    'Partner index page',
    'Partner index pages',
    'ISO 3166-1 alpha-2 country code.',
    'Facebook URL',
    'Instagram URL',
    'LinkedIn URL',
    'YouTube URL',
    'Twitter / X URL',
    'Partner owner',
    'User account that manages this partner page.',
    'Owner email',
    'Contact email for the partner owner.',
    'Show this partner prominently.',
    'Display order',
    'Lower numbers appear first.',
    'Show on homepage',
    'Partnership start',
    'Partnership end',
    'Leave blank for ongoing partnerships.',
    'Social media',
    'Ownership',
    'Display settings',
    'Social',
    'Display',
    'Partner page',
    'Partner pages',
    'Velocity',
    'Heritage',
    'Terra / Eco',
    'Zen',
    'Clubs',
    'Tricolore',
    'Honeypot (no external service)',
    'OpenStreetMap',
    'Google Maps',
    'Mapbox',
    'Human-readable name shown in the header / meta tags.',
    'Site description',
    'Default meta description for SEO.',
    'Colour scheme',
    'Logo (dark variant)',
    'Optional dark-background version of the logo.',
    'Opening hours',
    'TikTok URL',
    'Navbar',
    'PWA name',
    'PWA short name',
    'PWA description',
    'PWA icon 192x192',
    'PWA icon 512x512',
    'PWA theme colour',
    'PWA background colour',
    'CAPTCHA provider',
    'CAPTCHA site key',
    'CAPTCHA secret key',
    'Map routing service',
    'Map API key',
    'Required for Google Maps / Mapbox.',
    'Default map centre',
    'Default map zoom',
    'General',
    'Branding',
    'Progressive Web App',
    'PWA',
    'Anti-spam / CAPTCHA',
    'Forms',
    'Map & routing',
    'site settings',
    'Test',
    'Payment mode',
    'Only credentials for the selected mode are used at runtime.',
    'Stripe enabled (test)',
    'Stripe public key (test)',
    'Stripe secret key (test)',
    'Stripe webhook secret (test)',
    'PayPal enabled (test)',
    'PayPal client ID (test)',
    'PayPal secret (test)',
    'Stripe enabled (live)',
    'Stripe public key (live)',
    'Stripe secret key (live)',
    'Stripe webhook secret (live)',
    'PayPal enabled (live)',
    'PayPal client ID (live)',
    'PayPal secret (live)',
    'Bank transfer enabled',
    'Account holder',
    'IBAN',
    'BIC / SWIFT',
    'Bank name',
    'Bank transfer instructions',
    "Additional instructions shown to the user (e.g. 'Include the reference in the description').",
    'Bank transfer expiry (days)',
    'Days allowed for the user to complete the bank transfer.',
    'Active mode',
    'Mode',
    'Stripe (test)',
    'PayPal (test)',
    'Test configuration',
    'Stripe (live)',
    'PayPal (live)',
    'Live configuration',
    'Bank transfer',
    'payment settings',
    'Main brand colour (hex).',
    'Secondary/accent brand colour (hex).',
    'Accent colour',
    'Accent highlight colour (hex).',
    'Surface colour',
    'Card/panel background colour (hex).',
    'Surface alt colour',
    'Alternate surface colour (hex).',
    'Text primary',
    'Main body text colour (hex).',
    'Text muted',
    'Secondary/lighter text colour (hex).',
    'Enable if this is a dark colour scheme.',
    'Brand colours',
    'Surface colours',
    'Text colours',
    'colour scheme',
    'colour schemes',
    'Show search',
    'navbar',
    'navbars',
    'Parent item',
    'Leave empty for top-level items. Select a parent for dropdown sub-items.',
    'Link page',
    'Used only when no page is selected.',
    'Open in new tab',
    'Is CTA',
    'Render as a highlighted call-to-action button.',
    'Twitter / X',
    'TikTok',
    "Short 'about' text displayed in the footer.",
    'Copyright text',
    'Contact details',
    'Social links',
    'footer',
    'footers',
    'Platform',
    'Question',
    'Answer',
    'Optional grouping label for the FAQ.',
    'FAQ',
    'FAQs',
    'Author name',
    'Author role',
    'Author photo',
    'Show this testimonial more prominently.',
    'testimonial',
    'testimonials',
    'Colour',
    'Badge/label colour (hex).',
    'news category',
    'news categories',
    'Motorcycle',
    'Rally',
    'Meeting',
    'Charity',
    'Race',
    'event category',
    'event categories',
    'photo tag',
    'photo tags',
    'partner category',
    'partner categories',
    'Attachment',
    'PDF or document attachment.',
    'Archived',
    'press release',
    'press releases',
    'Font',
    'Template',
    'Preview image',
    'brand asset',
    'brand assets',
    'Mechanics',
    'Logistics',
    'Emergency',
    'aid skill',
    'aid skills',
    'Inactive products are hidden from the storefront.',
    'Grants voting rights',
    'Grants gallery upload',
    'Grants event access',
    'Grants discount',
    'Percentage discount on events when grants_discount is on.',
    'Product info',
    'Member privileges',
    'product',
    'Uploaded by',
    'Optionally link this photo to an event.',
    'Approved at',
    'Rejection reason',
    'Uploaded at',
    'photo upload',
    'photo uploads',
    'approved',
    'pending',
    'Not found',
    'Wrong data',
    'Expired membership',
    'Partner user',
    'The partner owner who performed this verification.',
    'Which secondary factor was used for verification.',
    'Result',
    'IP address',
    'verification log',
    'verification logs',
    'Access denied. Only partner owners and staff can verify members.',
    'Rate limit exceeded. Maximum 20 verification attempts per hour.',
    'Account temporarily locked. Too many failed verification attempts. Please try again in 15 minutes.',
    'No member found with this card number.',
    "This member's membership has expired.",
    'Member verified successfully.',
    'N/A',
    'Verification failed. The provided information does not match our records.',
    'Access denied. Your membership does not include gallery upload privileges.',
    'Rejected by moderator.',
    'Membership Card',
    'Card No.',
    'Expires',
    'Barcode',
    'Download PDF',
    'No membership card has been issued yet. Please contact the club administration.',
    'Member Directory',
    'Pagination',
    'No members are currently visible in the directory.',
    'Welcome back',
    'Log in to access your profile, events, and club features.',
    'Forgot your password?',
    "Don't have an account?",
    'Are you sure you want to log out?',
    'Go back to home',
    'Become a member',
    'Choose the membership plan that best fits your needs. Combine multiple products to customize your ex',
    'Your plan',
    'year',
    'Event registration',
    'Voting rights',
    'Gallery upload',
    '%(percent)s%% discount on events',
    'Contact the club',
    'No membership plans available at this time.',
    'Reset your password',
    "Enter your email address and we'll send you a link to reset your password.",
    'Send reset link',
    'Back to login',
    'Active Member',
    'Back to Directory',
    'Create your account',
    'Join the club and access events, member directory, and more.',
    'Already have an account?',
    'Registration Confirmed',
    'Amount',
    'Bank Transfer Payment Required',
    'This is an automatic confirmation email. Please do not reply.',
    'My Favorite Events',
    'Upcoming',
    'Archive',
    'My Registrations',
    'Events map',
    'Map view of your favorite events',
    'Remove from favorites',
    'Download calendar file',
    'ICS',
    'You have not added any events to your favorites yet.',
    'Events Archive',
    'No past events in your favorites.',
    'Payment',
    'Bank Transfer Instructions',
    'Transfer Details',
    'Bank',
    'Payment Reference',
    'Copy',
    'Deadline',
    'Back to my registrations',
    'Your payment was not completed. You can try again using the link below.',
    'Try again',
    'Choose Payment Method',
    'Credit / Debit Card',
    'Pay securely with Stripe',
    'Pay with your PayPal account',
    'Pay via SEPA bank transfer',
    'Payment Confirmed',
    'Register for Event',
    'Member discount',
    'Please correct the highlighted errors below.',
    'Your Information',
    'Registration Details',
    'Registration Summary',
    'Partner Events',
    'Breadcrumb',
    'Club',
    'View on Google Maps',
    'View on partner site',
    'Events from our federated partner clubs.',
    'Partner Club',
    'All clubs',
    'Search events...',
    'No partner events found.',
    'Clear filters',
    'Club Discussion',
    'Comments are visible only to our club members. They are not shared with the partner club.',
    'Delete this comment?',
    'No comments yet. Be the first to start a discussion!',
    'Add a comment',
    'Share your thoughts with fellow club members...',
    'Post Comment',
    'Only active members can post comments.',
    'Are you interested?',
    'going',
    'interested',
    'maybe',
    'Only active members can express interest in partner events.',
    'Main navigation',
    'Toggle navigation',
    'Search...',
    'Search the site',
    'Submit search',
    'Membership card',
    'My events',
    'Member directory',
    'Request Access',
    'Request Access to Mutual Aid',
    'Submit Request',
    'radius',
    'Send Request',
    'Availability',
    'WhatsApp',
    'Send message',
    'Send Aid Request',
    'Unlock Limit Reached',
    'Contact Unlock Limit Reached',
    'Please wait before unlocking more contacts, or use the contacts you have already unlocked.',
    'Back to Mutual Aid',
    'Emergency Contacts',
    'Check back later or contact the club directly.',
    'Notification digest',
    'View details',
    'Notification history',
    'ago',
    'No notifications yet.',
    'Unsubscribe',
    'Confirm unsubscribe',
    'You can re-enable notifications at any time from your account settings.',
    'Invalid link',
    'Unsubscribed',
    'You have been unsubscribed from these notifications. You will no longer receive them.',
    'If you change your mind, you can re-enable notifications from your',
    'account settings',
    'Event period',
    'Past',
    'Event filters',
    'Registration Open',
]
