#!/usr/bin/env python3
"""
Batch-translate the Spanish .po file for ClubCMS.
Source: English msgid → Spanish msgstr
Cross-checked against Italian translations for consistency.
"""
from translate_engine import run_translation

# ──────────────────────────────────────────────────────────
#  TRANSLATION DICTIONARY  (English → Spanish)
# ──────────────────────────────────────────────────────────
TRANSLATIONS = {
    # ── AppConfig verbose_name ──
    "Core": "Núcleo",
    "Events": "Eventos",
    "Federation": "Federación",
    "Members": "Socios",
    "Mutual Aid": "Ayuda Mutua",
    "Notifications": "Notificaciones",
    "Website": "Sitio Web",

    # ── Model Meta verbose_name / verbose_name_plural ──
    "Federated Club": "Club Federado",
    "Federated Clubs": "Clubes Federados",
    "External Event": "Evento Externo",
    "External Events": "Eventos Externos",
    "External Event Interest": "Interés en Evento Externo",
    "External Event Interests": "Intereses en Eventos Externos",
    "External Event Comment": "Comentario de Evento Externo",
    "External Event Comments": "Comentarios de Eventos Externos",
    "Club User": "Usuario del Club",
    "Club Users": "Usuarios del Club",
    "Event Registration": "Inscripción al Evento",
    "Event Registrations": "Inscripciones a Eventos",
    "Event Favorite": "Evento Favorito",
    "Event Favorites": "Eventos Favoritos",
    "Event page": "Página del evento",

    # ── Events / Registration fields ──
    "Confirmed": "Confirmado",
    "Waitlist": "Lista de espera",
    "Pending": "Pendiente",
    "Paid": "Pagado",
    "Refunded": "Reembolsado",
    "Stripe": "Stripe",
    "PayPal": "PayPal",
    "Bank Transfer": "Transferencia Bancaria",
    "User": "Usuario",
    "Status": "Estado",
    "Number of guests": "Número de invitados",
    "Payment status": "Estado del pago",
    "Payment provider": "Proveedor de pago",
    "Payment ID": "ID de pago",
    "External payment reference from the provider.": "Referencia de pago externa del proveedor.",
    "Payment session ID": "ID de sesión de pago",
    "Checkout Session ID (Stripe) or Order ID (PayPal).": "ID de sesión de checkout (Stripe) o ID de pedido (PayPal).",
    "Payment amount": "Importe del pago",
    "Unique reference for bank transfers (e.g. EVT-00123-A7B3).": "Referencia única para transferencias bancarias (ej. EVT-00123-A7B3).",
    "Payment expires at": "El pago vence el",
    "Deadline for bank transfer payments.": "Fecha límite para pagos por transferencia bancaria.",
    "Guest": "Invitado",
    "Days before event": "Días antes del evento",
    "Hours before event": "Horas antes del evento",
    "Minutes before event": "Minutos antes del evento",
    "Discount percent": "Porcentaje de descuento",
    "Label": "Etiqueta",
    "Display label for this tier, e.g. 'Early Bird'.": "Etiqueta para este nivel, ej. 'Reserva anticipada'.",
    "The time offset must be greater than zero.": "El intervalo de tiempo debe ser mayor que cero.",
    "Added at": "Añadido el",
    "Registered": "Registrado",
    "Registered at": "Registrado el",
    "Cancelled": "Cancelado",
    "Event": "Evento",
    "Payment reference": "Referencia de pago",
    "Is registration deadline": "Es fecha límite de inscripción",

    # ── Events notification messages ──
    "Payment expired: {event}": "Pago vencido: {event}",
    "Your bank transfer for {event} was not received in time. Your registration has been cancelled.":
        "Tu transferencia bancaria para {event} no se recibió a tiempo. Tu inscripción ha sido cancelada.",
    "Spot available: {event}": "Plaza disponible: {event}",
    "A spot has opened up! You have been promoted from the waitlist for {event}.":
        "¡Se ha liberado una plaza! Has sido promovido de la lista de espera para {event}.",
    "Your membership does not include event registration. Please upgrade your membership.":
        "Tu membresía no incluye inscripción a eventos. Por favor, actualiza tu membresía.",
    "Please wait before toggling again.": "Espera antes de cambiar de nuevo.",
    "Payment instructions: {event}": "Instrucciones de pago: {event}",
    "Please complete the bank transfer of €{amount} with reference {ref} by {expires}.":
        "Por favor, completa la transferencia bancaria de €{amount} con referencia {ref} antes del {expires}.",
    "Payment service temporarily unavailable. Please try again.":
        "Servicio de pago temporalmente no disponible. Inténtalo de nuevo.",

    # ── Federation model help_text ──
    "Display name of the partner club": "Nombre del club asociado",
    "URL-safe identifier": "Identificador seguro para URL",
    "Partner site base URL": "URL base del sitio asociado",
    "Optional logo URL": "URL del logo (opcional)",
    "Their public API key (given to us)": "Su clave API pública (proporcionada a nosotros)",
    "Our key we gave them (auto-generated)": "Nuestra clave proporcionada a ellos (autogenerada)",
    "Share our events with this partner": "Compartir nuestros eventos con este socio",
    "Auto-approve imported events": "Aprobar automáticamente los eventos importados",
    "Sanitized HTML": "HTML saneado",

    # ── Member form fields ──
    "Select member": "Seleccionar socio",
    "Number of extra people coming with you (not counting yourself or your passenger). Example: 2":
        "Número de personas extra que vienen contigo (sin contarte a ti ni a tu pasajero). Ejemplo: 2",
    "List each guest on a separate line. Example:\\nMario Rossi\\nLucia Bianchi":
        "Enumera cada invitado en una línea separada. Ejemplo:\\nJuan García\\nMaría López",
    "Allergies, dietary needs, special requests, or anything the organizers should know.":
        "Alergias, necesidades dietéticas, peticiones especiales o cualquier cosa que los organizadores deban saber.",
    "Check this if someone will ride with you as a passenger on your motorcycle.":
        "Marca esto si alguien viajará contigo como pasajero en tu moto.",
    "If your passenger is already a club member, enable this to select them from the list.":
        "Si tu pasajero ya es socio del club, activa esto para seleccionarlo de la lista.",
    "Example: Marco": "Ejemplo: Juan",
    "Example: Verdi": "Ejemplo: García",
    "Example: marco.verdi@email.com": "Ejemplo: juan.garcia@email.com",
    "Italian tax identification code, 16 characters. Example: VRDMRC85M01H501Z":
        "Código fiscal italiano, 16 caracteres. Ejemplo: VRDMRC85M01H501Z",
    "Example: 1985-08-01": "Ejemplo: 1985-08-01",
    "Name and phone number to call in case of emergency. Example: Anna Verdi +39 340 7654321":
        "Nombre y número de teléfono de emergencia. Ejemplo: Ana García +34 600 123456",
    "Your legal first name. Example: Maria": "Tu nombre legal. Ejemplo: María",
    "Your family name. Example: Rossi": "Tu apellido. Ejemplo: García",
    "Guest names": "Nombres de los invitados",
    "Passenger first name": "Nombre del pasajero",
    "Emergency contact": "Contacto de emergencia",
    "Start typing a name to search registered members.": "Empieza a escribir un nombre para buscar socios registrados.",
    "Include country prefix. Example: +39 333 1234567": "Incluye el prefijo del país. Ejemplo: +34 600 123456",
    "We will send your registration confirmation here.": "Enviaremos tu confirmación de inscripción aquí.",

    # ── Admin panels (members) ──
    "Personal": "Personal",
    "Identity": "Identidad",
    "Address": "Dirección",
    "Membership": "Membresía",
    "Privacy": "Privacidad",

    # ── Member model fields ──
    "Username": "Nombre de usuario",
    "First name": "Nombre",
    "Last name": "Apellido",
    "Email": "Correo electrónico",
    "Display name": "Nombre visible",
    "Phone": "Teléfono",
    "Mobile": "Móvil",
    "Birth date": "Fecha de nacimiento",
    "Birth place": "Lugar de nacimiento",
    "Photo": "Foto",
    "Bio": "Biografía",
    "Fiscal code": "Código fiscal",
    "Document type": "Tipo de documento",
    "Document number": "Número de documento",
    "Document expiry": "Vencimiento del documento",
    "City": "Ciudad",
    "Province": "Provincia",
    "Postal code": "Código postal",
    "Country": "País",
    "Card number": "Número de tarjeta",
    "Membership date": "Fecha de membresía",
    "Membership expiry": "Vencimiento de membresía",
    "Is active": "Está activo",
    "Products": "Productos",
    "Show in directory": "Mostrar en el directorio",
    "Public profile": "Perfil público",
    "Show real name to members": "Mostrar nombre real a los socios",
    "Newsletter": "Boletín",
    "Email notifications": "Notificaciones por correo",
    "Push notifications": "Notificaciones push",
    "News updates": "Actualizaciones de noticias",
    "Event updates": "Actualizaciones de eventos",
    "Event reminders": "Recordatorios de eventos",
    "Membership alerts": "Alertas de membresía",
    "Partner updates": "Actualizaciones de socios",
    "Aid requests": "Solicitudes de ayuda",
    "Partner events": "Eventos de socios",
    "Partner event comments": "Comentarios de eventos de socios",
    "Digest frequency": "Frecuencia del resumen",
    "Aid available": "Ayuda disponible",
    "Aid radius km": "Radio de ayuda (km)",
    "Aid location city": "Ciudad de ubicación de ayuda",
    "Aid coordinates": "Coordenadas de ayuda",
    "Aid notes": "Notas de ayuda",

    # ── Antispam ──
    "Spam detected. Access denied.": "Spam detectado. Acceso denegado.",
    "This submission looks like spam.": "Este envío parece spam.",
    "Too many requests. Please try again later.": "Demasiadas solicitudes. Inténtalo más tarde.",
    "Are you human?": "¿Eres humano?",
    "Verify": "Verificar",
    "I am human": "Soy humano",
    "Verification failed. Please try again.": "Verificación fallida. Inténtalo de nuevo.",
    "Remember me": "Recordarme",

    # ── Website / Page models ──
    "Home Page": "Página de Inicio",
    "Content Page": "Página de Contenido",
    "News Page": "Página de Noticias",
    "News Index Page": "Índice de Noticias",
    "Gallery Page": "Página de Galería",
    "Gallery Index Page": "Índice de Galería",
    "Events Index Page": "Índice de Eventos",
    "Contact Page": "Página de Contacto",
    "Title": "Título",
    "Subtitle": "Subtítulo",
    "Body": "Cuerpo",
    "Image": "Imagen",
    "Caption": "Leyenda",
    "Author": "Autor",
    "Date": "Fecha",
    "Published": "Publicado",
    "Draft": "Borrador",
    "Summary": "Resumen",
    "Tags": "Etiquetas",
    "Category": "Categoría",
    "Categories": "Categorías",
    "Slug": "Slug",
    "SEO Title": "Título SEO",
    "Search Description": "Descripción de búsqueda",
    "Description": "Descripción",
    "Content": "Contenido",
    "Location": "Ubicación",
    "Start date": "Fecha de inicio",
    "End date": "Fecha de fin",
    "Start time": "Hora de inicio",
    "End time": "Hora de fin",
    "All day": "Todo el día",
    "Registration required": "Inscripción obligatoria",
    "Max participants": "Participantes máximos",
    "Price": "Precio",
    "Free": "Gratuito",
    "Featured": "Destacado",
    "Promoted": "Promocionado",
    "Featured image": "Imagen destacada",

    # ── StreamField blocks ──
    "Heading": "Encabezado",
    "Paragraph": "Párrafo",
    "Quote": "Cita",
    "Rich Text": "Texto Enriquecido",
    "Rich text": "Texto enriquecido",
    "Link": "Enlace",
    "URL": "URL",
    "Button": "Botón",
    "Button text": "Texto del botón",
    "Button link": "Enlace del botón",
    "Call to Action": "Llamada a la acción",
    "Background color": "Color de fondo",
    "Background image": "Imagen de fondo",
    "Text color": "Color del texto",
    "Alignment": "Alineación",
    "Left": "Izquierda",
    "Center": "Centro",
    "Right": "Derecha",
    "Full width": "Ancho completo",
    "Card": "Tarjeta",
    "Cards": "Tarjetas",
    "Column": "Columna",
    "Columns": "Columnas",
    "Section": "Sección",
    "Hero": "Hero",
    "Hero section": "Sección Hero",
    "Embed": "Incrustación",
    "Embed URL": "URL de incrustación",
    "Video": "Vídeo",
    "Document": "Documento",
    "Documents": "Documentos",
    "File": "Archivo",
    "Download": "Descargar",
    "Gallery": "Galería",
    "Slider": "Slider",
    "Testimonial": "Testimonio",
    "Testimonials": "Testimonios",
    "Icon": "Icono",
    "Feature": "Característica",
    "Features": "Características",
    "Table": "Tabla",
    "Map": "Mapa",
    "Code": "Código",
    "Accordion": "Acordeón",
    "Tab": "Pestaña",
    "Tabs": "Pestañas",
    "Spacer": "Espaciador",
    "Divider": "Divisor",
    "HTML": "HTML",
    "Raw HTML": "HTML sin formato",

    # ── Wagtail / Settings ──
    "Site Settings": "Configuración del Sitio",
    "Site settings": "Configuración del sitio",
    "Site Name": "Nombre del Sitio",
    "Site name": "Nombre del sitio",
    "Tagline": "Eslogan",
    "Logo": "Logo",
    "Favicon": "Favicon",
    "Social Media": "Redes Sociales",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "Twitter": "Twitter",
    "YouTube": "YouTube",
    "LinkedIn": "LinkedIn",
    "Footer": "Pie de página",
    "Footer text": "Texto del pie de página",
    "Copyright": "Copyright",
    "Analytics": "Analítica",
    "Google Analytics ID": "ID de Google Analytics",
    "Theme": "Tema",
    "Color scheme": "Esquema de colores",
    "Primary color": "Color primario",
    "Secondary color": "Color secundario",
    "Accent color": "Color de acento",
    "Dark mode": "Modo oscuro",
    "Light mode": "Modo claro",
    "Auto": "Automático",

    # ── Notifications ──
    "Notification": "Notificación",
    "Notification Type": "Tipo de Notificación",
    "Notification type": "Tipo de notificación",
    "Message": "Mensaje",
    "Read": "Leído",
    "Unread": "No leído",
    "Sent": "Enviado",
    "Mark as read": "Marcar como leído",
    "Mark all as read": "Marcar todo como leído",
    "Delete": "Eliminar",
    "No notifications": "Sin notificaciones",
    "Notification Settings": "Configuración de Notificaciones",
    "Notification settings": "Configuración de notificaciones",
    "Enable email notifications": "Activar notificaciones por correo",
    "Enable push notifications": "Activar notificaciones push",
    "Notification Preference": "Preferencia de Notificación",
    "Notification Preferences": "Preferencias de Notificación",
    "Channel": "Canal",
    "Channels": "Canales",

    # ── Mutual Aid ──
    "Aid Request": "Solicitud de Ayuda",
    "Aid Requests": "Solicitudes de Ayuda",
    "Aid Offer": "Oferta de Ayuda",
    "Aid Offers": "Ofertas de Ayuda",
    "Aid Category": "Categoría de Ayuda",
    "Aid Categories": "Categorías de Ayuda",
    "Urgency": "Urgencia",
    "Low": "Baja",
    "Medium": "Media",
    "High": "Alta",
    "Critical": "Crítica",
    "Open": "Abierto",
    "Closed": "Cerrado",
    "In Progress": "En Curso",
    "Resolved": "Resuelto",
    "Latitude": "Latitud",
    "Longitude": "Longitud",
    "Radius": "Radio",
    "Available": "Disponible",
    "Unavailable": "No disponible",
    "Skills": "Habilidades",
    "Equipment": "Equipamiento",
    "Notes": "Notas",
    "Active": "Activo",
    "Inactive": "Inactivo",
    "Expires at": "Vence el",
    "Created at": "Creado el",
    "Updated at": "Actualizado el",
    "Created by": "Creado por",

    # ── Common actions / UI ──
    "Save": "Guardar",
    "Cancel": "Cancelar",
    "Edit": "Editar",
    "Add": "Añadir",
    "Remove": "Eliminar",
    "Search": "Buscar",
    "Filter": "Filtrar",
    "Sort": "Ordenar",
    "View": "Ver",
    "Details": "Detalles",
    "Back": "Atrás",
    "Next": "Siguiente",
    "Previous": "Anterior",
    "Submit": "Enviar",
    "Confirm": "Confirmar",
    "Close": "Cerrar",
    "Update": "Actualizar",
    "Yes": "Sí",
    "No": "No",
    "None": "Ninguno",
    "All": "Todos",
    "Name": "Nombre",
    "Type": "Tipo",
    "Actions": "Acciones",
    "Loading...": "Cargando...",
    "Error": "Error",
    "Success": "Éxito",
    "Warning": "Aviso",
    "Info": "Info",

    # ── Wagtail snippets ──
    "Snippet": "Fragmento",
    "Snippets": "Fragmentos",
    "Menu item": "Elemento de menú",
    "Menu items": "Elementos de menú",
    "Navigation": "Navegación",
    "External link": "Enlace externo",
    "Internal link": "Enlace interno",
    "Page": "Página",
    "Pages": "Páginas",
    "Parent page": "Página padre",
    "Order": "Orden",
    "Sort order": "Orden de clasificación",
    "Show in menu": "Mostrar en el menú",

    # ── Uploads / Gallery ──
    "Upload": "Subir",
    "Uploads": "Subidas",
    "Album": "Álbum",
    "Albums": "Álbumes",
    "Upload date": "Fecha de subida",
    "File size": "Tamaño del archivo",
    "File type": "Tipo de archivo",
    "Width": "Ancho",
    "Height": "Alto",
    "Alt text": "Texto alternativo",
    "Thumbnail": "Miniatura",

    # ── Partners ──
    "Partner": "Socio",
    "Partners": "Socios",
    "Partner Category": "Categoría de Socio",
    "Partner Categories": "Categorías de Socios",
    "Discount": "Descuento",
    "Benefit": "Beneficio",
    "Benefits": "Beneficios",
    "Valid from": "Válido desde",
    "Valid until": "Válido hasta",
    "Terms and conditions": "Términos y condiciones",

    # ── Press Office ──
    "Press Release": "Comunicado de Prensa",
    "Press Releases": "Comunicados de Prensa",

    # ── Registration form ──
    "Registration": "Registro",
    "Register": "Registrarse",
    "Login": "Iniciar sesión",
    "Logout": "Cerrar sesión",
    "Sign up": "Registrarse",
    "Sign in": "Iniciar sesión",
    "Password": "Contraseña",
    "Confirm password": "Confirmar contraseña",
    "Forgot password?": "¿Olvidaste tu contraseña?",
    "Reset password": "Restablecer contraseña",
    "Change password": "Cambiar contraseña",
    "Account": "Cuenta",
    "Profile": "Perfil",
    "Settings": "Configuración",
    "Preferences": "Preferencias",

    # ── Event-specific ──
    "Upcoming events": "Próximos eventos",
    "Past events": "Eventos pasados",
    "No upcoming events": "No hay eventos próximos",
    "Event details": "Detalles del evento",
    "Register for event": "Inscribirse al evento",
    "Cancel registration": "Cancelar inscripción",
    "Registration closed": "Inscripción cerrada",
    "Event full": "Evento completo",
    "Spots available": "Plazas disponibles",
    "Organizer": "Organizador",
    "Route": "Ruta",
    "Route map": "Mapa de ruta",
    "Distance": "Distancia",
    "Difficulty": "Dificultad",
    "Easy": "Fácil",
    "Moderate": "Moderada",
    "Hard": "Difícil",
    "Expert": "Experto",
    "GPX file": "Archivo GPX",
    "Route description": "Descripción de la ruta",
    "Waypoints": "Puntos de ruta",
    "Departure": "Salida",
    "Arrival": "Llegada",
    "Duration": "Duración",

    # ── Verification / Moderation ──
    "Verified": "Verificado",
    "Not verified": "No verificado",
    "Verification": "Verificación",
    "Verification code": "Código de verificación",
    "Verification token": "Token de verificación",
    "Approved": "Aprobado",
    "Rejected": "Rechazado",
    "Pending review": "Pendiente de revisión",
    "Moderation": "Moderación",
    "Report": "Reportar",
    "Reported": "Reportado",
    "Ban": "Bloquear",
    "Banned": "Bloqueado",

    # ── Interest / Comment ──
    "Interested": "Interesado",
    "Maybe": "Quizás",
    "Going": "Asistiré",
    "Interest level": "Nivel de interés",
    "Comment": "Comentario",
    "Comments": "Comentarios",
    "Add comment": "Añadir comentario",
    "Edit comment": "Editar comentario",
    "Delete comment": "Eliminar comentario",
    "Reply": "Responder",

    # ── Sync / Federation ──
    "Last sync": "Última sincronización",
    "Last error": "Último error",
    "Is approved": "Está aprobado",
    "Source club": "Club de origen",
    "External ID": "ID externo",
    "Event name": "Nombre del evento",
    "Location name": "Nombre del lugar",
    "Location address": "Dirección del lugar",
    "Event status": "Estado del evento",
    "Image URL": "URL de imagen",
    "Detail URL": "URL de detalle",
    "Is hidden": "Está oculto",
    "Fetched at": "Obtenido el",
    "Short code": "Código corto",
    "Base URL": "URL base",
    "Logo URL": "URL del logo",
    "API key": "Clave API",

    # ── Misc field labels ──
    "Scheduled": "Programado",
    "Moved Online": "Movido a Online",
    "Postponed": "Aplazado",
    "EventScheduled": "Programado",
    "EventCancelled": "Cancelado",
    "EventPostponed": "Aplazado",
    "EventMovedOnline": "Movido a Online",
    "True": "Verdadero",
    "False": "Falso",
    "Enabled": "Activado",
    "Disabled": "Desactivado",

    # ── SEO / JSON-LD ──
    "Structured data": "Datos estructurados",
    "Schema type": "Tipo de esquema",
    "JSON-LD": "JSON-LD",
    "Open Graph": "Open Graph",
    "Twitter Card": "Twitter Card",
    "Canonical URL": "URL canónica",
    "Robots": "Robots",
    "Sitemap": "Mapa del sitio",
    "sitemap.xml": "sitemap.xml",

    # ── Wagtail admin ──
    "Dashboard": "Panel de control",
    "Explorer": "Explorador",
    "Images": "Imágenes",
    "Search terms": "Términos de búsqueda",
    "Search promotions": "Promociones de búsqueda",
    "Redirects": "Redirecciones",
    "Users": "Usuarios",
    "Groups": "Grupos",
    "Sites": "Sitios",
    "Collections": "Colecciones",
    "Workflows": "Flujos de trabajo",
    "Tasks": "Tareas",
    "Locked pages": "Páginas bloqueadas",
    "Aging pages": "Páginas antiguas",
    "Reports": "Informes",

    # ── i18n / locale ──
    "Language": "Idioma",
    "English": "Inglés",
    "Italian": "Italiano",
    "French": "Francés",
    "German": "Alemán",
    "Spanish": "Español",
    "Select language": "Seleccionar idioma",

    # ── Form validations ──
    "This field is required.": "Este campo es obligatorio.",
    "Enter a valid email address.": "Introduce una dirección de correo válida.",
    "Enter a valid URL.": "Introduce una URL válida.",
    "Enter a valid value.": "Introduce un valor válido.",
    "Ensure this value is greater than or equal to %(limit_value)s.": "Asegúrate de que este valor sea mayor o igual a %(limit_value)s.",
    "Ensure this value is less than or equal to %(limit_value)s.": "Asegúrate de que este valor sea menor o igual a %(limit_value)s.",

    # ── Privacy / GDPR ──
    "I accept the <a href='/privacy/' target='_blank' rel='noopener'>terms and conditions</a>":
        "Acepto los <a href='/privacy/' target='_blank' rel='noopener'>términos y condiciones</a>",

    # ── Color Scheme choices ──
    "light": "claro",
    "dark": "oscuro",
    "auto": "automático",
    "Light": "Claro",
    "Dark": "Oscuro",

    # ── PWA / Push ──
    "Install app": "Instalar aplicación",
    "Subscribe to notifications": "Suscribirse a notificaciones",
    "Unsubscribe from notifications": "Cancelar suscripción a notificaciones",
    "Offline": "Sin conexión",
    "Online": "En línea",
    "Update available": "Actualización disponible",
    "Refresh": "Actualizar",

    # ── Contribution / Moderation ──
    "Contribution": "Contribución",
    "Contributions": "Contribuciones",
    "Contributor": "Colaborador",
    "Contributors": "Colaboradores",
    "Suggestion": "Sugerencia",
    "Suggestions": "Sugerencias",
    "Pending approval": "Pendiente de aprobación",

    # ── Time-related ──
    "Today": "Hoy",
    "Tomorrow": "Mañana",
    "Yesterday": "Ayer",
    "This week": "Esta semana",
    "Next week": "Próxima semana",
    "This month": "Este mes",
    "Next month": "Próximo mes",
    "Daily": "Diario",
    "Weekly": "Semanal",
    "Monthly": "Mensual",
    "Never": "Nunca",

    # ── Product / membership tiers ──
    "Product": "Producto",
    "Product name": "Nombre del producto",
    "Product type": "Tipo de producto",
    "Includes event registration": "Incluye inscripción a eventos",
    "Annual": "Anual",

    # ── Email subjects / messages ──
    "Welcome": "Bienvenido",
    "Goodbye": "Adiós",
    "Thank you": "Gracias",
    "Confirmation": "Confirmación",
    "Reminder": "Recordatorio",
    "Alert": "Alerta",
    "Important": "Importante",
    "New": "Nuevo",

    # ── Common model field names as verbose_name ──
    "address": "dirección",
    "city": "ciudad",
    "province": "provincia",
    "postal code": "código postal",
    "country": "país",
    "phone": "teléfono",
    "mobile": "móvil",
    "email": "correo electrónico",
    "first name": "nombre",
    "last name": "apellido",
    "display name": "nombre visible",
    "birth date": "fecha de nacimiento",
    "birth place": "lugar de nacimiento",
    "photo": "foto",
    "bio": "biografía",
    "fiscal code": "código fiscal",
    "document type": "tipo de documento",
    "document number": "número de documento",
    "document expiry": "vencimiento del documento",
    "card number": "número de tarjeta",
    "membership date": "fecha de membresía",
    "membership expiry": "vencimiento de membresía",
    "is active": "está activo",
    "show in directory": "mostrar en el directorio",
    "public profile": "perfil público",
    "show real name to members": "mostrar nombre real a los socios",
    "newsletter": "boletín",
    "email notifications": "notificaciones por correo",
    "push notifications": "notificaciones push",
    "news updates": "actualizaciones de noticias",
    "event updates": "actualizaciones de eventos",
    "event reminders": "recordatorios de eventos",
    "membership alerts": "alertas de membresía",
    "partner updates": "actualizaciones de socios",
    "aid requests": "solicitudes de ayuda",
    "partner events": "eventos de socios",
    "partner event comments": "comentarios de eventos de socios",
    "digest frequency": "frecuencia del resumen",
    "aid available": "ayuda disponible",
    "aid radius km": "radio de ayuda (km)",
    "aid location city": "ciudad de ubicación de ayuda",
    "aid coordinates": "coordenadas de ayuda",
    "aid notes": "notas de ayuda",
    "products": "productos",

    # ── mutual_aid model strings ──
    "request": "solicitud",
    "offer": "oferta",
    "Roadside assistance": "Asistencia en carretera",
    "Mechanical help": "Ayuda mecánica",
    "Transport": "Transporte",
    "Accommodation": "Alojamiento",
    "Medical": "Médico",
    "Other": "Otro",
    "other": "otro",
    "Description of the problem or assistance needed": "Descripción del problema o asistencia necesaria",
    "Title of the aid request": "Título de la solicitud de ayuda",
    "Aid request": "Solicitud de ayuda",
    "Aid offer": "Oferta de ayuda",
    "Responder": "Socorrista",
    "Requester": "Solicitante",
    "Response": "Respuesta",
    "Responses": "Respuestas",
    "Aid Response": "Respuesta de Ayuda",
    "Aid Responses": "Respuestas de Ayuda",
    "Response message": "Mensaje de respuesta",
    "Estimated arrival": "Llegada estimada",
    "Can help": "Puede ayudar",
    "On the way": "En camino",
    "Arrived": "Llegado",
    "Completed": "Completado",
    "Did not show": "No se presentó",

    # ── Notification types ──
    "event_registration": "inscripción_evento",
    "event_reminder": "recordatorio_evento",
    "event_update": "actualización_evento",
    "membership_expiry": "vencimiento_membresía",
    "aid_request": "solicitud_ayuda",
    "aid_response": "respuesta_ayuda",
    "partner_event": "evento_socio",
    "system": "sistema",
    "general": "general",
    "email": "correo",
    "push": "push",
    "in_app": "en_app",
    "both": "ambos",

    # ── Additional form/template strings ──
    "Are you sure?": "¿Estás seguro?",
    "This action cannot be undone.": "Esta acción no se puede deshacer.",
    "No results found.": "No se encontraron resultados.",
    "Showing %(start)s to %(end)s of %(total)s results": "Mostrando %(start)s a %(end)s de %(total)s resultados",
    "Page %(current)s of %(total)s": "Página %(current)s de %(total)s",
    "Items per page": "Elementos por página",
    "Apply": "Aplicar",
    "Reset": "Restablecer",
    "Clear": "Limpiar",
    "Select all": "Seleccionar todo",
    "Deselect all": "Deseleccionar todo",
    "Export": "Exportar",
    "Import": "Importar",
    "CSV": "CSV",
    "PDF": "PDF",
    "Print": "Imprimir",

    # ── Registration flow ──
    "Passenger": "Pasajero",
    "Has passenger": "Tiene pasajero",
    "Passenger is member": "El pasajero es socio",
    "Passenger name": "Nombre del pasajero",
    "Number of extra guests": "Número de invitados extra",
    "Special requests": "Peticiones especiales",
    "Total": "Total",
    "Subtotal": "Subtotal",
    "Tax": "Impuesto",
    "Registration date": "Fecha de inscripción",
    "Registration status": "Estado de inscripción",
    "Confirm registration": "Confirmar inscripción",
    "cancel": "cancelar",
    "Extra content": "Contenido extra",

    # ── More website model strings ──
    "Hero image": "Imagen hero",
    "Intro": "Introducción",
    "intro": "introducción",
    "Related pages": "Páginas relacionadas",
    "Related links": "Enlaces relacionados",
    "Sidebar": "Barra lateral",
    "Header": "Encabezado",
    "Main content": "Contenido principal",
    "Call to action": "Llamada a la acción",
    "call to action": "llamada a la acción",
    "Banner": "Banner",
    "Promo": "Promoción",
    "Highlight": "Destacado",
    "Text": "Texto",
    "text": "texto",
    "Block type": "Tipo de bloque",

    # ── Error messages ──
    "An error occurred.": "Ha ocurrido un error.",
    "Permission denied.": "Permiso denegado.",
    "Not found.": "No encontrado.",
    "Page not found": "Página no encontrada",
    "Server error": "Error del servidor",
    "Bad request": "Solicitud incorrecta",
    "Forbidden": "Prohibido",
    "Unauthorized": "No autorizado",
    "Service unavailable": "Servicio no disponible",

    # ── Pricing tiers ──
    "Early Bird": "Reserva anticipada",
    "Regular": "Regular",
    "Late": "Tardío",
    "VIP": "VIP",
    "Standard": "Estándar",
    "Premium": "Premium",
    "Basic": "Básico",

    # ── Additional wagtail/website fields ──
    "Published date": "Fecha de publicación",
    "Publish date": "Fecha de publicación",
    "Expire date": "Fecha de vencimiento",
    "Go live date": "Fecha de publicación",
    "First published at": "Primera publicación",
    "Last published at": "Última publicación",
    "Latest revision created at": "Última revisión creada el",
    "Live": "Publicado",
    "Has unpublished changes": "Tiene cambios sin publicar",
    "Locked": "Bloqueado",
    "Locked by": "Bloqueado por",
    "Locked at": "Bloqueado el",

    # ── Menu/admin strings Wagtail ──
    "Menu label": "Etiqueta de menú",
    "Admin display title": "Título de visualización admin",

    # ── Additional mutual aid ──
    "Accept": "Aceptar",
    "Reject": "Rechazar",
    "Withdraw": "Retirar",
    "Confirm arrival": "Confirmar llegada",
    "Mark as resolved": "Marcar como resuelto",
    "Request help": "Solicitar ayuda",
    "Offer help": "Ofrecer ayuda",
    "Your location": "Tu ubicación",
    "Distance from you": "Distancia desde ti",
    "km": "km",

    # ── Additional notification messages ──
    "You have %(count)s new notifications": "Tienes %(count)s nuevas notificaciones",
    "No new notifications": "No hay nuevas notificaciones",
    "View all notifications": "Ver todas las notificaciones",
    "Notification sent": "Notificación enviada",
    "Notification deleted": "Notificación eliminada",

    # ── Choices for document_type ──
    "ID Card": "Documento de identidad",
    "Passport": "Pasaporte",
    "Driving License": "Permiso de conducir",

    # ── Additional registration ──
    "Check-in": "Check-in",
    "Checked in": "Check-in realizado",
    "Not checked in": "Check-in no realizado",
    "QR Code": "Código QR",
    "Scan QR code": "Escanear código QR",

    # ── Additional patterns ──
    "per year": "al año",
    "per month": "al mes",
    "valid": "válido",
    "invalid": "no válido",
    "required": "obligatorio",
    "optional": "opcional",
    "default": "predeterminado",
    "custom": "personalizado",
    "public": "público",
    "private": "privado",
    "visible": "visible",
    "hidden": "oculto",
    "enabled": "activado",
    "disabled": "desactivado",

    # ══════════════════════════════════════════════════════
    #  PASS 2 — remaining strings
    # ══════════════════════════════════════════════════════

    # ── Membership card / QR ──
    "No membership card available.": "No hay tarjeta de socio disponible.",
    "QR code generation not available.": "Generación de código QR no disponible.",
    "Barcode generation not available.": "Generación de código de barras no disponible.",
    "Your name": "Tu nombre",
    "Phone number": "Número de teléfono",
    "Email address": "Dirección de correo electrónico",
    "Your current location": "Tu ubicación actual",
    "Description must be 5000 characters or fewer.": "La descripción debe tener 5000 caracteres o menos.",
    "Why do you need access? (optional)": "¿Por qué necesitas acceso? (opcional)",
    "Role": "Rol",
    "Emergency Contact": "Contacto de Emergencia",
    "Introduction": "Introducción",
    "Emergency contacts": "Contactos de emergencia",
    "Default map radius (km)": "Radio de mapa predeterminado (km)",
    "Enable federation": "Activar la federación",

    # ── Mutual Aid Pages ──
    "Mutual Aid Page": "Página de Ayuda Mutua",
    "Mutual Aid Pages": "Páginas de Ayuda Mutua",
    "Show phone number": "Mostrar número de teléfono",
    "Show mobile number": "Mostrar número de móvil",
    "Show WhatsApp availability": "Mostrar disponibilidad de WhatsApp",
    "Show email address": "Mostrar dirección de correo",
    "Show exact location": "Mostrar ubicación exacta",
    "If disabled, only the city name is shown.": "Si está desactivado, solo se muestra el nombre de la ciudad.",
    "Show profile photo": "Mostrar foto de perfil",
    "Show bio": "Mostrar biografía",
    "Show availability hours": "Mostrar horario de disponibilidad",
    "Aid Privacy Settings": "Configuración de Privacidad de Ayuda",

    # ── Urgency levels ──
    "Low - can wait": "Baja - puede esperar",
    "Medium - within a day": "Media - en un día",
    "High - urgent": "Alta - urgente",
    "Emergency - immediate": "Emergencia - inmediato",
    "Accepted": "Aceptado",
    "In progress": "En curso",

    # ── Aid issue types ──
    "Breakdown": "Avería",
    "Flat tire": "Pinchazo",
    "Out of fuel": "Sin combustible",
    "Accident": "Accidente",
    "Need towing": "Necesita remolque",
    "Need tools": "Necesita herramientas",
    "Need transport": "Necesita transporte",
    "Need accommodation": "Necesita alojamiento",
    "Helper": "Ayudante",
    "Requester name": "Nombre del solicitante",
    "Requester phone": "Teléfono del solicitante",
    "Requester email": "Correo del solicitante",
    "Requester (if member)": "Solicitante (si es socio)",
    "Issue type": "Tipo de problema",
    "Where are you? Address or coordinates.": "¿Dónde estás? Dirección o coordenadas.",

    # ── Federation access ──
    "From federation": "De la federación",
    "Federation access": "Acceso federación",
    "Can contact helpers": "Puede contactar ayudantes",
    "External user ID": "ID de usuario externo",
    "External display name": "Nombre visible externo",
    "Contacts unlocked": "Contactos desbloqueados",
    "Access level": "Nivel de acceso",
    "Approved by": "Aprobado por",
    "Federated Aid Access": "Acceso Ayuda Federada",
    "Federated Aid Access Grants": "Permisos de Acceso Ayuda Federada",
    "Denied": "Denegado",
    "Federated access": "Acceso federado",
    "Why are you requesting access?": "¿Por qué solicitas acceso?",
    "Reviewed by": "Revisado por",
    "Reviewed at": "Revisado el",
    "Federated Aid Access Request": "Solicitud de Acceso Ayuda Federada",
    "Federated Aid Access Requests": "Solicitudes de Acceso Ayuda Federada",
    "Contact Unlock": "Desbloqueo de Contacto",
    "Contact Unlocks": "Desbloqueos de Contactos",
    "Active membership required.": "Membresía activa obligatoria.",

    # ── Notification types ──
    "News published": "Noticia publicada",
    "Event published": "Evento publicado",
    "Event reminder": "Recordatorio de evento",
    "Weekend favorites": "Favoritos del fin de semana",
    "Registration opens": "Apertura de inscripciones",
    "Photo approved": "Foto aprobada",
    "Membership expiring": "Membresía por vencer",
    "Partner news": "Noticias de socios",
    "Partner event interest": "Interés en evento de socio",
    "Partner event comment": "Comentario de evento de socio",
    "Partner event cancelled": "Evento de socio cancelado",
    "Mutual aid request": "Solicitud de ayuda mutua",
    "Mutual aid access request": "Solicitud de acceso a ayuda mutua",
    "Payment instructions": "Instrucciones de pago",
    "Payment confirmed": "Pago confirmado",
    "Payment expired": "Pago vencido",
    "Registration cancelled": "Inscripción cancelada",
    "Promoted from waitlist": "Promovido de la lista de espera",
    "Push notification": "Notificación push",
    "In-app notification": "Notificación en la app",
    "Failed": "Fallido",
    "Skipped": "Omitido",

    # ── Notification model fields (lowercase) ──
    "notification type": "tipo de notificación",
    "content type": "tipo de contenido",
    "object ID": "ID de objeto",
    "recipient": "destinatario",
    "channel": "canal",
    "status": "estado",
    "title": "título",
    "body": "cuerpo",
    "scheduled for": "programado para",
    "If set, notification will not be sent before this time.": "Si se establece, la notificación no se enviará antes de este momento.",
    "sent at": "enviado el",
    "created at": "creado el",
    "error message": "mensaje de error",
    "notification": "notificación",
    "notifications": "notificaciones",

    # ── Push subscriptions ──
    "user": "usuario",
    "endpoint": "endpoint",
    "Push service URL": "URL del servicio push",
    "p256dh key": "clave p256dh",
    "Client public encryption key": "Clave pública de cifrado del cliente",
    "auth key": "clave de autenticación",
    "Client auth secret": "Secreto de autenticación del cliente",
    "active": "activo",
    "last used": "último uso",
    "user agent": "user agent",
    "push subscription": "suscripción push",
    "push subscriptions": "suscripciones push",
    "token": "token",
    "unsubscribe token": "token de cancelación",
    "unsubscribe tokens": "tokens de cancelación",
    "Invalid JSON body": "Cuerpo JSON no válido",
    "Endpoint is required": "El endpoint es obligatorio",
    "Endpoint must use HTTPS": "El endpoint debe usar HTTPS",
    "Encryption keys are required": "Las claves de cifrado son obligatorias",

    # ── StreamField blocks – gallery/media ──
    "Article gallery": "Galería del artículo",
    "Event gallery": "Galería del evento",
    "Event location map": "Mapa de ubicación del evento",
    "Card thumbnail image.": "Imagen miniatura de la tarjeta.",
    "Optional badge text (e.g. date, category label).": "Texto de insignia opcional (ej. fecha, etiqueta de categoría).",
    "Card title.": "Título de la tarjeta.",
    "Short description text.": "Breve texto descriptivo.",
    "Link to page": "Enlace a la página",
    "External URL": "URL externa",
    "Used only if no internal page is selected.": "Se usa solo si no se selecciona una página interna.",
    "Button / link label.": "Etiqueta del botón / enlace.",
    "Optional section title above the grid.": "Título de sección opcional sobre la cuadrícula.",
    "2 columns": "2 columnas",
    "3 columns": "3 columnas",
    "4 columns": "4 columnas",
    "Number of columns on desktop.": "Número de columnas en escritorio.",
    "Default": "Predeterminado",
    "Outlined": "Con borde",
    "Elevated / shadow": "Elevado / sombra",
    "Minimal": "Mínimo",
    "Visual style for the cards.": "Estilo visual de las tarjetas.",
    "Cards grid": "Cuadrícula de tarjetas",

    # ── CTA block ──
    "CTA headline.": "Título CTA.",
    "Supporting text.": "Texto de apoyo.",
    "Button label.": "Etiqueta del botón.",
    "Button page link": "Enlace de página del botón",
    "Button external URL": "URL externa del botón",
    "Primary colour": "Color primario",
    "Gradient": "Degradado",
    "Image background": "Fondo de imagen",
    "Background style for this section.": "Estilo de fondo para esta sección.",
    "Background image (only used with 'Image background' style).": "Imagen de fondo (solo se usa con el estilo 'Fondo de imagen').",

    # ── Statistics block ──
    "The numeric value or short text (e.g. '1500+').": "El valor numérico o texto corto (ej. '1500+').",
    "Description of the stat (e.g. 'Members').": "Descripción de la estadística (ej. 'Socios').",
    "Optional icon class name.": "Nombre de clase de icono opcional.",
    "Statistic": "Estadística",
    "Optional section title.": "Título de sección opcional.",
    "Statistics": "Estadísticas",

    # ── Testimonial / Quote block ──
    "The quote text.": "El texto de la cita.",
    "Name of the person quoted.": "Nombre de la persona citada.",
    "Role or title of the author (e.g. 'President').": "Rol o título del autor (ej. 'Presidente').",
    "Optional portrait of the author.": "Retrato opcional del autor.",

    # ── Timeline block ──
    "Year or date label (e.g. '2015').": "Año o etiqueta de fecha (ej. '2015').",
    "Event or milestone title.": "Título del evento o hito.",
    "Detailed description of this event.": "Descripción detallada de este evento.",
    "Timeline entry": "Entrada de cronología",
    "Timeline entries": "Entradas de cronología",
    "Timeline": "Cronología",

    # ── Team block ──
    "Position or title.": "Posición o título.",
    "Short biography.": "Breve biografía.",
    "Team member": "Miembro del equipo",
    "Optional section title (e.g. 'Board of Directors').": "Título de sección opcional (ej. 'Junta Directiva').",
    "Team members": "Miembros del equipo",
    "Team grid": "Cuadrícula del equipo",

    # ── Newsletter block ──
    "Stay updated": "Mantente informado",
    "Form heading.": "Encabezado del formulario.",
    "Short text explaining what subscribers will receive.": "Breve texto que explica lo que recibirán los suscriptores.",
    "Subscribe": "Suscribirse",
    "Newsletter signup": "Suscripción al boletín",

    # ── Alert block ──
    "Alert message content.": "Contenido del mensaje de alerta.",
    "Danger": "Peligro",
    "Visual style and severity of the alert.": "Estilo visual y gravedad de la alerta.",
    "Allow users to dismiss this alert.": "Permitir a los usuarios cerrar esta alerta.",

    # ── Slider / Hero slider ──
    "Slide background image.": "Imagen de fondo de la diapositiva.",
    "Slide headline.": "Título de la diapositiva.",
    "Optional subtitle text.": "Texto de subtítulo opcional.",
    "CTA text": "Texto CTA",
    "CTA page link": "Enlace de página CTA",
    "CTA external URL": "URL externa CTA",
    "Slide": "Diapositiva",
    "Slides": "Diapositivas",
    "Automatically advance slides.": "Avance automático de diapositivas.",
    "Time between slides in milliseconds.": "Tiempo entre diapositivas en milisegundos.",
    "Half screen": "Media pantalla",
    "Three-quarter screen": "Tres cuartos de pantalla",
    "Full screen": "Pantalla completa",
    "Slider height.": "Altura del slider.",
    "Show navigation arrows.": "Mostrar flechas de navegación.",
    "Show dot indicators.": "Mostrar indicadores de puntos.",
    "Hero slider": "Slider hero",

    # ── Hero banner ──
    "Hero background image.": "Imagen de fondo hero.",
    "Small badge text above the title (e.g. 'Est. 2010').": "Pequeño texto de insignia sobre el título (ej. 'Est. 2010').",
    "Main headline.": "Título principal.",
    "Supporting text below the title.": "Texto de apoyo bajo el título.",
    "Secondary CTA text": "Texto CTA secundario",
    "Optional secondary button label.": "Etiqueta opcional del botón secundario.",
    "Secondary CTA page link": "Enlace de página CTA secundario",
    "Secondary CTA external URL": "URL externa CTA secundaria",
    "Light overlay": "Superposición clara",
    "Dark overlay": "Superposición oscura",
    "Gradient overlay": "Superposición degradada",
    "Overlay style over the background image.": "Estilo de superposición sobre la imagen de fondo.",
    "Bottom left": "Abajo a la izquierda",
    "Bottom right": "Abajo a la derecha",
    "Position of the text overlay.": "Posición de la superposición de texto.",
    "Hero banner": "Banner hero",

    # ── Hero countdown ──
    "Select an event to count down to.": "Selecciona un evento para la cuenta atrás.",
    "Optional background image. Falls back to event cover image.": "Imagen de fondo opcional. Si no hay, usa la imagen de portada del evento.",
    "Override the event title in the hero.": "Sobreescribe el título del evento en el hero.",
    "Hero countdown": "Cuenta atrás hero",

    # ── Hero video ──
    "URL to the video file (MP4 recommended).": "URL del archivo de vídeo (MP4 recomendado).",
    "Displayed on mobile or when video cannot play.": "Se muestra en móvil o cuando el vídeo no se puede reproducir.",
    "Mute the video (required for autoplay on most browsers).": "Silenciar el vídeo (necesario para reproducción automática en la mayoría de navegadores).",
    "Loop the video.": "Reproducir el vídeo en bucle.",
    "Hero video": "Vídeo hero",

    # ── Accordion block ──
    "Accordion panel header.": "Encabezado del panel acordeón.",
    "Panel content revealed when expanded.": "Contenido del panel mostrado al expandir.",
    "Accordion item": "Elemento de acordeón",
    "Optional section title above the accordion.": "Título de sección opcional sobre el acordeón.",
    "Panels": "Paneles",

    # ── Tab block ──
    "Tab label.": "Etiqueta de pestaña.",
    "Tab panel content.": "Contenido del panel de pestaña.",

    # ── Two columns block ──
    "Left column": "Columna izquierda",
    "Right column": "Columna derecha",
    "50 / 50": "50 / 50",
    "33 / 67": "33 / 67",
    "67 / 33": "67 / 33",
    "25 / 75": "25 / 75",
    "75 / 25": "75 / 25",
    "Column width ratio.": "Proporción del ancho de columnas.",
    "Two columns": "Dos columnas",

    # ── Section block ──
    "Optional section heading.": "Encabezado de sección opcional.",
    "Section body content.": "Contenido del cuerpo de la sección.",
    "Secondary colour": "Color secundario",
    "Light grey": "Gris claro",
    "Background style.": "Estilo de fondo.",
    "Small": "Pequeño",
    "Large": "Grande",
    "Extra large": "Extra grande",
    "Vertical padding.": "Relleno vertical.",

    # ── Separator/spacer ──
    "Horizontal line": "Línea horizontal",
    "Dots": "Puntos",
    "Blank space": "Espacio en blanco",
    "Separator visual style.": "Estilo visual del separador.",
    "Small (1rem)": "Pequeño (1rem)",
    "Medium (2rem)": "Mediano (2rem)",
    "Large (4rem)": "Grande (4rem)",
    "Extra large (6rem)": "Extra grande (6rem)",
    "Amount of vertical space.": "Cantidad de espacio vertical.",

    # ── Gallery block ──
    "Optional caption displayed below the image.": "Leyenda opcional mostrada bajo la imagen.",
    "Gallery image": "Imagen de galería",
    "Optional gallery title.": "Título de galería opcional.",
    "6 columns": "6 columnas",
    "Enable lightbox for full-size image viewing.": "Activar lightbox para ver imágenes a tamaño completo.",
    "Auto (original)": "Automático (original)",
    "Square (1:1)": "Cuadrado (1:1)",
    "Landscape (4:3)": "Horizontal (4:3)",
    "Widescreen (16:9)": "Panorámico (16:9)",
    "Portrait (3:4)": "Vertical (3:4)",
    "Thumbnail aspect ratio.": "Proporción de aspecto de la miniatura.",

    # ── Video embed ──
    "Paste a video URL (YouTube, Vimeo, etc.).": "Pega una URL de vídeo (YouTube, Vimeo, etc.).",
    "Optional caption displayed below the video.": "Leyenda opcional mostrada bajo el vídeo.",
    "Autoplay the video (muted).": "Reproducir automáticamente el vídeo (silenciado).",
    "Video embed": "Vídeo incrustado",

    # ── Image block ──
    "Centred": "Centrado",
    "Float left": "Alineado a la izquierda",
    "Float right": "Alineado a la derecha",
    "Image alignment within the content area.": "Alineación de imagen en el área de contenido.",

    # ── Document list ──
    "Optional description of the document.": "Descripción opcional del documento.",
    "Section title for the document list.": "Título de sección para la lista de documentos.",
    "Document list": "Lista de documentos",

    # ── Map block ──
    "Display address (shown in the info popup).": "Dirección mostrada (en el popup informativo).",
    "Latitude,Longitude (e.g. '45.4642,9.1900').": "Latitud,Longitud (ej. '45.4642,9.1900').",
    "Map zoom level (1-20).": "Nivel de zoom del mapa (1-20).",
    "Map height in pixels.": "Altura del mapa en píxeles.",
    "Optional marker label.": "Etiqueta de marcador opcional.",

    # ── Route / waypoints ──
    "Waypoint name (e.g. 'Passo dello Stelvio').": "Nombre del punto de ruta (ej. 'Puerto del Stelvio').",
    "Optional address or location description.": "Dirección opcional o descripción de ubicación.",
    "Latitude,Longitude (e.g. '46.5287,10.4531').": "Latitud,Longitud (ej. '46.5287,10.4531').",
    "Start": "Inicio",
    "Waypoint": "Punto de ruta",
    "Fuel stop": "Parada de combustible",
    "Food / restaurant": "Restaurante",
    "Photo spot": "Punto fotográfico",
    "End": "Fin",
    "Marker icon type on the map.": "Tipo de icono de marcador en el mapa.",
    "Route name.": "Nombre de la ruta.",
    "Brief route description.": "Breve descripción de la ruta.",
    "At least two waypoints (start and end) are required.": "Se requieren al menos dos puntos de ruta (inicio y fin).",
    "Scenic ride": "Paseo panorámico",
    "Touring": "Turístico",
    "Sport / twisties": "Deportivo / curvas",
    "Off-road / adventure": "Todoterreno / aventura",
    "Commute / practical": "Desplazamiento / práctico",
    "Type of route.": "Tipo de ruta.",
    "Approximate distance (e.g. '320 km').": "Distancia aproximada (ej. '320 km').",
    "Elevation gain (e.g. '2500 m').": "Desnivel (ej. '2500 m').",
    "Estimated riding time (e.g. '5-6 hours').": "Tiempo de conducción estimado (ej. '5-6 horas').",
    "Challenging": "Exigente",
    "Route difficulty level.": "Nivel de dificultad de la ruta.",

    # ── Verification ──
    "Enter member card number": "Introduce el número de tarjeta de socio",
    "Verification type": "Tipo de verificación",
    "Select which piece of information to verify against.": "Selecciona qué información verificar.",
    "Verification value": "Valor de verificación",
    "Enter the value to verify": "Introduce el valor a verificar",

    # ── Photo uploads ──
    "Photos": "Fotos",
    "Select up to 20 images (JPG, PNG, or WebP, max 10 MB each).": "Selecciona hasta 20 imágenes (JPG, PNG o WebP, máx. 10 MB cada una).",
    "Title prefix": "Prefijo del título",
    "Optional prefix added to each photo title.": "Prefijo opcional añadido a cada título de foto.",
    "e.g. Summer Rally 2025": "ej. Rally de Verano 2025",
    "Optionally link photos to an event.": "Enlaza opcionalmente las fotos a un evento.",
    "-- No event --": "-- Sin evento --",
    "You can upload a maximum of %(max)d files at a time.": "Puedes subir un máximo de %(max)d archivos a la vez.",
    "File '%(name)s' exceeds the maximum size of 10 MB.": "El archivo '%(name)s' supera el tamaño máximo de 10 MB.",
    "File '%(name)s' is not an allowed format. Only JPG, PNG, and WebP are accepted.": "El archivo '%(name)s' no tiene un formato permitido. Solo se aceptan JPG, PNG y WebP.",

    # ── Home page ──
    "Hero title": "Título hero",
    "Main headline displayed in the hero section.": "Título principal mostrado en la sección hero.",
    "Hero subtitle": "Subtítulo hero",
    "Hero background image": "Imagen de fondo hero",
    "Primary CTA text": "Texto CTA primario",
    "Primary CTA link": "Enlace CTA primario",
    "Primary CTA external URL": "URL externa CTA primaria",
    "Secondary CTA link": "Enlace CTA secundario",
    "Featured event": "Evento destacado",
    "Select an EventDetailPage to highlight on the homepage.": "Selecciona una página de evento para destacar en la portada.",
    "Call-to-action buttons": "Botones de llamada a la acción",
    "Featured content": "Contenido destacado",
    "Home page": "Página de inicio",
    "Home pages": "Páginas de inicio",
    "Displayed below the page title.": "Mostrado debajo del título de la página.",
    "Cover image": "Imagen de portada",

    # ── About page ──
    "About page": "Página sobre nosotros",
    "About pages": "Páginas sobre nosotros",
    "Use team-member blocks here.": "Usa aquí bloques de miembros del equipo.",

    # ── Board page ──
    "Board page": "Página de junta directiva",
    "Board pages": "Páginas de junta directiva",

    # ── News index ──
    "Optional content displayed above the article listing.": "Contenido opcional mostrado sobre la lista de artículos.",
    "News index page": "Página de índice de noticias",
    "News index pages": "Páginas de índice de noticias",
    "Introduction / excerpt": "Introducción / extracto",
    "Short summary shown in listings.": "Breve resumen mostrado en los listados.",
    "Display date": "Fecha de visualización",
    "Publication date shown to readers.": "Fecha de publicación mostrada a los lectores.",
    "Article metadata": "Metadatos del artículo",
    "Categorisation": "Categorización",
    "News page": "Página de noticias",
    "News pages": "Páginas de noticias",

    # ── Events page ──
    "Optional content above the event listing.": "Contenido opcional sobre la lista de eventos.",
    "Events page": "Página de eventos",
    "Events pages": "Páginas de eventos",
    "Short description shown in listings.": "Breve descripción mostrada en los listados.",
    "Start date & time": "Fecha y hora de inicio",
    "End date & time": "Fecha y hora de fin",
    "Venue name": "Nombre del lugar",
    "Coordinates": "Coordenadas",
    "Latitude,Longitude (e.g. '45.4642,9.1900')": "Latitud,Longitud (ej. '45.4642,9.1900')",
    "Registration open": "Inscripción abierta",
    "Registration deadline": "Fecha límite de inscripción",
    "Max attendees": "Asistentes máximos",
    "0 = unlimited.": "0 = ilimitados.",
    "Event participation cost in EUR.  0 = free.": "Coste de participación en EUR. 0 = gratuito.",
    "Early-bird discount (%)": "Descuento anticipado (%)",
    "Early-bird deadline": "Fecha límite anticipada",
    "Percentage discount for active members.": "Descuento porcentual para socios activos.",
    "Allow guest registration": "Permitir inscripción de invitados",
    "Meeting point": "Punto de encuentro",
    "Where participants should gather before the event start.": "Donde los participantes deben reunirse antes del inicio del evento.",
    "Difficulty level": "Nivel de dificultad",
    "Schedule": "Programa",
    "Registration settings": "Configuración de inscripción",
    "Pricing": "Precios",
    "Promote": "Promocionar",
    "Event detail page": "Página de detalle del evento",
    "Event detail pages": "Páginas de detalle de eventos",

    # ── Gallery page ──
    "Root collection": "Colección raíz",
    "Starting collection for gallery display.  Sub-collections become albums.": "Colección inicial para la galería. Las subcolecciones se convierten en álbumes.",
    "Gallery page": "Página de galería",
    "Gallery pages": "Páginas de galería",

    # ── Contact page ──
    "Form title": "Título del formulario",
    "Success message": "Mensaje de éxito",
    "Confirmation shown after form submission.": "Confirmación mostrada tras el envío del formulario.",
    "Enable captcha": "Activar captcha",
    "Honeypot + Time check": "Honeypot + Verificación de tiempo",
    "Cloudflare Turnstile": "Cloudflare Turnstile",
    "hCaptcha": "hCaptcha",
    "Captcha provider": "Proveedor de captcha",
    "Captcha site key": "Clave de sitio captcha",
    "Captcha secret key": "Clave secreta captcha",
    "Anti-spam settings": "Configuración anti-spam",
    "Anti-spam": "Anti-spam",
    "Contact page": "Página de contacto",
    "Contact pages": "Páginas de contacto",

    # ── Privacy page ──
    "Last updated": "Última actualización",
    "Date the policy was last revised.": "Fecha de la última revisión de la política.",
    "Privacy page": "Página de privacidad",
    "Privacy pages": "Páginas de privacidad",

    # ── Transparency page ──
    "Use document-list and accordion blocks for organising documents.": "Usa bloques de lista de documentos y acordeón para organizar documentos.",
    "Transparency page": "Página de transparencia",
    "Transparency pages": "Páginas de transparencia",

    # ── Press page ──
    "Press email": "Correo de prensa",
    "Press phone": "Teléfono de prensa",
    "Press contact person": "Persona de contacto de prensa",
    "Press contact": "Contacto de prensa",
    "Press page": "Página de prensa",
    "Press pages": "Páginas de prensa",

    # ── Partner index ──
    "Partner index page": "Página de índice de socios",
    "Partner index pages": "Páginas de índice de socios",
    "ISO 3166-1 alpha-2 country code.": "Código de país ISO 3166-1 alfa-2.",
    "Facebook URL": "URL de Facebook",
    "Instagram URL": "URL de Instagram",
    "LinkedIn URL": "URL de LinkedIn",
    "YouTube URL": "URL de YouTube",
    "Twitter / X URL": "URL de Twitter / X",
    "Partner owner": "Propietario del socio",
    "User account that manages this partner page.": "Cuenta de usuario que gestiona esta página de socio.",
    "Owner email": "Correo del propietario",
    "Contact email for the partner owner.": "Correo de contacto del propietario del socio.",
    "Show this partner prominently.": "Mostrar este socio de forma destacada.",
    "Display order": "Orden de visualización",
    "Lower numbers appear first.": "Los números menores aparecen primero.",
    "Show on homepage": "Mostrar en la portada",
    "Partnership start": "Inicio de la asociación",
    "Partnership end": "Fin de la asociación",
    "Leave blank for ongoing partnerships.": "Dejar en blanco para asociaciones vigentes.",
    "Social media": "Redes sociales",
    "Ownership": "Propiedad",
    "Display settings": "Configuración de visualización",
    "Social": "Social",
    "Display": "Visualización",
    "Partner page": "Página de socio",
    "Partner pages": "Páginas de socios",

    # ── Theme names ──
    "Velocity": "Velocity",
    "Heritage": "Heritage",
    "Terra / Eco": "Terra / Eco",
    "Zen": "Zen",
    "Clubs": "Clubs",
    "Tricolore": "Tricolore",

    # ── Site settings ──
    "Honeypot (no external service)": "Honeypot (sin servicio externo)",
    "OpenStreetMap": "OpenStreetMap",
    "Google Maps": "Google Maps",
    "Mapbox": "Mapbox",
    "Human-readable name shown in the header / meta tags.": "Nombre legible mostrado en el encabezado / meta tags.",
    "Site description": "Descripción del sitio",
    "Default meta description for SEO.": "Meta descripción predeterminada para SEO.",
    "Colour scheme": "Esquema de colores",
    "Logo (dark variant)": "Logo (variante oscura)",
    "Optional dark-background version of the logo.": "Versión opcional del logo con fondo oscuro.",
    "Opening hours": "Horario de apertura",
    "TikTok URL": "URL de TikTok",
    "Navbar": "Barra de navegación",
    "PWA name": "Nombre PWA",
    "PWA short name": "Nombre corto PWA",
    "PWA description": "Descripción PWA",
    "PWA icon 192x192": "Icono PWA 192x192",
    "PWA icon 512x512": "Icono PWA 512x512",
    "PWA theme colour": "Color de tema PWA",
    "PWA background colour": "Color de fondo PWA",
    "CAPTCHA provider": "Proveedor CAPTCHA",
    "CAPTCHA site key": "Clave de sitio CAPTCHA",
    "CAPTCHA secret key": "Clave secreta CAPTCHA",
    "Map routing service": "Servicio de enrutamiento de mapas",
    "Map API key": "Clave API de mapas",
    "Required for Google Maps / Mapbox.": "Requerido para Google Maps / Mapbox.",
    "Default map centre": "Centro de mapa predeterminado",
    "Default map zoom": "Zoom de mapa predeterminado",
    "General": "General",
    "Branding": "Marca",
    "Progressive Web App": "Progressive Web App",
    "PWA": "PWA",
    "Anti-spam / CAPTCHA": "Anti-spam / CAPTCHA",
    "Forms": "Formularios",
    "Map & routing": "Mapa y rutas",
    "site settings": "configuración del sitio",

    # ── Payment settings ──
    "Test": "Prueba",
    "Payment mode": "Modo de pago",
    "Only credentials for the selected mode are used at runtime.": "Solo las credenciales del modo seleccionado se usan en ejecución.",
    "Stripe enabled (test)": "Stripe activado (prueba)",
    "Stripe public key (test)": "Clave pública Stripe (prueba)",
    "Stripe secret key (test)": "Clave secreta Stripe (prueba)",
    "Stripe webhook secret (test)": "Secreto webhook Stripe (prueba)",
    "PayPal enabled (test)": "PayPal activado (prueba)",
    "PayPal client ID (test)": "ID de cliente PayPal (prueba)",
    "PayPal secret (test)": "Secreto PayPal (prueba)",
    "Stripe enabled (live)": "Stripe activado (producción)",
    "Stripe public key (live)": "Clave pública Stripe (producción)",
    "Stripe secret key (live)": "Clave secreta Stripe (producción)",
    "Stripe webhook secret (live)": "Secreto webhook Stripe (producción)",
    "PayPal enabled (live)": "PayPal activado (producción)",
    "PayPal client ID (live)": "ID de cliente PayPal (producción)",
    "PayPal secret (live)": "Secreto PayPal (producción)",
    "Bank transfer enabled": "Transferencia bancaria activada",
    "Account holder": "Titular de la cuenta",
    "IBAN": "IBAN",
    "BIC / SWIFT": "BIC / SWIFT",
    "Bank name": "Nombre del banco",
    "Bank transfer instructions": "Instrucciones de transferencia bancaria",
    "Additional instructions shown to the user (e.g. 'Include the reference in the description').": "Instrucciones adicionales mostradas al usuario (ej. 'Incluye la referencia en el concepto').",
    "Bank transfer expiry (days)": "Vencimiento de transferencia bancaria (días)",
    "Days allowed for the user to complete the bank transfer.": "Días permitidos para completar la transferencia bancaria.",
    "Active mode": "Modo activo",
    "Mode": "Modo",
    "Stripe (test)": "Stripe (prueba)",
    "PayPal (test)": "PayPal (prueba)",
    "Test configuration": "Configuración de prueba",
    "Stripe (live)": "Stripe (producción)",
    "PayPal (live)": "PayPal (producción)",
    "Live configuration": "Configuración de producción",
    "Bank transfer": "Transferencia bancaria",
    "payment settings": "configuración de pago",

    # ── Colour scheme snippet ──
    "Main brand colour (hex).": "Color principal de marca (hex).",
    "Secondary/accent brand colour (hex).": "Color secundario/acento de marca (hex).",
    "Accent colour": "Color de acento",
    "Accent highlight colour (hex).": "Color de acento destacado (hex).",
    "Surface colour": "Color de superficie",
    "Card/panel background colour (hex).": "Color de fondo de tarjeta/panel (hex).",
    "Surface alt colour": "Color de superficie alternativo",
    "Alternate surface colour (hex).": "Color de superficie alternativo (hex).",
    "Text primary": "Texto primario",
    "Main body text colour (hex).": "Color de texto principal (hex).",
    "Text muted": "Texto atenuado",
    "Secondary/lighter text colour (hex).": "Color de texto secundario/claro (hex).",
    "Enable if this is a dark colour scheme.": "Activar si es un esquema de colores oscuro.",
    "Brand colours": "Colores de marca",
    "Surface colours": "Colores de superficie",
    "Text colours": "Colores de texto",
    "colour scheme": "esquema de colores",
    "colour schemes": "esquemas de colores",

    # ── Navbar snippet ──
    "Show search": "Mostrar búsqueda",
    "navbar": "barra de navegación",
    "navbars": "barras de navegación",
    "Parent item": "Elemento padre",
    "Leave empty for top-level items. Select a parent for dropdown sub-items.": "Dejar en blanco para elementos de nivel superior. Seleccionar un padre para submenús.",
    "Link page": "Página enlazada",
    "Used only when no page is selected.": "Se usa solo cuando no se selecciona una página.",
    "Open in new tab": "Abrir en nueva pestaña",
    "Is CTA": "Es CTA",
    "Render as a highlighted call-to-action button.": "Mostrar como botón de llamada a la acción destacado.",

    # ── Footer snippet ──
    "Twitter / X": "Twitter / X",
    "TikTok": "TikTok",
    "Short 'about' text displayed in the footer.": "Breve texto 'sobre nosotros' mostrado en el pie de página.",
    "Copyright text": "Texto de copyright",
    "Contact details": "Datos de contacto",
    "Social links": "Enlaces sociales",
    "footer": "pie de página",
    "footers": "pies de página",

    # ── FAQ snippet ──
    "Platform": "Plataforma",
    "Question": "Pregunta",
    "Answer": "Respuesta",
    "Optional grouping label for the FAQ.": "Etiqueta de agrupación opcional para las FAQ.",
    "FAQ": "FAQ",
    "FAQs": "FAQs",

    # ── Testimonial snippet ──
    "Author name": "Nombre del autor",
    "Author role": "Rol del autor",
    "Author photo": "Foto del autor",
    "Show this testimonial more prominently.": "Mostrar este testimonio de forma más destacada.",
    "testimonial": "testimonio",
    "testimonials": "testimonios",

    # ── Category snippets ──
    "Colour": "Color",
    "Badge/label colour (hex).": "Color de insignia/etiqueta (hex).",
    "news category": "categoría de noticias",
    "news categories": "categorías de noticias",
    "Motorcycle": "Moto",
    "Rally": "Rally",
    "Meeting": "Encuentro",
    "Charity": "Beneficencia",
    "Race": "Carrera",
    "event category": "categoría de evento",
    "event categories": "categorías de eventos",
    "photo tag": "etiqueta de foto",
    "photo tags": "etiquetas de fotos",
    "partner category": "categoría de socio",
    "partner categories": "categorías de socios",

    # ── Press release snippet ──
    "Attachment": "Adjunto",
    "PDF or document attachment.": "Adjunto PDF o documento.",
    "Archived": "Archivado",
    "press release": "comunicado de prensa",
    "press releases": "comunicados de prensa",

    # ── Brand asset snippet ──
    "Font": "Fuente",
    "Template": "Plantilla",
    "Preview image": "Imagen de vista previa",
    "brand asset": "recurso de marca",
    "brand assets": "recursos de marca",

    # ── Aid skill snippet ──
    "Mechanics": "Mecánica",
    "Logistics": "Logística",
    "Emergency": "Emergencia",
    "aid skill": "habilidad de ayuda",
    "aid skills": "habilidades de ayuda",

    # ── Product snippet ──
    "Inactive products are hidden from the storefront.": "Los productos inactivos están ocultos en la tienda.",
    "Grants voting rights": "Otorga derecho a voto",
    "Grants gallery upload": "Otorga subida a galería",
    "Grants event access": "Otorga acceso a eventos",
    "Grants discount": "Otorga descuento",
    "Percentage discount on events when grants_discount is on.": "Descuento porcentual en eventos cuando grants_discount está activado.",
    "Product info": "Info del producto",
    "Member privileges": "Privilegios de socio",
    "product": "producto",

    # ── Photo upload model ──
    "Uploaded by": "Subido por",
    "Optionally link this photo to an event.": "Enlazar opcionalmente esta foto a un evento.",
    "Approved at": "Aprobado el",
    "Rejection reason": "Motivo del rechazo",
    "Uploaded at": "Subido el",
    "photo upload": "subida de foto",
    "photo uploads": "subidas de fotos",
    "approved": "aprobado",
    "pending": "pendiente",

    # ── Verification log ──
    "Not found": "No encontrado",
    "Wrong data": "Datos incorrectos",
    "Expired membership": "Membresía vencida",
    "Partner user": "Usuario socio",
    "The partner owner who performed this verification.": "El propietario del socio que realizó esta verificación.",
    "Which secondary factor was used for verification.": "Qué factor secundario se usó para la verificación.",
    "Result": "Resultado",
    "IP address": "Dirección IP",
    "verification log": "registro de verificación",
    "verification logs": "registros de verificación",

    # ── Verification error messages ──
    "Access denied. Only partner owners and staff can verify members.": "Acceso denegado. Solo los propietarios de socios y el personal pueden verificar socios.",
    "Rate limit exceeded. Maximum 20 verification attempts per hour.": "Límite de solicitudes superado. Máximo 20 intentos de verificación por hora.",
    "Account temporarily locked. Too many failed verification attempts. Please try again in 15 minutes.": "Cuenta temporalmente bloqueada. Demasiados intentos de verificación fallidos. Inténtalo de nuevo en 15 minutos.",
    "No member found with this card number.": "No se encontró ningún socio con este número de tarjeta.",
    "This member's membership has expired.": "La membresía de este socio ha vencido.",
    "Member verified successfully.": "Socio verificado con éxito.",
    "N/A": "N/D",
    "Verification failed. The provided information does not match our records.": "Verificación fallida. La información proporcionada no coincide con nuestros registros.",
    "Access denied. Your membership does not include gallery upload privileges.": "Acceso denegado. Tu membresía no incluye privilegios de subida a galería.",
    "Rejected by moderator.": "Rechazado por el moderador.",

    # ── Membership card template ──
    "Membership Card": "Tarjeta de Socio",
    "Card No.": "N.º de Tarjeta",
    "Expires": "Vence",
    "Barcode": "Código de barras",
    "Download PDF": "Descargar PDF",
    "No membership card has been issued yet. Please contact the club administration.": "Aún no se ha emitido tarjeta de socio. Contacta con la administración del club.",

    # ── Member directory template ──
    "Member Directory": "Directorio de Socios",
    "Pagination": "Paginación",
    "No members are currently visible in the directory.": "No hay socios visibles actualmente en el directorio.",

    # ── Auth templates ──
    "Welcome back": "Bienvenido de nuevo",
    "Log in to access your profile, events, and club features.": "Inicia sesión para acceder a tu perfil, eventos y funciones del club.",
    "Forgot your password?": "¿Olvidaste tu contraseña?",
    "Don't have an account?": "¿No tienes cuenta?",
    "Are you sure you want to log out?": "¿Estás seguro de que quieres cerrar sesión?",
    "Go back to home": "Volver a la página principal",
    "Become a member": "Hazte socio",
    "Choose the membership plan that best fits your needs. Combine multiple products to customize your ex": "Elige el plan de membresía que mejor se adapte a tus necesidades. Combina varios productos para personalizar tu experiencia",
    "Your plan": "Tu plan",
    "year": "año",
    "Event registration": "Inscripción a eventos",
    "Voting rights": "Derecho a voto",
    "Gallery upload": "Subida a galería",
    "%(percent)s%% discount on events": "%(percent)s%% de descuento en eventos",
    "Contact the club": "Contactar con el club",
    "No membership plans available at this time.": "No hay planes de membresía disponibles en este momento.",
    "Reset your password": "Restablece tu contraseña",
    "Enter your email address and we'll send you a link to reset your password.": "Introduce tu dirección de correo y te enviaremos un enlace para restablecer tu contraseña.",
    "Send reset link": "Enviar enlace de restablecimiento",
    "Back to login": "Volver al inicio de sesión",
    "Active Member": "Socio Activo",
    "Back to Directory": "Volver al Directorio",
    "Create your account": "Crea tu cuenta",
    "Join the club and access events, member directory, and more.": "Únete al club y accede a eventos, directorio de socios y más.",
    "Already have an account?": "¿Ya tienes cuenta?",

    # ── Registration confirmation ──
    "Registration Confirmed": "Inscripción Confirmada",

    # ── Payment pages ──
    "Amount": "Importe",
    "Bank Transfer Payment Required": "Pago por Transferencia Bancaria Requerido",
    "This is an automatic confirmation email. Please do not reply.": "Este es un correo de confirmación automática. Por favor, no respondas.",

    # ── Favorite events ──
    "My Favorite Events": "Mis Eventos Favoritos",
    "Upcoming": "Próximos",
    "Archive": "Archivo",
    "My Registrations": "Mis Inscripciones",
    "Events map": "Mapa de eventos",
    "Map view of your favorite events": "Vista de mapa de tus eventos favoritos",
    "Remove from favorites": "Eliminar de favoritos",
    "Download calendar file": "Descargar archivo de calendario",
    "ICS": "ICS",
    "You have not added any events to your favorites yet.": "Aún no has añadido eventos a tus favoritos.",
    "Events Archive": "Archivo de Eventos",
    "No past events in your favorites.": "No hay eventos pasados en tus favoritos.",

    # ── Payment flow ──
    "Payment": "Pago",
    "Bank Transfer Instructions": "Instrucciones de Transferencia Bancaria",
    "Transfer Details": "Detalles de Transferencia",
    "Bank": "Banco",
    "Payment Reference": "Referencia de Pago",
    "Copy": "Copiar",
    "Deadline": "Fecha límite",
    "Back to my registrations": "Volver a mis inscripciones",
    "Your payment was not completed. You can try again using the link below.": "Tu pago no se ha completado. Puedes intentarlo de nuevo usando el enlace de abajo.",
    "Try again": "Intentar de nuevo",
    "Choose Payment Method": "Elige el Método de Pago",
    "Credit / Debit Card": "Tarjeta de Crédito / Débito",
    "Pay securely with Stripe": "Paga de forma segura con Stripe",
    "Pay with your PayPal account": "Paga con tu cuenta PayPal",
    "Pay via SEPA bank transfer": "Paga por transferencia bancaria SEPA",
    "Payment Confirmed": "Pago Confirmado",
    "Register for Event": "Inscribirse al Evento",
    "Member discount": "Descuento de socio",
    "Please correct the highlighted errors below.": "Por favor, corrige los errores destacados a continuación.",
    "Your Information": "Tu Información",
    "Registration Details": "Detalles de Inscripción",
    "Registration Summary": "Resumen de Inscripción",

    # ── Federation / Partner events ──
    "Partner Events": "Eventos de Socios",
    "Breadcrumb": "Ruta de navegación",
    "Club": "Club",
    "View on Google Maps": "Ver en Google Maps",
    "View on partner site": "Ver en el sitio del socio",
    "Events from our federated partner clubs.": "Eventos de nuestros clubes socios federados.",
    "Partner Club": "Club Socio",
    "All clubs": "Todos los clubes",
    "Search events...": "Buscar eventos...",
    "No partner events found.": "No se encontraron eventos de socios.",
    "Clear filters": "Limpiar filtros",
    "Club Discussion": "Discusión del Club",
    "Comments are visible only to our club members. They are not shared with the partner club.": "Los comentarios son visibles solo para nuestros socios. No se comparten con el club socio.",
    "Delete this comment?": "¿Eliminar este comentario?",
    "No comments yet. Be the first to start a discussion!": "Aún no hay comentarios. ¡Sé el primero en iniciar una discusión!",
    "Add a comment": "Añadir un comentario",
    "Share your thoughts with fellow club members...": "Comparte tus opiniones con otros socios del club...",
    "Post Comment": "Publicar Comentario",
    "Only active members can post comments.": "Solo los socios activos pueden publicar comentarios.",
    "Are you interested?": "¿Estás interesado?",
    "going": "asistiré",
    "interested": "interesado",
    "maybe": "quizás",
    "Only active members can express interest in partner events.": "Solo los socios activos pueden expresar interés en eventos de socios.",

    # ── Navbar template ──
    "Main navigation": "Navegación principal",
    "Toggle navigation": "Abrir/cerrar navegación",
    "Search...": "Buscar...",
    "Search the site": "Buscar en el sitio",
    "Submit search": "Enviar búsqueda",
    "Membership card": "Tarjeta de socio",
    "My events": "Mis eventos",
    "Member directory": "Directorio de socios",

    # ── Mutual Aid access request ──
    "Request Access": "Solicitar Acceso",
    "Request Access to Mutual Aid": "Solicitar Acceso a Ayuda Mutua",
    "Submit Request": "Enviar Solicitud",
    "radius": "radio",
    "Send Request": "Enviar Solicitud",
    "Availability": "Disponibilidad",
    "WhatsApp": "WhatsApp",
    "Send message": "Enviar mensaje",
    "Send Aid Request": "Enviar Solicitud de Ayuda",
    "Unlock Limit Reached": "Límite de Desbloqueos Alcanzado",
    "Contact Unlock Limit Reached": "Límite de Desbloqueo de Contactos Alcanzado",
    "Please wait before unlocking more contacts, or use the contacts you have already unlocked.": "Espera antes de desbloquear más contactos, o usa los contactos que ya has desbloqueado.",
    "Back to Mutual Aid": "Volver a Ayuda Mutua",
    "Emergency Contacts": "Contactos de Emergencia",
    "Check back later or contact the club directly.": "Vuelve más tarde o contacta directamente con el club.",

    # ── Notification digest template ──
    "Notification digest": "Resumen de notificaciones",
    "View details": "Ver detalles",
    "Notification history": "Historial de notificaciones",
    "ago": "hace",
    "No notifications yet.": "Aún no hay notificaciones.",
    "Unsubscribe": "Cancelar suscripción",
    "Confirm unsubscribe": "Confirmar cancelación",
    "You can re-enable notifications at any time from your account settings.": "Puedes reactivar las notificaciones en cualquier momento desde la configuración de tu cuenta.",
    "Invalid link": "Enlace no válido",
    "Unsubscribed": "Suscripción cancelada",
    "You have been unsubscribed from these notifications. You will no longer receive them.": "Se ha cancelado tu suscripción a estas notificaciones. Ya no las recibirás.",
    "If you change your mind, you can re-enable notifications from your": "Si cambias de opinión, puedes reactivar las notificaciones desde tu",
    "account settings": "configuración de cuenta",

    # ── Events filters ──
    "Event period": "Período del evento",
    "Past": "Pasado",
    "Event filters": "Filtros de evento",
    "Registration Open": "Inscripción Abierta",

    # ── Remaining strings (pass 3) ──
    "Contact information": "Información de contacto",
    "\\n                Page %(current)s of %(total)s\\n            ": "\\n                Página %(current)s de %(total)s\\n            ",
    "Choose the membership plan that best fits your needs. Combine multiple products to customize your experience.": "Elige el plan de membresía que mejor se adapte a tus necesidades. Combina varios productos para personalizar tu experiencia.",
    "Your registration for <strong>%(event_title)s</strong> has been confirmed.": "Tu inscripción para <strong>%(event_title)s</strong> ha sido confirmada.",
    "Please complete the bank transfer with reference <strong>%(ref)s</strong> before %(expires)s.": "Por favor, completa la transferencia bancaria con referencia <strong>%(ref)s</strong> antes del %(expires)s.",
    "Please include the payment reference in the transfer description. Your registration will be confirmed once the payment is verified by the organiser.": "Por favor, incluye la referencia de pago en la descripción de la transferencia. Tu inscripción se confirmará una vez verificado el pago por el organizador.",
    "As a member of a federated partner club, you can request access to our mutual aid helpers directory.": "Como miembro de un club asociado federado, puedes solicitar acceso a nuestro directorio de ayudantes de asistencia mutua.",
    "Your request will be reviewed by our administrators. Once approved, you will be able to view and contact available helpers.": "Tu solicitud será revisada por nuestros administradores. Una vez aprobada, podrás ver y contactar a los ayudantes disponibles.",
    "Sending request to:": "Enviando solicitud a:",
    "\\n                You have reached the maximum of %(limit)s contact unlocks\\n                per %(days)s-day period.\\n            ": "\\n                Has alcanzado el máximo de %(limit)s desbloqueos de contacto\\n                por período de %(days)s días.\\n            ",
    "\\n    Hi %(name)s, here is your notification digest\\n    ": "\\n    Hola %(name)s, aquí tienes tu resumen de notificaciones\\n    ",
    "\\n    You have %(count)s new notification(s).\\n    ": "\\n    Tienes %(count)s nueva(s) notificación(es).\\n    ",
    "\\n                Page %(current)s of %(total)s\\n                ": "\\n                Página %(current)s de %(total)s\\n                ",
    "\\n            You are about to unsubscribe <strong>%(email)s</strong> from\\n            <strong>%(type)s</strong> notifications.\\n            ": "\\n            Estás a punto de cancelar la suscripción de <strong>%(email)s</strong> de\\n            las notificaciones de <strong>%(type)s</strong>.\\n            ",
    "This unsubscribe link is invalid or has expired. Please check the link and try again, or manage your preferences from your account settings.": "Este enlace de cancelación es inválido o ha expirado. Revisa el enlace e inténtalo de nuevo, o gestiona tus preferencias desde la configuración de tu cuenta.",
    "Thank you for your message. We will get back to you shortly.": "Gracias por tu mensaje. Nos pondremos en contacto contigo pronto.",
    "Please correct the errors below:": "Por favor, corrige los errores a continuación:",
    "Subject": "Asunto",
    "Send Message": "Enviar Mensaje",
    "Club location map": "Mapa de ubicación del club",
    "View larger map": "Ver mapa más grande",
    "opens in a new window": "se abre en una nueva ventana",
    "Where to Find Us": "Cómo Encontrarnos",
    "Direct Contacts": "Contactos Directos",
    "Opening Hours": "Horario de Apertura",
    "No events found.": "No se encontraron eventos.",
}

if __name__ == "__main__":
    run_translation("es", "Español", TRANSLATIONS)
