#!/usr/bin/env python3
"""
Batch-translate the French .po file for ClubCMS.
Source: English msgid → French msgstr
Cross-checked against Italian translations for consistency.
"""
from translate_engine import run_translation

# ──────────────────────────────────────────────────────────
#  TRANSLATION DICTIONARY  (English → French)
# ──────────────────────────────────────────────────────────
TRANSLATIONS = {
    # ── AppConfig verbose_name ──
    "Core": "Noyau",
    "Events": "Événements",
    "Federation": "Fédération",
    "Members": "Membres",
    "Mutual Aid": "Entraide",
    "Notifications": "Notifications",
    "Website": "Site Web",

    # ── Model Meta verbose_name / verbose_name_plural ──
    "Federated Club": "Club Fédéré",
    "Federated Clubs": "Clubs Fédérés",
    "External Event": "Événement Externe",
    "External Events": "Événements Externes",
    "External Event Interest": "Intérêt pour Événement Externe",
    "External Event Interests": "Intérêts pour Événements Externes",
    "External Event Comment": "Commentaire d'Événement Externe",
    "External Event Comments": "Commentaires d'Événements Externes",
    "Club User": "Utilisateur du Club",
    "Club Users": "Utilisateurs du Club",
    "Event Registration": "Inscription à l'Événement",
    "Event Registrations": "Inscriptions aux Événements",
    "Event Favorite": "Événement Favori",
    "Event Favorites": "Événements Favoris",
    "Event page": "Page d'événement",

    # ── Events / Registration fields ──
    "Confirmed": "Confirmé",
    "Waitlist": "Liste d'attente",
    "Pending": "En attente",
    "Paid": "Payé",
    "Refunded": "Remboursé",
    "Stripe": "Stripe",
    "PayPal": "PayPal",
    "Bank Transfer": "Virement Bancaire",
    "User": "Utilisateur",
    "Status": "Statut",
    "Number of guests": "Nombre d'invités",
    "Payment status": "Statut du paiement",
    "Payment provider": "Fournisseur de paiement",
    "Payment ID": "ID de paiement",
    "External payment reference from the provider.": "Référence de paiement externe du fournisseur.",
    "Payment session ID": "ID de session de paiement",
    "Checkout Session ID (Stripe) or Order ID (PayPal).": "ID de session de paiement (Stripe) ou ID de commande (PayPal).",
    "Payment amount": "Montant du paiement",
    "Unique reference for bank transfers (e.g. EVT-00123-A7B3).": "Référence unique pour les virements bancaires (ex. EVT-00123-A7B3).",
    "Payment expires at": "Le paiement expire le",
    "Deadline for bank transfer payments.": "Date limite pour les paiements par virement bancaire.",
    "Guest": "Invité",
    "Days before event": "Jours avant l'événement",
    "Hours before event": "Heures avant l'événement",
    "Minutes before event": "Minutes avant l'événement",
    "Discount percent": "Pourcentage de réduction",
    "Label": "Libellé",
    "Display label for this tier, e.g. 'Early Bird'.": "Libellé pour ce palier, ex. 'Tarif précoce'.",
    "The time offset must be greater than zero.": "Le décalage horaire doit être supérieur à zéro.",
    "Added at": "Ajouté le",
    "Registered": "Inscrit",
    "Registered at": "Inscrit le",
    "Cancelled": "Annulé",
    "Event": "Événement",
    "Payment reference": "Référence de paiement",
    "Is registration deadline": "Est date limite d'inscription",

    # ── Events notification messages ──
    "Payment expired: {event}": "Paiement expiré : {event}",
    "Your bank transfer for {event} was not received in time. Your registration has been cancelled.":
        "Votre virement bancaire pour {event} n'a pas été reçu à temps. Votre inscription a été annulée.",
    "Spot available: {event}": "Place disponible : {event}",
    "A spot has opened up! You have been promoted from the waitlist for {event}.":
        "Une place s'est libérée ! Vous avez été promu de la liste d'attente pour {event}.",
    "Your membership does not include event registration. Please upgrade your membership.":
        "Votre adhésion n'inclut pas l'inscription aux événements. Veuillez mettre à jour votre adhésion.",
    "Please wait before toggling again.": "Veuillez patienter avant de changer à nouveau.",
    "Payment instructions: {event}": "Instructions de paiement : {event}",
    "Please complete the bank transfer of €{amount} with reference {ref} by {expires}.":
        "Veuillez effectuer le virement bancaire de {amount} € avec la référence {ref} avant le {expires}.",
    "Payment service temporarily unavailable. Please try again.":
        "Service de paiement temporairement indisponible. Veuillez réessayer.",

    # ── Federation model help_text ──
    "Display name of the partner club": "Nom d'affichage du club partenaire",
    "URL-safe identifier": "Identifiant compatible URL",
    "Partner site base URL": "URL de base du site partenaire",
    "Optional logo URL": "URL du logo (facultatif)",
    "Their public API key (given to us)": "Leur clé API publique (fournie à nous)",
    "Our key we gave them (auto-generated)": "Notre clé fournie à eux (générée automatiquement)",
    "Share our events with this partner": "Partager nos événements avec ce partenaire",
    "Auto-approve imported events": "Approuver automatiquement les événements importés",
    "Sanitized HTML": "HTML assaini",

    # ── Member form fields ──
    "Select member": "Sélectionner un membre",
    "Number of extra people coming with you (not counting yourself or your passenger). Example: 2":
        "Nombre de personnes supplémentaires vous accompagnant (sans vous compter ni votre passager). Exemple : 2",
    "List each guest on a separate line. Example:\\nMario Rossi\\nLucia Bianchi":
        "Listez chaque invité sur une ligne séparée. Exemple :\\nJean Dupont\\nMarie Martin",
    "Allergies, dietary needs, special requests, or anything the organizers should know.":
        "Allergies, besoins alimentaires, demandes spéciales ou toute information utile aux organisateurs.",
    "Check this if someone will ride with you as a passenger on your motorcycle.":
        "Cochez si quelqu'un voyagera avec vous en tant que passager sur votre moto.",
    "If your passenger is already a club member, enable this to select them from the list.":
        "Si votre passager est déjà membre du club, activez cette option pour le sélectionner dans la liste.",
    "Example: Marco": "Exemple : Jean",
    "Example: Verdi": "Exemple : Dupont",
    "Example: marco.verdi@email.com": "Exemple : jean.dupont@email.com",
    "Italian tax identification code, 16 characters. Example: VRDMRC85M01H501Z":
        "Code fiscal italien, 16 caractères. Exemple : VRDMRC85M01H501Z",
    "Example: 1985-08-01": "Exemple : 1985-08-01",
    "Name and phone number to call in case of emergency. Example: Anna Verdi +39 340 7654321":
        "Nom et numéro de téléphone à appeler en cas d'urgence. Exemple : Anne Dupont +33 6 12 34 56 78",
    "Your legal first name. Example: Maria": "Votre prénom légal. Exemple : Marie",
    "Your family name. Example: Rossi": "Votre nom de famille. Exemple : Dupont",
    "Guest names": "Noms des invités",
    "Passenger first name": "Prénom du passager",
    "Emergency contact": "Contact d'urgence",
    "Start typing a name to search registered members.": "Commencez à taper un nom pour rechercher des membres inscrits.",
    "Include country prefix. Example: +39 333 1234567": "Incluez l'indicatif international. Exemple : +33 6 12 34 56 78",
    "We will send your registration confirmation here.": "Nous enverrons votre confirmation d'inscription ici.",

    # ── Admin panels (members) ──
    "Personal": "Personnel",
    "Identity": "Identité",
    "Address": "Adresse",
    "Membership": "Adhésion",
    "Privacy": "Confidentialité",

    # ── Member model fields ──
    "Username": "Nom d'utilisateur",
    "First name": "Prénom",
    "Last name": "Nom",
    "Email": "E-mail",
    "Display name": "Nom d'affichage",
    "Phone": "Téléphone",
    "Mobile": "Mobile",
    "Birth date": "Date de naissance",
    "Birth place": "Lieu de naissance",
    "Photo": "Photo",
    "Bio": "Biographie",
    "Fiscal code": "Code fiscal",
    "Document type": "Type de document",
    "Document number": "Numéro de document",
    "Document expiry": "Expiration du document",
    "City": "Ville",
    "Province": "Province",
    "Postal code": "Code postal",
    "Country": "Pays",
    "Card number": "Numéro de carte",
    "Membership date": "Date d'adhésion",
    "Membership expiry": "Expiration de l'adhésion",
    "Is active": "Est actif",
    "Products": "Produits",
    "Show in directory": "Afficher dans l'annuaire",
    "Public profile": "Profil public",
    "Show real name to members": "Afficher le vrai nom aux membres",
    "Newsletter": "Newsletter",
    "Email notifications": "Notifications par e-mail",
    "Push notifications": "Notifications push",
    "News updates": "Actualités",
    "Event updates": "Mises à jour des événements",
    "Event reminders": "Rappels d'événements",
    "Membership alerts": "Alertes d'adhésion",
    "Partner updates": "Mises à jour des partenaires",
    "Aid requests": "Demandes d'aide",
    "Partner events": "Événements partenaires",
    "Partner event comments": "Commentaires sur les événements partenaires",
    "Digest frequency": "Fréquence du résumé",
    "Aid available": "Aide disponible",
    "Aid radius km": "Rayon d'aide (km)",
    "Aid location city": "Ville de localisation d'aide",
    "Aid coordinates": "Coordonnées d'aide",
    "Aid notes": "Notes d'aide",

    # ── Antispam ──
    "Spam detected. Access denied.": "Spam détecté. Accès refusé.",
    "This submission looks like spam.": "Cette soumission ressemble à du spam.",
    "Too many requests. Please try again later.": "Trop de requêtes. Veuillez réessayer plus tard.",
    "Are you human?": "Êtes-vous humain ?",
    "Verify": "Vérifier",
    "I am human": "Je suis humain",
    "Verification failed. Please try again.": "Vérification échouée. Veuillez réessayer.",
    "Remember me": "Se souvenir de moi",

    # ── Website / Page models ──
    "Home Page": "Page d'Accueil",
    "Content Page": "Page de Contenu",
    "News Page": "Page d'Actualités",
    "News Index Page": "Index des Actualités",
    "Gallery Page": "Page Galerie",
    "Gallery Index Page": "Index de la Galerie",
    "Events Index Page": "Index des Événements",
    "Contact Page": "Page de Contact",
    "Title": "Titre",
    "Subtitle": "Sous-titre",
    "Body": "Corps",
    "Image": "Image",
    "Caption": "Légende",
    "Author": "Auteur",
    "Date": "Date",
    "Published": "Publié",
    "Draft": "Brouillon",
    "Summary": "Résumé",
    "Tags": "Étiquettes",
    "Category": "Catégorie",
    "Categories": "Catégories",
    "Slug": "Slug",
    "SEO Title": "Titre SEO",
    "Search Description": "Description de recherche",
    "Description": "Description",
    "Content": "Contenu",
    "Location": "Lieu",
    "Start date": "Date de début",
    "End date": "Date de fin",
    "Start time": "Heure de début",
    "End time": "Heure de fin",
    "All day": "Toute la journée",
    "Registration required": "Inscription obligatoire",
    "Max participants": "Nombre maximum de participants",
    "Price": "Prix",
    "Free": "Gratuit",
    "Featured": "En vedette",
    "Promoted": "Promu",
    "Featured image": "Image à la une",

    # ── StreamField blocks ──
    "Heading": "Titre",
    "Paragraph": "Paragraphe",
    "Quote": "Citation",
    "Rich Text": "Texte Enrichi",
    "Rich text": "Texte enrichi",
    "Link": "Lien",
    "URL": "URL",
    "Button": "Bouton",
    "Button text": "Texte du bouton",
    "Button link": "Lien du bouton",
    "Call to Action": "Appel à l'action",
    "Background color": "Couleur de fond",
    "Background image": "Image de fond",
    "Text color": "Couleur du texte",
    "Alignment": "Alignement",
    "Left": "Gauche",
    "Center": "Centre",
    "Right": "Droite",
    "Full width": "Pleine largeur",
    "Card": "Carte",
    "Cards": "Cartes",
    "Column": "Colonne",
    "Columns": "Colonnes",
    "Section": "Section",
    "Hero": "Hero",
    "Hero section": "Section Hero",
    "Embed": "Intégration",
    "Embed URL": "URL d'intégration",
    "Video": "Vidéo",
    "Document": "Document",
    "Documents": "Documents",
    "File": "Fichier",
    "Download": "Télécharger",
    "Gallery": "Galerie",
    "Slider": "Diaporama",
    "Testimonial": "Témoignage",
    "Testimonials": "Témoignages",
    "Icon": "Icône",
    "Feature": "Fonctionnalité",
    "Features": "Fonctionnalités",
    "Table": "Tableau",
    "Map": "Carte",
    "Code": "Code",
    "Accordion": "Accordéon",
    "Tab": "Onglet",
    "Tabs": "Onglets",
    "Spacer": "Espacement",
    "Divider": "Séparateur",
    "HTML": "HTML",
    "Raw HTML": "HTML Brut",

    # ── Wagtail / Settings ──
    "Site Settings": "Paramètres du Site",
    "Site settings": "Paramètres du site",
    "Site Name": "Nom du Site",
    "Site name": "Nom du site",
    "Tagline": "Slogan",
    "Logo": "Logo",
    "Favicon": "Favicon",
    "Social Media": "Réseaux Sociaux",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "Twitter": "Twitter",
    "YouTube": "YouTube",
    "LinkedIn": "LinkedIn",
    "Footer": "Pied de page",
    "Footer text": "Texte du pied de page",
    "Copyright": "Droits d'auteur",
    "Analytics": "Analytiques",
    "Google Analytics ID": "ID Google Analytics",
    "Theme": "Thème",
    "Color scheme": "Palette de couleurs",
    "Primary color": "Couleur primaire",
    "Secondary color": "Couleur secondaire",
    "Accent color": "Couleur d'accent",
    "Dark mode": "Mode sombre",
    "Light mode": "Mode clair",
    "Auto": "Automatique",

    # ── Notifications ──
    "Notification": "Notification",
    "Notification Type": "Type de Notification",
    "Notification type": "Type de notification",
    "Message": "Message",
    "Read": "Lu",
    "Unread": "Non lu",
    "Sent": "Envoyé",
    "Mark as read": "Marquer comme lu",
    "Mark all as read": "Tout marquer comme lu",
    "Delete": "Supprimer",
    "No notifications": "Aucune notification",
    "Notification Settings": "Paramètres de Notification",
    "Notification settings": "Paramètres de notification",
    "Enable email notifications": "Activer les notifications par e-mail",
    "Enable push notifications": "Activer les notifications push",
    "Notification Preference": "Préférence de Notification",
    "Notification Preferences": "Préférences de Notification",
    "Channel": "Canal",
    "Channels": "Canaux",

    # ── Mutual Aid ──
    "Aid Request": "Demande d'Aide",
    "Aid Requests": "Demandes d'Aide",
    "Aid Offer": "Offre d'Aide",
    "Aid Offers": "Offres d'Aide",
    "Aid Category": "Catégorie d'Aide",
    "Aid Categories": "Catégories d'Aide",
    "Urgency": "Urgence",
    "Low": "Faible",
    "Medium": "Moyen",
    "High": "Élevé",
    "Critical": "Critique",
    "Open": "Ouvert",
    "Closed": "Fermé",
    "In Progress": "En Cours",
    "Resolved": "Résolu",
    "Latitude": "Latitude",
    "Longitude": "Longitude",
    "Radius": "Rayon",
    "Available": "Disponible",
    "Unavailable": "Indisponible",
    "Skills": "Compétences",
    "Equipment": "Équipement",
    "Notes": "Notes",
    "Active": "Actif",
    "Inactive": "Inactif",
    "Expires at": "Expire le",
    "Created at": "Créé le",
    "Updated at": "Mis à jour le",
    "Created by": "Créé par",

    # ── Common actions / UI ──
    "Save": "Enregistrer",
    "Cancel": "Annuler",
    "Edit": "Modifier",
    "Add": "Ajouter",
    "Remove": "Supprimer",
    "Search": "Rechercher",
    "Filter": "Filtrer",
    "Sort": "Trier",
    "View": "Voir",
    "Details": "Détails",
    "Back": "Retour",
    "Next": "Suivant",
    "Previous": "Précédent",
    "Submit": "Soumettre",
    "Confirm": "Confirmer",
    "Close": "Fermer",
    "Update": "Mettre à jour",
    "Yes": "Oui",
    "No": "Non",
    "None": "Aucun",
    "All": "Tous",
    "Name": "Nom",
    "Type": "Type",
    "Actions": "Actions",
    "Loading...": "Chargement...",
    "Error": "Erreur",
    "Success": "Succès",
    "Warning": "Avertissement",
    "Info": "Info",

    # ── Wagtail snippets ──
    "Snippet": "Fragment",
    "Snippets": "Fragments",
    "Menu item": "Élément de menu",
    "Menu items": "Éléments de menu",
    "Navigation": "Navigation",
    "External link": "Lien externe",
    "Internal link": "Lien interne",
    "Page": "Page",
    "Pages": "Pages",
    "Parent page": "Page parente",
    "Order": "Ordre",
    "Sort order": "Ordre de tri",
    "Show in menu": "Afficher dans le menu",

    # ── Uploads / Gallery ──
    "Upload": "Téléversement",
    "Uploads": "Téléversements",
    "Album": "Album",
    "Albums": "Albums",
    "Upload date": "Date de téléversement",
    "File size": "Taille du fichier",
    "File type": "Type de fichier",
    "Width": "Largeur",
    "Height": "Hauteur",
    "Alt text": "Texte alternatif",
    "Thumbnail": "Miniature",

    # ── Partners ──
    "Partner": "Partenaire",
    "Partners": "Partenaires",
    "Partner Category": "Catégorie Partenaire",
    "Partner Categories": "Catégories Partenaires",
    "Discount": "Réduction",
    "Benefit": "Avantage",
    "Benefits": "Avantages",
    "Valid from": "Valide à partir du",
    "Valid until": "Valide jusqu'au",
    "Terms and conditions": "Conditions générales",

    # ── Press Office ──
    "Press Release": "Communiqué de Presse",
    "Press Releases": "Communiqués de Presse",

    # ── Registration form ──
    "Registration": "Inscription",
    "Register": "S'inscrire",
    "Login": "Connexion",
    "Logout": "Déconnexion",
    "Sign up": "S'inscrire",
    "Sign in": "Se connecter",
    "Password": "Mot de passe",
    "Confirm password": "Confirmer le mot de passe",
    "Forgot password?": "Mot de passe oublié ?",
    "Reset password": "Réinitialiser le mot de passe",
    "Change password": "Changer le mot de passe",
    "Account": "Compte",
    "Profile": "Profil",
    "Settings": "Paramètres",
    "Preferences": "Préférences",

    # ── Event-specific ──
    "Upcoming events": "Événements à venir",
    "Past events": "Événements passés",
    "No upcoming events": "Aucun événement à venir",
    "Event details": "Détails de l'événement",
    "Register for event": "S'inscrire à l'événement",
    "Cancel registration": "Annuler l'inscription",
    "Registration closed": "Inscriptions closes",
    "Event full": "Événement complet",
    "Spots available": "Places disponibles",
    "Organizer": "Organisateur",
    "Route": "Itinéraire",
    "Route map": "Carte de l'itinéraire",
    "Distance": "Distance",
    "Difficulty": "Difficulté",
    "Easy": "Facile",
    "Moderate": "Modéré",
    "Hard": "Difficile",
    "Expert": "Expert",
    "GPX file": "Fichier GPX",
    "Route description": "Description de l'itinéraire",
    "Waypoints": "Points de passage",
    "Departure": "Départ",
    "Arrival": "Arrivée",
    "Duration": "Durée",

    # ── Verification / Moderation ──
    "Verified": "Vérifié",
    "Not verified": "Non vérifié",
    "Verification": "Vérification",
    "Verification code": "Code de vérification",
    "Verification token": "Jeton de vérification",
    "Approved": "Approuvé",
    "Rejected": "Rejeté",
    "Pending review": "En attente de révision",
    "Moderation": "Modération",
    "Report": "Signaler",
    "Reported": "Signalé",
    "Ban": "Bannir",
    "Banned": "Banni",

    # ── Interest / Comment ──
    "Interested": "Intéressé",
    "Maybe": "Peut-être",
    "Going": "J'y vais",
    "Interest level": "Niveau d'intérêt",
    "Comment": "Commentaire",
    "Comments": "Commentaires",
    "Add comment": "Ajouter un commentaire",
    "Edit comment": "Modifier le commentaire",
    "Delete comment": "Supprimer le commentaire",
    "Reply": "Répondre",

    # ── Sync / Federation ──
    "Last sync": "Dernière synchronisation",
    "Last error": "Dernière erreur",
    "Is active": "Est actif",
    "Is approved": "Est approuvé",
    "Source club": "Club d'origine",
    "External ID": "ID externe",
    "Event name": "Nom de l'événement",
    "Location name": "Nom du lieu",
    "Location address": "Adresse du lieu",
    "Event status": "Statut de l'événement",
    "Image URL": "URL de l'image",
    "Detail URL": "URL de détail",
    "Is hidden": "Est masqué",
    "Fetched at": "Récupéré le",
    "Short code": "Code court",
    "Base URL": "URL de base",
    "Logo URL": "URL du logo",
    "API key": "Clé API",

    # ── Misc field labels ──
    "Scheduled": "Programmé",
    "Moved Online": "Déplacé en Ligne",
    "Postponed": "Reporté",
    "EventScheduled": "Programmé",
    "EventCancelled": "Annulé",
    "EventPostponed": "Reporté",
    "EventMovedOnline": "Déplacé en Ligne",
    "No": "Non",
    "Yes": "Oui",
    "True": "Vrai",
    "False": "Faux",
    "Enabled": "Activé",
    "Disabled": "Désactivé",

    # ── SEO / JSON-LD ──
    "Structured data": "Données structurées",
    "Schema type": "Type de schéma",
    "JSON-LD": "JSON-LD",
    "Open Graph": "Open Graph",
    "Twitter Card": "Twitter Card",
    "Canonical URL": "URL canonique",
    "Robots": "Robots",
    "Sitemap": "Plan du site",
    "sitemap.xml": "sitemap.xml",

    # ── Wagtail admin ──
    "Dashboard": "Tableau de bord",
    "Explorer": "Explorateur",
    "Images": "Images",
    "Search terms": "Termes de recherche",
    "Search promotions": "Promotions de recherche",
    "Redirects": "Redirections",
    "Users": "Utilisateurs",
    "Groups": "Groupes",
    "Sites": "Sites",
    "Collections": "Collections",
    "Workflows": "Flux de travail",
    "Tasks": "Tâches",
    "Locked pages": "Pages verrouillées",
    "Aging pages": "Pages anciennes",
    "Reports": "Rapports",

    # ── i18n / locale ──
    "Language": "Langue",
    "English": "Anglais",
    "Italian": "Italien",
    "French": "Français",
    "German": "Allemand",
    "Spanish": "Espagnol",
    "Select language": "Sélectionner la langue",

    # ── Form validations ──
    "This field is required.": "Ce champ est obligatoire.",
    "Enter a valid email address.": "Saisissez une adresse e-mail valide.",
    "Enter a valid URL.": "Saisissez une URL valide.",
    "Enter a valid value.": "Saisissez une valeur valide.",
    "Ensure this value is greater than or equal to %(limit_value)s.": "Assurez-vous que cette valeur est supérieure ou égale à %(limit_value)s.",
    "Ensure this value is less than or equal to %(limit_value)s.": "Assurez-vous que cette valeur est inférieure ou égale à %(limit_value)s.",

    # ── Privacy / GDPR ──
    "I accept the <a href='/privacy/' target='_blank' rel='noopener'>terms and conditions</a>":
        "J'accepte les <a href='/privacy/' target='_blank' rel='noopener'>conditions générales</a>",

    # ── Color Scheme choices ──
    "light": "clair",
    "dark": "sombre",
    "auto": "automatique",
    "Light": "Clair",
    "Dark": "Sombre",

    # ── PWA / Push ──
    "Install app": "Installer l'application",
    "Subscribe to notifications": "S'abonner aux notifications",
    "Unsubscribe from notifications": "Se désabonner des notifications",
    "Offline": "Hors ligne",
    "Online": "En ligne",
    "Update available": "Mise à jour disponible",
    "Refresh": "Actualiser",

    # ── Contribution / Moderation ──
    "Contribution": "Contribution",
    "Contributions": "Contributions",
    "Contributor": "Contributeur",
    "Contributors": "Contributeurs",
    "Suggestion": "Suggestion",
    "Suggestions": "Suggestions",
    "Pending approval": "En attente d'approbation",

    # ── Time-related ──
    "Today": "Aujourd'hui",
    "Tomorrow": "Demain",
    "Yesterday": "Hier",
    "This week": "Cette semaine",
    "Next week": "Semaine prochaine",
    "This month": "Ce mois-ci",
    "Next month": "Mois prochain",
    "Daily": "Quotidien",
    "Weekly": "Hebdomadaire",
    "Monthly": "Mensuel",
    "Never": "Jamais",

    # ── Product / membership tiers ──
    "Product": "Produit",
    "Product name": "Nom du produit",
    "Product type": "Type de produit",
    "Includes event registration": "Inclut l'inscription aux événements",
    "Annual": "Annuel",

    # ── Email subjects / messages ──
    "Welcome": "Bienvenue",
    "Goodbye": "Au revoir",
    "Thank you": "Merci",
    "Confirmation": "Confirmation",
    "Reminder": "Rappel",
    "Alert": "Alerte",
    "Important": "Important",
    "New": "Nouveau",

    # ── Common model field names as verbose_name ──
    "address": "adresse",
    "city": "ville",
    "province": "province",
    "postal code": "code postal",
    "country": "pays",
    "phone": "téléphone",
    "mobile": "mobile",
    "email": "e-mail",
    "first name": "prénom",
    "last name": "nom",
    "display name": "nom d'affichage",
    "birth date": "date de naissance",
    "birth place": "lieu de naissance",
    "photo": "photo",
    "bio": "biographie",
    "fiscal code": "code fiscal",
    "document type": "type de document",
    "document number": "numéro de document",
    "document expiry": "expiration du document",
    "card number": "numéro de carte",
    "membership date": "date d'adhésion",
    "membership expiry": "expiration de l'adhésion",
    "is active": "est actif",
    "show in directory": "afficher dans l'annuaire",
    "public profile": "profil public",
    "show real name to members": "afficher le vrai nom aux membres",
    "newsletter": "newsletter",
    "email notifications": "notifications par e-mail",
    "push notifications": "notifications push",
    "news updates": "actualités",
    "event updates": "mises à jour des événements",
    "event reminders": "rappels d'événements",
    "membership alerts": "alertes d'adhésion",
    "partner updates": "mises à jour des partenaires",
    "aid requests": "demandes d'aide",
    "partner events": "événements partenaires",
    "partner event comments": "commentaires sur les événements partenaires",
    "digest frequency": "fréquence du résumé",
    "aid available": "aide disponible",
    "aid radius km": "rayon d'aide (km)",
    "aid location city": "ville de localisation d'aide",
    "aid coordinates": "coordonnées d'aide",
    "aid notes": "notes d'aide",
    "products": "produits",

    # ── mutual_aid model strings ──
    "request": "demande",
    "offer": "offre",
    "Roadside assistance": "Assistance routière",
    "Mechanical help": "Aide mécanique",
    "Transport": "Transport",
    "Accommodation": "Hébergement",
    "Medical": "Médical",
    "Other": "Autre",
    "other": "autre",
    "Description of the problem or assistance needed": "Description du problème ou de l'aide nécessaire",
    "Title of the aid request": "Titre de la demande d'aide",
    "Aid request": "Demande d'aide",
    "Aid offer": "Offre d'aide",
    "Responder": "Intervenant",
    "Requester": "Demandeur",
    "Response": "Réponse",
    "Responses": "Réponses",
    "Aid Response": "Réponse d'Aide",
    "Aid Responses": "Réponses d'Aide",
    "Response message": "Message de réponse",
    "Estimated arrival": "Arrivée estimée",
    "Can help": "Peut aider",
    "On the way": "En route",
    "Arrived": "Arrivé",
    "Completed": "Terminé",
    "Did not show": "Ne s'est pas présenté",

    # ── Notification types ──
    "event_registration": "inscription_événement",
    "event_reminder": "rappel_événement",
    "event_update": "mise_à_jour_événement",
    "membership_expiry": "expiration_adhésion",
    "aid_request": "demande_aide",
    "aid_response": "réponse_aide",
    "partner_event": "événement_partenaire",
    "system": "système",
    "general": "général",
    "email": "e-mail",
    "push": "push",
    "in_app": "en_application",
    "both": "les deux",

    # ── Additional form/template strings ──
    "Are you sure?": "Êtes-vous sûr ?",
    "This action cannot be undone.": "Cette action est irréversible.",
    "No results found.": "Aucun résultat trouvé.",
    "Showing %(start)s to %(end)s of %(total)s results": "Résultats %(start)s à %(end)s sur %(total)s",
    "Page %(current)s of %(total)s": "Page %(current)s sur %(total)s",
    "Items per page": "Éléments par page",
    "Apply": "Appliquer",
    "Reset": "Réinitialiser",
    "Clear": "Effacer",
    "Select all": "Tout sélectionner",
    "Deselect all": "Tout désélectionner",
    "Export": "Exporter",
    "Import": "Importer",
    "CSV": "CSV",
    "PDF": "PDF",
    "Print": "Imprimer",

    # ── Registration flow ──
    "Passenger": "Passager",
    "Has passenger": "A un passager",
    "Passenger is member": "Le passager est membre",
    "Passenger name": "Nom du passager",
    "Number of extra guests": "Nombre d'invités supplémentaires",
    "Special requests": "Demandes spéciales",
    "Total": "Total",
    "Subtotal": "Sous-total",
    "Tax": "Taxes",
    "Registration date": "Date d'inscription",
    "Registration status": "Statut de l'inscription",
    "Confirm registration": "Confirmer l'inscription",
    "cancel": "annuler",
    "Extra content": "Contenu supplémentaire",

    # ── More website model strings ──
    "Hero image": "Image hero",
    "Intro": "Introduction",
    "intro": "introduction",
    "Related pages": "Pages associées",
    "Related links": "Liens associés",
    "Sidebar": "Barre latérale",
    "Header": "En-tête",
    "Main content": "Contenu principal",
    "Call to action": "Appel à l'action",
    "call to action": "appel à l'action",
    "Banner": "Bannière",
    "Promo": "Promotion",
    "Highlight": "En vedette",
    "Text": "Texte",
    "text": "texte",
    "Block type": "Type de bloc",

    # ── Error messages ──
    "An error occurred.": "Une erreur s'est produite.",
    "Permission denied.": "Accès refusé.",
    "Not found.": "Non trouvé.",
    "Page not found": "Page non trouvée",
    "Server error": "Erreur du serveur",
    "Bad request": "Requête invalide",
    "Forbidden": "Interdit",
    "Unauthorized": "Non autorisé",
    "Service unavailable": "Service indisponible",

    # ── Pricing tiers ──
    "Early Bird": "Tarif précoce",
    "Regular": "Régulier",
    "Late": "Tardif",
    "VIP": "VIP",
    "Standard": "Standard",
    "Premium": "Premium",
    "Basic": "Basique",

    # ── Additional wagtail/website fields ──
    "Published date": "Date de publication",
    "Publish date": "Date de publication",
    "Expire date": "Date d'expiration",
    "Go live date": "Date de mise en ligne",
    "First published at": "Première publication",
    "Last published at": "Dernière publication",
    "Latest revision created at": "Dernière révision créée le",
    "Live": "Publié",
    "Has unpublished changes": "A des modifications non publiées",
    "Locked": "Verrouillé",
    "Locked by": "Verrouillé par",
    "Locked at": "Verrouillé le",

    # ── Menu/admin strings Wagtail ──
    "Menu label": "Libellé du menu",
    "Admin display title": "Titre d'affichage admin",

    # ── Additional mutual aid ──
    "Accept": "Accepter",
    "Reject": "Rejeter",
    "Withdraw": "Retirer",
    "Confirm arrival": "Confirmer l'arrivée",
    "Mark as resolved": "Marquer comme résolu",
    "Request help": "Demander de l'aide",
    "Offer help": "Proposer de l'aide",
    "Your location": "Votre position",
    "Distance from you": "Distance de vous",
    "km": "km",

    # ── Additional notification messages ──
    "You have %(count)s new notifications": "Vous avez %(count)s nouvelles notifications",
    "No new notifications": "Aucune nouvelle notification",
    "View all notifications": "Voir toutes les notifications",
    "Notification sent": "Notification envoyée",
    "Notification deleted": "Notification supprimée",

    # ── Choices for document_type ──
    "ID Card": "Carte d'identité",
    "Passport": "Passeport",
    "Driving License": "Permis de conduire",

    # ── Additional registration ──
    "Check-in": "Enregistrement",
    "Checked in": "Enregistré",
    "Not checked in": "Non enregistré",
    "QR Code": "Code QR",
    "Scan QR code": "Scanner le code QR",

    # ── Additional patterns ──
    "per year": "par an",
    "per month": "par mois",
    "valid": "valide",
    "invalid": "invalide",
    "required": "obligatoire",
    "optional": "facultatif",
    "default": "par défaut",
    "custom": "personnalisé",
    "public": "public",
    "private": "privé",
    "visible": "visible",
    "hidden": "masqué",
    "enabled": "activé",
    "disabled": "désactivé",

    # ──────────────────────────────────────────────────────────
    #  PASS 2 – remaining translations
    # ──────────────────────────────────────────────────────────

    # ── Membership card / QR ──
    "No membership card available.": "Aucune carte de membre disponible.",
    "QR code generation not available.": "Génération de code QR non disponible.",
    "Barcode generation not available.": "Génération de code-barres non disponible.",
    "Your name": "Votre nom",
    "Phone number": "Numéro de téléphone",
    "Email address": "Adresse e-mail",
    "Your current location": "Votre position actuelle",
    "Description must be 5000 characters or fewer.": "La description doit contenir 5000 caractères ou moins.",
    "Why do you need access? (optional)": "Pourquoi avez-vous besoin d'un accès ? (facultatif)",
    "Role": "Rôle",
    "Emergency Contact": "Contact d'Urgence",
    "Introduction": "Introduction",
    "Emergency contacts": "Contacts d'urgence",
    "Default map radius (km)": "Rayon de carte par défaut (km)",
    "Enable federation": "Activer la fédération",

    # ── Mutual Aid Pages ──
    "Mutual Aid Page": "Page d'Entraide",
    "Mutual Aid Pages": "Pages d'Entraide",
    "Show phone number": "Afficher le numéro de téléphone",
    "Show mobile number": "Afficher le numéro de mobile",
    "Show WhatsApp availability": "Afficher la disponibilité WhatsApp",
    "Show email address": "Afficher l'adresse e-mail",
    "Show exact location": "Afficher la position exacte",
    "If disabled, only the city name is shown.": "Si désactivé, seul le nom de la ville est affiché.",
    "Show profile photo": "Afficher la photo de profil",
    "Show bio": "Afficher la biographie",
    "Show availability hours": "Afficher les heures de disponibilité",
    "Aid Privacy Settings": "Paramètres de Confidentialité d'Aide",

    # ── Urgency levels ──
    "Low - can wait": "Faible - peut attendre",
    "Medium - within a day": "Moyen - dans la journée",
    "High - urgent": "Élevé - urgent",
    "Emergency - immediate": "Urgence - immédiat",
    "Accepted": "Accepté",
    "In progress": "En cours",

    # ── Aid issue types ──
    "Breakdown": "Panne",
    "Flat tire": "Crevaison",
    "Out of fuel": "En panne de carburant",
    "Accident": "Accident",
    "Need towing": "Besoin de remorquage",
    "Need tools": "Besoin d'outils",
    "Need transport": "Besoin de transport",
    "Need accommodation": "Besoin d'hébergement",
    "Helper": "Aidant",
    "Requester name": "Nom du demandeur",
    "Requester phone": "Téléphone du demandeur",
    "Requester email": "E-mail du demandeur",
    "Requester (if member)": "Demandeur (si membre)",
    "Issue type": "Type de problème",
    "Where are you? Address or coordinates.": "Où êtes-vous ? Adresse ou coordonnées.",

    # ── Federation access ──
    "From federation": "De la fédération",
    "Federation access": "Accès fédération",
    "Can contact helpers": "Peut contacter les aidants",
    "External user ID": "ID utilisateur externe",
    "External display name": "Nom d'affichage externe",
    "Contacts unlocked": "Contacts débloqués",
    "Access level": "Niveau d'accès",
    "Approved by": "Approuvé par",
    "Federated Aid Access": "Accès Aide Fédérée",
    "Federated Aid Access Grants": "Autorisations d'Accès Aide Fédérée",
    "Denied": "Refusé",
    "Federated access": "Accès fédéré",
    "Why are you requesting access?": "Pourquoi demandez-vous l'accès ?",
    "Reviewed by": "Examiné par",
    "Reviewed at": "Examiné le",
    "Federated Aid Access Request": "Demande d'Accès Aide Fédérée",
    "Federated Aid Access Requests": "Demandes d'Accès Aide Fédérée",
    "Contact Unlock": "Déblocage de Contact",
    "Contact Unlocks": "Déblocages de Contacts",
    "Active membership required.": "Adhésion active requise.",

    # ── Notification types ──
    "News published": "Actualité publiée",
    "Event published": "Événement publié",
    "Event reminder": "Rappel d'événement",
    "Weekend favorites": "Favoris du week-end",
    "Registration opens": "Ouverture des inscriptions",
    "Photo approved": "Photo approuvée",
    "Membership expiring": "Adhésion bientôt expirée",
    "Partner news": "Actualités partenaires",
    "Partner event interest": "Intérêt pour événement partenaire",
    "Partner event comment": "Commentaire sur événement partenaire",
    "Partner event cancelled": "Événement partenaire annulé",
    "Mutual aid request": "Demande d'entraide",
    "Mutual aid access request": "Demande d'accès entraide",
    "Payment instructions": "Instructions de paiement",
    "Payment confirmed": "Paiement confirmé",
    "Payment expired": "Paiement expiré",
    "Registration cancelled": "Inscription annulée",
    "Promoted from waitlist": "Promu de la liste d'attente",
    "Push notification": "Notification push",
    "In-app notification": "Notification dans l'application",
    "Failed": "Échoué",
    "Skipped": "Ignoré",

    # ── Notification model fields (lowercase) ──
    "notification type": "type de notification",
    "content type": "type de contenu",
    "object ID": "ID d'objet",
    "recipient": "destinataire",
    "channel": "canal",
    "status": "statut",
    "title": "titre",
    "body": "corps",
    "scheduled for": "programmé pour",
    "If set, notification will not be sent before this time.": "Si défini, la notification ne sera pas envoyée avant cette heure.",
    "sent at": "envoyé le",
    "created at": "créé le",
    "error message": "message d'erreur",
    "notification": "notification",
    "notifications": "notifications",

    # ── Push subscriptions ──
    "user": "utilisateur",
    "endpoint": "point de terminaison",
    "Push service URL": "URL du service push",
    "p256dh key": "clé p256dh",
    "Client public encryption key": "Clé publique de chiffrement du client",
    "auth key": "clé d'authentification",
    "Client auth secret": "Secret d'authentification du client",
    "active": "actif",
    "last used": "dernière utilisation",
    "user agent": "agent utilisateur",
    "push subscription": "abonnement push",
    "push subscriptions": "abonnements push",
    "token": "jeton",
    "unsubscribe token": "jeton de désabonnement",
    "unsubscribe tokens": "jetons de désabonnement",
    "Invalid JSON body": "Corps JSON invalide",
    "Endpoint is required": "Le point de terminaison est requis",
    "Endpoint must use HTTPS": "Le point de terminaison doit utiliser HTTPS",
    "Encryption keys are required": "Les clés de chiffrement sont requises",

    # ── StreamField blocks – gallery/media ──
    "Article gallery": "Galerie d'article",
    "Event gallery": "Galerie d'événement",
    "Event location map": "Carte de localisation d'événement",
    "Card thumbnail image.": "Image miniature de la carte.",
    "Optional badge text (e.g. date, category label).": "Texte de badge facultatif (ex. date, libellé de catégorie).",
    "Card title.": "Titre de la carte.",
    "Short description text.": "Texte descriptif court.",
    "Link to page": "Lien vers la page",
    "External URL": "URL externe",
    "Used only if no internal page is selected.": "Utilisé uniquement si aucune page interne n'est sélectionnée.",
    "Button / link label.": "Libellé du bouton / lien.",
    "Optional section title above the grid.": "Titre de section facultatif au-dessus de la grille.",
    "2 columns": "2 colonnes",
    "3 columns": "3 colonnes",
    "4 columns": "4 colonnes",
    "Number of columns on desktop.": "Nombre de colonnes sur bureau.",
    "Default": "Par défaut",
    "Outlined": "Avec bordure",
    "Elevated / shadow": "Élevé / ombre",
    "Minimal": "Minimal",
    "Visual style for the cards.": "Style visuel pour les cartes.",
    "Cards grid": "Grille de cartes",

    # ── CTA block ──
    "CTA headline.": "Titre CTA.",
    "Supporting text.": "Texte d'accompagnement.",
    "Button label.": "Libellé du bouton.",
    "Button page link": "Lien page du bouton",
    "Button external URL": "URL externe du bouton",
    "Primary colour": "Couleur primaire",
    "Gradient": "Dégradé",
    "Image background": "Arrière-plan image",
    "Background style for this section.": "Style d'arrière-plan pour cette section.",
    "Background image (only used with 'Image background' style).": "Image de fond (utilisée uniquement avec le style 'Arrière-plan image').",

    # ── Statistics block ──
    "The numeric value or short text (e.g. '1500+').": "La valeur numérique ou texte court (ex. '1500+').",
    "Description of the stat (e.g. 'Members').": "Description de la statistique (ex. 'Membres').",
    "Optional icon class name.": "Nom de classe d'icône facultatif.",
    "Statistic": "Statistique",
    "Optional section title.": "Titre de section facultatif.",
    "Statistics": "Statistiques",

    # ── Testimonial / Quote block ──
    "The quote text.": "Le texte de la citation.",
    "Name of the person quoted.": "Nom de la personne citée.",
    "Role or title of the author (e.g. 'President').": "Rôle ou titre de l'auteur (ex. 'Président').",
    "Optional portrait of the author.": "Portrait facultatif de l'auteur.",

    # ── Timeline block ──
    "Year or date label (e.g. '2015').": "Année ou libellé de date (ex. '2015').",
    "Event or milestone title.": "Titre de l'événement ou étape.",
    "Detailed description of this event.": "Description détaillée de cet événement.",
    "Timeline entry": "Entrée chronologique",
    "Timeline entries": "Entrées chronologiques",
    "Timeline": "Chronologie",

    # ── Team block ──
    "Position or title.": "Position ou titre.",
    "Short biography.": "Courte biographie.",
    "Team member": "Membre de l'équipe",
    "Optional section title (e.g. 'Board of Directors').": "Titre de section facultatif (ex. 'Conseil d'Administration').",
    "Team members": "Membres de l'équipe",
    "Team grid": "Grille d'équipe",

    # ── Newsletter block ──
    "Stay updated": "Restez informé",
    "Form heading.": "Titre du formulaire.",
    "Short text explaining what subscribers will receive.": "Texte court expliquant ce que les abonnés recevront.",
    "Subscribe": "S'abonner",
    "Newsletter signup": "Inscription à la newsletter",

    # ── Alert block ──
    "Alert message content.": "Contenu du message d'alerte.",
    "Danger": "Danger",
    "Visual style and severity of the alert.": "Style visuel et gravité de l'alerte.",
    "Allow users to dismiss this alert.": "Permettre aux utilisateurs de fermer cette alerte.",

    # ── Slider / Hero slider ──
    "Slide background image.": "Image de fond de la diapositive.",
    "Slide headline.": "Titre de la diapositive.",
    "Optional subtitle text.": "Texte de sous-titre facultatif.",
    "CTA text": "Texte CTA",
    "CTA page link": "Lien page CTA",
    "CTA external URL": "URL externe CTA",
    "Slide": "Diapositive",
    "Slides": "Diapositives",
    "Automatically advance slides.": "Avancer les diapositives automatiquement.",
    "Time between slides in milliseconds.": "Temps entre les diapositives en millisecondes.",
    "Half screen": "Demi-écran",
    "Three-quarter screen": "Trois-quarts d'écran",
    "Full screen": "Plein écran",
    "Slider height.": "Hauteur du diaporama.",
    "Show navigation arrows.": "Afficher les flèches de navigation.",
    "Show dot indicators.": "Afficher les indicateurs de points.",
    "Hero slider": "Diaporama hero",

    # ── Hero banner ──
    "Hero background image.": "Image de fond hero.",
    "Small badge text above the title (e.g. 'Est. 2010').": "Petit texte de badge au-dessus du titre (ex. 'Est. 2010').",
    "Main headline.": "Titre principal.",
    "Supporting text below the title.": "Texte d'accompagnement sous le titre.",
    "Secondary CTA text": "Texte CTA secondaire",
    "Optional secondary button label.": "Libellé du bouton secondaire facultatif.",
    "Secondary CTA page link": "Lien page CTA secondaire",
    "Secondary CTA external URL": "URL externe CTA secondaire",
    "Light overlay": "Superposition claire",
    "Dark overlay": "Superposition sombre",
    "Gradient overlay": "Superposition dégradée",
    "Overlay style over the background image.": "Style de superposition sur l'image de fond.",
    "Bottom left": "En bas à gauche",
    "Bottom right": "En bas à droite",
    "Position of the text overlay.": "Position de la superposition de texte.",
    "Hero banner": "Bannière hero",

    # ── Hero countdown ──
    "Select an event to count down to.": "Sélectionnez un événement pour le compte à rebours.",
    "Optional background image. Falls back to event cover image.": "Image de fond facultative. En l'absence, utilise l'image de couverture de l'événement.",
    "Override the event title in the hero.": "Remplacer le titre de l'événement dans le hero.",
    "Hero countdown": "Compte à rebours hero",

    # ── Hero video ──
    "URL to the video file (MP4 recommended).": "URL du fichier vidéo (MP4 recommandé).",
    "Displayed on mobile or when video cannot play.": "Affiché sur mobile ou lorsque la vidéo ne peut pas être lue.",
    "Mute the video (required for autoplay on most browsers).": "Couper le son de la vidéo (requis pour la lecture automatique sur la plupart des navigateurs).",
    "Loop the video.": "Lire la vidéo en boucle.",
    "Hero video": "Vidéo hero",

    # ── Accordion block ──
    "Accordion panel header.": "En-tête du panneau accordéon.",
    "Panel content revealed when expanded.": "Contenu du panneau révélé lors de l'expansion.",
    "Accordion item": "Élément accordéon",
    "Optional section title above the accordion.": "Titre de section facultatif au-dessus de l'accordéon.",
    "Panels": "Panneaux",

    # ── Tab block ──
    "Tab label.": "Libellé de l'onglet.",
    "Tab panel content.": "Contenu du panneau d'onglet.",

    # ── Two columns block ──
    "Left column": "Colonne gauche",
    "Right column": "Colonne droite",
    "50 / 50": "50 / 50",
    "33 / 67": "33 / 67",
    "67 / 33": "67 / 33",
    "25 / 75": "25 / 75",
    "75 / 25": "75 / 25",
    "Column width ratio.": "Rapport de largeur des colonnes.",
    "Two columns": "Deux colonnes",

    # ── Section block ──
    "Optional section heading.": "Titre de section facultatif.",
    "Section body content.": "Contenu du corps de la section.",
    "Secondary colour": "Couleur secondaire",
    "Light grey": "Gris clair",
    "Background style.": "Style d'arrière-plan.",
    "Small": "Petit",
    "Large": "Grand",
    "Extra large": "Très grand",
    "Vertical padding.": "Espacement vertical.",

    # ── Separator/spacer ──
    "Horizontal line": "Ligne horizontale",
    "Dots": "Points",
    "Blank space": "Espace vide",
    "Separator visual style.": "Style visuel du séparateur.",
    "Small (1rem)": "Petit (1rem)",
    "Medium (2rem)": "Moyen (2rem)",
    "Large (4rem)": "Grand (4rem)",
    "Extra large (6rem)": "Très grand (6rem)",
    "Amount of vertical space.": "Quantité d'espace vertical.",

    # ── Gallery block ──
    "Optional caption displayed below the image.": "Légende facultative affichée sous l'image.",
    "Gallery image": "Image de galerie",
    "Optional gallery title.": "Titre de galerie facultatif.",
    "6 columns": "6 colonnes",
    "Enable lightbox for full-size image viewing.": "Activer la lightbox pour la visualisation en taille réelle.",
    "Auto (original)": "Automatique (original)",
    "Square (1:1)": "Carré (1:1)",
    "Landscape (4:3)": "Paysage (4:3)",
    "Widescreen (16:9)": "Panoramique (16:9)",
    "Portrait (3:4)": "Portrait (3:4)",
    "Thumbnail aspect ratio.": "Rapport d'aspect des miniatures.",

    # ── Video embed ──
    "Paste a video URL (YouTube, Vimeo, etc.).": "Collez une URL de vidéo (YouTube, Vimeo, etc.).",
    "Optional caption displayed below the video.": "Légende facultative affichée sous la vidéo.",
    "Autoplay the video (muted).": "Lire automatiquement la vidéo (sans son).",
    "Video embed": "Intégration vidéo",

    # ── Image block ──
    "Centred": "Centré",
    "Float left": "Aligné à gauche",
    "Float right": "Aligné à droite",
    "Image alignment within the content area.": "Alignement de l'image dans la zone de contenu.",

    # ── Document list ──
    "Optional description of the document.": "Description facultative du document.",
    "Section title for the document list.": "Titre de section pour la liste de documents.",
    "Document list": "Liste de documents",

    # ── Map block ──
    "Display address (shown in the info popup).": "Adresse affichée (montrée dans la fenêtre info).",
    "Latitude,Longitude (e.g. '45.4642,9.1900').": "Latitude,Longitude (ex. '45.4642,9.1900').",
    "Map zoom level (1-20).": "Niveau de zoom de la carte (1-20).",
    "Map height in pixels.": "Hauteur de la carte en pixels.",
    "Optional marker label.": "Libellé du marqueur facultatif.",

    # ── Route / waypoints ──
    "Waypoint name (e.g. 'Passo dello Stelvio').": "Nom du point de passage (ex. 'Col du Stelvio').",
    "Optional address or location description.": "Adresse facultative ou description du lieu.",
    "Latitude,Longitude (e.g. '46.5287,10.4531').": "Latitude,Longitude (ex. '46.5287,10.4531').",
    "Start": "Départ",
    "Waypoint": "Point de passage",
    "Fuel stop": "Arrêt carburant",
    "Food / restaurant": "Restaurant",
    "Photo spot": "Point photo",
    "End": "Arrivée",
    "Marker icon type on the map.": "Type d'icône du marqueur sur la carte.",
    "Route name.": "Nom de l'itinéraire.",
    "Brief route description.": "Brève description de l'itinéraire.",
    "At least two waypoints (start and end) are required.": "Au moins deux points de passage (départ et arrivée) sont requis.",
    "Scenic ride": "Balade panoramique",
    "Touring": "Tourisme",
    "Sport / twisties": "Sport / virages",
    "Off-road / adventure": "Hors-piste / aventure",
    "Commute / practical": "Trajet / pratique",
    "Type of route.": "Type d'itinéraire.",
    "Approximate distance (e.g. '320 km').": "Distance approximative (ex. '320 km').",
    "Elevation gain (e.g. '2500 m').": "Dénivelé (ex. '2500 m').",
    "Estimated riding time (e.g. '5-6 hours').": "Temps de parcours estimé (ex. '5-6 heures').",
    "Challenging": "Exigeant",
    "Route difficulty level.": "Niveau de difficulté de l'itinéraire.",

    # ── Verification ──
    "Enter member card number": "Saisissez le numéro de carte de membre",
    "Verification type": "Type de vérification",
    "Select which piece of information to verify against.": "Sélectionnez quelle information utiliser pour la vérification.",
    "Verification value": "Valeur de vérification",
    "Enter the value to verify": "Saisissez la valeur à vérifier",

    # ── Photo uploads ──
    "Photos": "Photos",
    "Select up to 20 images (JPG, PNG, or WebP, max 10 MB each).": "Sélectionnez jusqu'à 20 images (JPG, PNG ou WebP, max 10 Mo chacune).",
    "Title prefix": "Préfixe du titre",
    "Optional prefix added to each photo title.": "Préfixe facultatif ajouté à chaque titre de photo.",
    "e.g. Summer Rally 2025": "ex. Rallye d'Été 2025",
    "Optionally link photos to an event.": "Associez facultativement les photos à un événement.",
    "-- No event --": "-- Aucun événement --",
    "You can upload a maximum of %(max)d files at a time.": "Vous pouvez téléverser un maximum de %(max)d fichiers à la fois.",
    "File '%(name)s' exceeds the maximum size of 10 MB.": "Le fichier '%(name)s' dépasse la taille maximale de 10 Mo.",
    "File '%(name)s' is not an allowed format. Only JPG, PNG, and WebP are accepted.": "Le fichier '%(name)s' n'est pas dans un format autorisé. Seuls JPG, PNG et WebP sont acceptés.",

    # ── Home page ──
    "Hero title": "Titre hero",
    "Main headline displayed in the hero section.": "Titre principal affiché dans la section hero.",
    "Hero subtitle": "Sous-titre hero",
    "Hero background image": "Image de fond hero",
    "Primary CTA text": "Texte CTA primaire",
    "Primary CTA link": "Lien CTA primaire",
    "Primary CTA external URL": "URL externe CTA primaire",
    "Secondary CTA link": "Lien CTA secondaire",
    "Featured event": "Événement en vedette",
    "Select an EventDetailPage to highlight on the homepage.": "Sélectionnez une page d'événement à mettre en avant sur la page d'accueil.",
    "Call-to-action buttons": "Boutons d'appel à l'action",
    "Featured content": "Contenu en vedette",
    "Home page": "Page d'accueil",
    "Home pages": "Pages d'accueil",
    "Displayed below the page title.": "Affiché sous le titre de la page.",
    "Cover image": "Image de couverture",

    # ── About page ──
    "About page": "Page à propos",
    "About pages": "Pages à propos",
    "Use team-member blocks here.": "Utilisez les blocs membre d'équipe ici.",

    # ── Board page ──
    "Board page": "Page du conseil d'administration",
    "Board pages": "Pages du conseil d'administration",

    # ── News index ──
    "Optional content displayed above the article listing.": "Contenu facultatif affiché au-dessus de la liste des articles.",
    "News index page": "Page d'index des actualités",
    "News index pages": "Pages d'index des actualités",
    "Introduction / excerpt": "Introduction / extrait",
    "Short summary shown in listings.": "Bref résumé affiché dans les listes.",
    "Display date": "Date d'affichage",
    "Publication date shown to readers.": "Date de publication affichée aux lecteurs.",
    "Article metadata": "Métadonnées de l'article",
    "Categorisation": "Catégorisation",
    "News page": "Page d'actualité",
    "News pages": "Pages d'actualités",

    # ── Events page ──
    "Optional content above the event listing.": "Contenu facultatif au-dessus de la liste des événements.",
    "Events page": "Page des événements",
    "Events pages": "Pages des événements",
    "Short description shown in listings.": "Brève description affichée dans les listes.",
    "Start date & time": "Date et heure de début",
    "End date & time": "Date et heure de fin",
    "Venue name": "Nom du lieu",
    "Coordinates": "Coordonnées",
    "Latitude,Longitude (e.g. '45.4642,9.1900')": "Latitude,Longitude (ex. '45.4642,9.1900')",
    "Registration open": "Inscription ouverte",
    "Registration deadline": "Date limite d'inscription",
    "Max attendees": "Nombre maximum de participants",
    "0 = unlimited.": "0 = illimité.",
    "Event participation cost in EUR.  0 = free.": "Coût de participation en EUR. 0 = gratuit.",
    "Early-bird discount (%)": "Réduction tarif précoce (%)",
    "Early-bird deadline": "Date limite tarif précoce",
    "Percentage discount for active members.": "Réduction en pourcentage pour les membres actifs.",
    "Allow guest registration": "Autoriser l'inscription d'invités",
    "Meeting point": "Point de rendez-vous",
    "Where participants should gather before the event start.": "Où les participants doivent se rassembler avant le début de l'événement.",
    "Difficulty level": "Niveau de difficulté",
    "Schedule": "Programme",
    "Registration settings": "Paramètres d'inscription",
    "Pricing": "Tarification",
    "Promote": "Promouvoir",
    "Event detail page": "Page de détail d'événement",
    "Event detail pages": "Pages de détail d'événements",

    # ── Gallery page ──
    "Root collection": "Collection racine",
    "Starting collection for gallery display.  Sub-collections become albums.": "Collection de départ pour l'affichage de la galerie. Les sous-collections deviennent des albums.",
    "Gallery page": "Page galerie",
    "Gallery pages": "Pages galerie",

    # ── Contact page ──
    "Form title": "Titre du formulaire",
    "Success message": "Message de succès",
    "Confirmation shown after form submission.": "Confirmation affichée après l'envoi du formulaire.",
    "Enable captcha": "Activer le captcha",
    "Honeypot + Time check": "Honeypot + Vérification temporelle",
    "Cloudflare Turnstile": "Cloudflare Turnstile",
    "hCaptcha": "hCaptcha",
    "Captcha provider": "Fournisseur de captcha",
    "Captcha site key": "Clé de site captcha",
    "Captcha secret key": "Clé secrète captcha",
    "Anti-spam settings": "Paramètres anti-spam",
    "Anti-spam": "Anti-spam",
    "Contact page": "Page de contact",
    "Contact pages": "Pages de contact",

    # ── Privacy page ──
    "Last updated": "Dernière mise à jour",
    "Date the policy was last revised.": "Date de la dernière révision de la politique.",
    "Privacy page": "Page de confidentialité",
    "Privacy pages": "Pages de confidentialité",

    # ── Transparency page ──
    "Use document-list and accordion blocks for organising documents.": "Utilisez les blocs liste de documents et accordéon pour organiser les documents.",
    "Transparency page": "Page de transparence",
    "Transparency pages": "Pages de transparence",

    # ── Press page ──
    "Press email": "E-mail presse",
    "Press phone": "Téléphone presse",
    "Press contact person": "Personne de contact presse",
    "Press contact": "Contact presse",
    "Press page": "Page presse",
    "Press pages": "Pages presse",

    # ── Partner index ──
    "Partner index page": "Page d'index des partenaires",
    "Partner index pages": "Pages d'index des partenaires",
    "ISO 3166-1 alpha-2 country code.": "Code pays ISO 3166-1 alpha-2.",
    "Facebook URL": "URL Facebook",
    "Instagram URL": "URL Instagram",
    "LinkedIn URL": "URL LinkedIn",
    "YouTube URL": "URL YouTube",
    "Twitter / X URL": "URL Twitter / X",
    "Partner owner": "Propriétaire partenaire",
    "User account that manages this partner page.": "Compte utilisateur qui gère cette page partenaire.",
    "Owner email": "E-mail du propriétaire",
    "Contact email for the partner owner.": "E-mail de contact du propriétaire partenaire.",
    "Show this partner prominently.": "Afficher ce partenaire en évidence.",
    "Display order": "Ordre d'affichage",
    "Lower numbers appear first.": "Les numéros les plus bas apparaissent en premier.",
    "Show on homepage": "Afficher sur la page d'accueil",
    "Partnership start": "Début du partenariat",
    "Partnership end": "Fin du partenariat",
    "Leave blank for ongoing partnerships.": "Laissez vide pour les partenariats en cours.",
    "Social media": "Réseaux sociaux",
    "Ownership": "Propriété",
    "Display settings": "Paramètres d'affichage",
    "Social": "Social",
    "Display": "Affichage",
    "Partner page": "Page partenaire",
    "Partner pages": "Pages partenaires",

    # ── Theme names ──
    "Velocity": "Velocity",
    "Heritage": "Heritage",
    "Terra / Eco": "Terra / Eco",
    "Zen": "Zen",
    "Clubs": "Clubs",
    "Tricolore": "Tricolore",

    # ── Site settings ──
    "Honeypot (no external service)": "Honeypot (sans service externe)",
    "OpenStreetMap": "OpenStreetMap",
    "Google Maps": "Google Maps",
    "Mapbox": "Mapbox",
    "Human-readable name shown in the header / meta tags.": "Nom lisible affiché dans l'en-tête / balises meta.",
    "Site description": "Description du site",
    "Default meta description for SEO.": "Description meta par défaut pour le SEO.",
    "Colour scheme": "Palette de couleurs",
    "Logo (dark variant)": "Logo (variante sombre)",
    "Optional dark-background version of the logo.": "Version facultative du logo sur fond sombre.",
    "Opening hours": "Heures d'ouverture",
    "TikTok URL": "URL TikTok",
    "Navbar": "Barre de navigation",
    "PWA name": "Nom PWA",
    "PWA short name": "Nom court PWA",
    "PWA description": "Description PWA",
    "PWA icon 192x192": "Icône PWA 192x192",
    "PWA icon 512x512": "Icône PWA 512x512",
    "PWA theme colour": "Couleur du thème PWA",
    "PWA background colour": "Couleur de fond PWA",
    "CAPTCHA provider": "Fournisseur CAPTCHA",
    "CAPTCHA site key": "Clé de site CAPTCHA",
    "CAPTCHA secret key": "Clé secrète CAPTCHA",
    "Map routing service": "Service de routage cartographique",
    "Map API key": "Clé API cartographique",
    "Required for Google Maps / Mapbox.": "Requis pour Google Maps / Mapbox.",
    "Default map centre": "Centre de carte par défaut",
    "Default map zoom": "Zoom de carte par défaut",
    "General": "Général",
    "Branding": "Image de marque",
    "Progressive Web App": "Progressive Web App",
    "PWA": "PWA",
    "Anti-spam / CAPTCHA": "Anti-spam / CAPTCHA",
    "Forms": "Formulaires",
    "Map & routing": "Carte et itinéraires",
    "site settings": "paramètres du site",

    # ── Payment settings ──
    "Test": "Test",
    "Payment mode": "Mode de paiement",
    "Only credentials for the selected mode are used at runtime.": "Seules les identifiants du mode sélectionné sont utilisés à l'exécution.",
    "Stripe enabled (test)": "Stripe activé (test)",
    "Stripe public key (test)": "Clé publique Stripe (test)",
    "Stripe secret key (test)": "Clé secrète Stripe (test)",
    "Stripe webhook secret (test)": "Secret webhook Stripe (test)",
    "PayPal enabled (test)": "PayPal activé (test)",
    "PayPal client ID (test)": "ID client PayPal (test)",
    "PayPal secret (test)": "Secret PayPal (test)",
    "Stripe enabled (live)": "Stripe activé (live)",
    "Stripe public key (live)": "Clé publique Stripe (live)",
    "Stripe secret key (live)": "Clé secrète Stripe (live)",
    "Stripe webhook secret (live)": "Secret webhook Stripe (live)",
    "PayPal enabled (live)": "PayPal activé (live)",
    "PayPal client ID (live)": "ID client PayPal (live)",
    "PayPal secret (live)": "Secret PayPal (live)",
    "Bank transfer enabled": "Virement bancaire activé",
    "Account holder": "Titulaire du compte",
    "IBAN": "IBAN",
    "BIC / SWIFT": "BIC / SWIFT",
    "Bank name": "Nom de la banque",
    "Bank transfer instructions": "Instructions de virement bancaire",
    "Additional instructions shown to the user (e.g. 'Include the reference in the description').": "Instructions supplémentaires affichées à l'utilisateur (ex. 'Inclure la référence dans le motif').",
    "Bank transfer expiry (days)": "Expiration du virement bancaire (jours)",
    "Days allowed for the user to complete the bank transfer.": "Jours accordés à l'utilisateur pour effectuer le virement bancaire.",
    "Active mode": "Mode actif",
    "Mode": "Mode",
    "Stripe (test)": "Stripe (test)",
    "PayPal (test)": "PayPal (test)",
    "Test configuration": "Configuration de test",
    "Stripe (live)": "Stripe (live)",
    "PayPal (live)": "PayPal (live)",
    "Live configuration": "Configuration live",
    "Bank transfer": "Virement bancaire",
    "payment settings": "paramètres de paiement",

    # ── Colour scheme snippet ──
    "Main brand colour (hex).": "Couleur principale de la marque (hex).",
    "Secondary/accent brand colour (hex).": "Couleur d'accent/secondaire de la marque (hex).",
    "Accent colour": "Couleur d'accent",
    "Accent highlight colour (hex).": "Couleur d'accent mis en valeur (hex).",
    "Surface colour": "Couleur de surface",
    "Card/panel background colour (hex).": "Couleur de fond carte/panneau (hex).",
    "Surface alt colour": "Couleur de surface alternative",
    "Alternate surface colour (hex).": "Couleur de surface alternative (hex).",
    "Text primary": "Texte primaire",
    "Main body text colour (hex).": "Couleur du texte principal (hex).",
    "Text muted": "Texte atténué",
    "Secondary/lighter text colour (hex).": "Couleur de texte secondaire/clair (hex).",
    "Enable if this is a dark colour scheme.": "Activez si c'est une palette de couleurs sombre.",
    "Brand colours": "Couleurs de la marque",
    "Surface colours": "Couleurs de surface",
    "Text colours": "Couleurs du texte",
    "colour scheme": "palette de couleurs",
    "colour schemes": "palettes de couleurs",

    # ── Navbar snippet ──
    "Show search": "Afficher la recherche",
    "navbar": "barre de navigation",
    "navbars": "barres de navigation",
    "Parent item": "Élément parent",
    "Leave empty for top-level items. Select a parent for dropdown sub-items.": "Laissez vide pour les éléments de premier niveau. Sélectionnez un parent pour les sous-éléments déroulants.",
    "Link page": "Page liée",
    "Used only when no page is selected.": "Utilisé uniquement lorsqu'aucune page n'est sélectionnée.",
    "Open in new tab": "Ouvrir dans un nouvel onglet",
    "Is CTA": "Est CTA",
    "Render as a highlighted call-to-action button.": "Afficher comme bouton d'appel à l'action mis en évidence.",

    # ── Footer snippet ──
    "Twitter / X": "Twitter / X",
    "TikTok": "TikTok",
    "Short 'about' text displayed in the footer.": "Court texte 'à propos' affiché dans le pied de page.",
    "Copyright text": "Texte de droits d'auteur",
    "Contact details": "Coordonnées",
    "Social links": "Liens sociaux",
    "footer": "pied de page",
    "footers": "pieds de page",

    # ── FAQ snippet ──
    "Platform": "Plateforme",
    "Question": "Question",
    "Answer": "Réponse",
    "Optional grouping label for the FAQ.": "Libellé de regroupement facultatif pour la FAQ.",
    "FAQ": "FAQ",
    "FAQs": "FAQ",

    # ── Testimonial snippet ──
    "Author name": "Nom de l'auteur",
    "Author role": "Rôle de l'auteur",
    "Author photo": "Photo de l'auteur",
    "Show this testimonial more prominently.": "Afficher ce témoignage de manière plus visible.",
    "testimonial": "témoignage",
    "testimonials": "témoignages",

    # ── Category snippets ──
    "Colour": "Couleur",
    "Badge/label colour (hex).": "Couleur de badge/libellé (hex).",
    "news category": "catégorie d'actualité",
    "news categories": "catégories d'actualités",
    "Motorcycle": "Moto",
    "Rally": "Rallye",
    "Meeting": "Rencontre",
    "Charity": "Caritatif",
    "Race": "Course",
    "event category": "catégorie d'événement",
    "event categories": "catégories d'événements",
    "photo tag": "tag photo",
    "photo tags": "tags photo",
    "partner category": "catégorie partenaire",
    "partner categories": "catégories partenaires",

    # ── Press release snippet ──
    "Attachment": "Pièce jointe",
    "PDF or document attachment.": "Pièce jointe PDF ou document.",
    "Archived": "Archivé",
    "press release": "communiqué de presse",
    "press releases": "communiqués de presse",

    # ── Brand asset snippet ──
    "Font": "Police",
    "Template": "Modèle",
    "Preview image": "Image de prévisualisation",
    "brand asset": "ressource de marque",
    "brand assets": "ressources de marque",

    # ── Aid skill snippet ──
    "Mechanics": "Mécanique",
    "Logistics": "Logistique",
    "Emergency": "Urgence",
    "aid skill": "compétence d'aide",
    "aid skills": "compétences d'aide",

    # ── Product snippet ──
    "Inactive products are hidden from the storefront.": "Les produits inactifs sont masqués de la vitrine.",
    "Grants voting rights": "Accorde le droit de vote",
    "Grants gallery upload": "Accorde le téléversement galerie",
    "Grants event access": "Accorde l'accès aux événements",
    "Grants discount": "Accorde une réduction",
    "Percentage discount on events when grants_discount is on.": "Réduction en pourcentage sur les événements lorsque grants_discount est activé.",
    "Product info": "Info produit",
    "Member privileges": "Privilèges membre",
    "product": "produit",

    # ── Photo upload model ──
    "Uploaded by": "Téléversé par",
    "Optionally link this photo to an event.": "Associez facultativement cette photo à un événement.",
    "Approved at": "Approuvé le",
    "Rejection reason": "Motif du rejet",
    "Uploaded at": "Téléversé le",
    "photo upload": "téléversement photo",
    "photo uploads": "téléversements photo",
    "approved": "approuvé",
    "pending": "en attente",

    # ── Verification log ──
    "Not found": "Non trouvé",
    "Wrong data": "Données erronées",
    "Expired membership": "Adhésion expirée",
    "Partner user": "Utilisateur partenaire",
    "The partner owner who performed this verification.": "Le propriétaire partenaire ayant effectué cette vérification.",
    "Which secondary factor was used for verification.": "Quel facteur secondaire a été utilisé pour la vérification.",
    "Result": "Résultat",
    "IP address": "Adresse IP",
    "verification log": "journal de vérification",
    "verification logs": "journaux de vérification",

    # ── Verification error messages ──
    "Access denied. Only partner owners and staff can verify members.": "Accès refusé. Seuls les propriétaires partenaires et le personnel peuvent vérifier les membres.",
    "Rate limit exceeded. Maximum 20 verification attempts per hour.": "Limite de requêtes dépassée. Maximum 20 tentatives de vérification par heure.",
    "Account temporarily locked. Too many failed verification attempts. Please try again in 15 minutes.": "Compte temporairement verrouillé. Trop de tentatives de vérification échouées. Veuillez réessayer dans 15 minutes.",
    "No member found with this card number.": "Aucun membre trouvé avec ce numéro de carte.",
    "This member's membership has expired.": "L'adhésion de ce membre a expiré.",
    "Member verified successfully.": "Membre vérifié avec succès.",
    "N/A": "N/D",
    "Verification failed. The provided information does not match our records.": "Vérification échouée. Les informations fournies ne correspondent pas à nos registres.",
    "Access denied. Your membership does not include gallery upload privileges.": "Accès refusé. Votre adhésion n'inclut pas les privilèges de téléversement galerie.",
    "Rejected by moderator.": "Rejeté par le modérateur.",

    # ── Membership card template ──
    "Membership Card": "Carte de Membre",
    "Card No.": "N° de Carte",
    "Expires": "Expire",
    "Barcode": "Code-barres",
    "Download PDF": "Télécharger le PDF",
    "No membership card has been issued yet. Please contact the club administration.": "Aucune carte de membre n'a encore été émise. Veuillez contacter l'administration du club.",

    # ── Member directory template ──
    "Member Directory": "Annuaire des Membres",
    "Pagination": "Pagination",
    "No members are currently visible in the directory.": "Aucun membre n'est actuellement visible dans l'annuaire.",

    # ── Auth templates ──
    "Welcome back": "Bon retour",
    "Log in to access your profile, events, and club features.": "Connectez-vous pour accéder à votre profil, vos événements et les fonctionnalités du club.",
    "Forgot your password?": "Mot de passe oublié ?",
    "Don't have an account?": "Vous n'avez pas de compte ?",
    "Are you sure you want to log out?": "Êtes-vous sûr de vouloir vous déconnecter ?",
    "Go back to home": "Retour à l'accueil",
    "Become a member": "Devenir membre",
    "Choose the membership plan that best fits your needs. Combine multiple products to customize your ex": "Choisissez le plan d'adhésion qui correspond le mieux à vos besoins. Combinez plusieurs produits pour personnaliser votre ex",
    "Your plan": "Votre plan",
    "year": "an",
    "Event registration": "Inscription aux événements",
    "Voting rights": "Droit de vote",
    "Gallery upload": "Téléversement galerie",
    "%(percent)s%% discount on events": "%(percent)s%% de réduction sur les événements",
    "Contact the club": "Contacter le club",
    "No membership plans available at this time.": "Aucun plan d'adhésion disponible pour le moment.",
    "Reset your password": "Réinitialiser votre mot de passe",
    "Enter your email address and we'll send you a link to reset your password.": "Saisissez votre adresse e-mail et nous vous enverrons un lien pour réinitialiser votre mot de passe.",
    "Send reset link": "Envoyer le lien de réinitialisation",
    "Back to login": "Retour à la connexion",
    "Active Member": "Membre Actif",
    "Back to Directory": "Retour à l'Annuaire",
    "Create your account": "Créer votre compte",
    "Join the club and access events, member directory, and more.": "Rejoignez le club et accédez aux événements, à l'annuaire des membres et plus encore.",
    "Already have an account?": "Vous avez déjà un compte ?",

    # ── Registration confirmation ──
    "Registration Confirmed": "Inscription Confirmée",

    # ── Payment pages ──
    "Amount": "Montant",
    "Bank Transfer Payment Required": "Paiement par Virement Bancaire Requis",
    "This is an automatic confirmation email. Please do not reply.": "Ceci est un e-mail de confirmation automatique. Veuillez ne pas répondre.",

    # ── Favorite events ──
    "My Favorite Events": "Mes Événements Favoris",
    "Upcoming": "À venir",
    "Archive": "Archives",
    "My Registrations": "Mes Inscriptions",
    "Events map": "Carte des événements",
    "Map view of your favorite events": "Vue carte de vos événements favoris",
    "Remove from favorites": "Retirer des favoris",
    "Download calendar file": "Télécharger le fichier calendrier",
    "ICS": "ICS",
    "You have not added any events to your favorites yet.": "Vous n'avez pas encore ajouté d'événements à vos favoris.",
    "Events Archive": "Archives des Événements",
    "No past events in your favorites.": "Aucun événement passé dans vos favoris.",

    # ── Payment flow ──
    "Payment": "Paiement",
    "Bank Transfer Instructions": "Instructions de Virement Bancaire",
    "Transfer Details": "Détails du Virement",
    "Bank": "Banque",
    "Payment Reference": "Référence de Paiement",
    "Copy": "Copier",
    "Deadline": "Date limite",
    "Back to my registrations": "Retour à mes inscriptions",
    "Your payment was not completed. You can try again using the link below.": "Votre paiement n'a pas été effectué. Vous pouvez réessayer en utilisant le lien ci-dessous.",
    "Try again": "Réessayer",
    "Choose Payment Method": "Choisir le Mode de Paiement",
    "Credit / Debit Card": "Carte de Crédit / Débit",
    "Pay securely with Stripe": "Payez en toute sécurité avec Stripe",
    "Pay with your PayPal account": "Payez avec votre compte PayPal",
    "Pay via SEPA bank transfer": "Payez par virement bancaire SEPA",
    "Payment Confirmed": "Paiement Confirmé",
    "Register for Event": "S'inscrire à l'Événement",
    "Member discount": "Réduction membre",
    "Please correct the highlighted errors below.": "Veuillez corriger les erreurs mises en évidence ci-dessous.",
    "Your Information": "Vos Informations",
    "Registration Details": "Détails de l'Inscription",
    "Registration Summary": "Résumé de l'Inscription",

    # ── Federation / Partner events ──
    "Partner Events": "Événements des Partenaires",
    "Breadcrumb": "Fil d'Ariane",
    "Club": "Club",
    "View on Google Maps": "Voir sur Google Maps",
    "View on partner site": "Voir sur le site partenaire",
    "Events from our federated partner clubs.": "Événements de nos clubs partenaires fédérés.",
    "Partner Club": "Club Partenaire",
    "All clubs": "Tous les clubs",
    "Search events...": "Rechercher des événements...",
    "No partner events found.": "Aucun événement partenaire trouvé.",
    "Clear filters": "Effacer les filtres",
    "Club Discussion": "Discussion du Club",
    "Comments are visible only to our club members. They are not shared with the partner club.": "Les commentaires sont visibles uniquement par les membres de notre club. Ils ne sont pas partagés avec le club partenaire.",
    "Delete this comment?": "Supprimer ce commentaire ?",
    "No comments yet. Be the first to start a discussion!": "Aucun commentaire pour le moment. Soyez le premier à lancer une discussion !",
    "Add a comment": "Ajouter un commentaire",
    "Share your thoughts with fellow club members...": "Partagez vos pensées avec les autres membres du club...",
    "Post Comment": "Publier le Commentaire",
    "Only active members can post comments.": "Seuls les membres actifs peuvent publier des commentaires.",
    "Are you interested?": "Êtes-vous intéressé ?",
    "going": "j'y vais",
    "interested": "intéressé",
    "maybe": "peut-être",
    "Only active members can express interest in partner events.": "Seuls les membres actifs peuvent exprimer leur intérêt pour les événements partenaires.",

    # ── Navbar template ──
    "Main navigation": "Navigation principale",
    "Toggle navigation": "Basculer la navigation",
    "Search...": "Rechercher...",
    "Search the site": "Rechercher sur le site",
    "Submit search": "Lancer la recherche",
    "Membership card": "Carte de membre",
    "My events": "Mes événements",
    "Member directory": "Annuaire des membres",

    # ── Mutual Aid access request ──
    "Request Access": "Demander l'Accès",
    "Request Access to Mutual Aid": "Demander l'Accès à l'Entraide",
    "Submit Request": "Envoyer la Demande",
    "radius": "rayon",
    "Send Request": "Envoyer la Demande",
    "Availability": "Disponibilité",
    "WhatsApp": "WhatsApp",
    "Send message": "Envoyer un message",
    "Send Aid Request": "Envoyer une Demande d'Aide",
    "Unlock Limit Reached": "Limite de Déblocage Atteinte",
    "Contact Unlock Limit Reached": "Limite de Déblocage de Contact Atteinte",
    "Please wait before unlocking more contacts, or use the contacts you have already unlocked.": "Veuillez patienter avant de débloquer d'autres contacts, ou utilisez ceux que vous avez déjà débloqués.",
    "Back to Mutual Aid": "Retour à l'Entraide",
    "Emergency Contacts": "Contacts d'Urgence",
    "Check back later or contact the club directly.": "Revenez plus tard ou contactez directement le club.",

    # ── Notification digest template ──
    "Notification digest": "Résumé des notifications",
    "View details": "Voir les détails",
    "Notification history": "Historique des notifications",
    "ago": "il y a",
    "No notifications yet.": "Aucune notification pour le moment.",
    "Unsubscribe": "Se désabonner",
    "Confirm unsubscribe": "Confirmer le désabonnement",
    "You can re-enable notifications at any time from your account settings.": "Vous pouvez réactiver les notifications à tout moment depuis les paramètres de votre compte.",
    "Invalid link": "Lien invalide",
    "Unsubscribed": "Désabonné",
    "You have been unsubscribed from these notifications. You will no longer receive them.": "Vous avez été désabonné de ces notifications. Vous ne les recevrez plus.",
    "If you change your mind, you can re-enable notifications from your": "Si vous changez d'avis, vous pouvez réactiver les notifications depuis vos",
    "account settings": "paramètres du compte",

    # ── Events filters ──
    "Event period": "Période de l'événement",
    "Past": "Passé",
    "Event filters": "Filtres d'événements",
    "Registration Open": "Inscription Ouverte",

    # ── Remaining strings (pass 3) ──
    "Contact information": "Coordonnées",
    "\\n                Page %(current)s of %(total)s\\n            ": "\\n                Page %(current)s sur %(total)s\\n            ",
    "Choose the membership plan that best fits your needs. Combine multiple products to customize your experience.": "Choisissez le plan d'adhésion qui correspond le mieux à vos besoins. Combinez plusieurs produits pour personnaliser votre expérience.",
    "Your registration for <strong>%(event_title)s</strong> has been confirmed.": "Votre inscription pour <strong>%(event_title)s</strong> a été confirmée.",
    "Please complete the bank transfer with reference <strong>%(ref)s</strong> before %(expires)s.": "Veuillez effectuer le virement bancaire avec la référence <strong>%(ref)s</strong> avant le %(expires)s.",
    "Please include the payment reference in the transfer description. Your registration will be confirmed once the payment is verified by the organiser.": "Veuillez inclure la référence de paiement dans le motif du virement. Votre inscription sera confirmée une fois le paiement vérifié par l'organisateur.",
    "As a member of a federated partner club, you can request access to our mutual aid helpers directory.": "En tant que membre d'un club partenaire fédéré, vous pouvez demander l'accès à notre annuaire d'aidants.",
    "Your request will be reviewed by our administrators. Once approved, you will be able to view and contact available helpers.": "Votre demande sera examinée par nos administrateurs. Une fois approuvée, vous pourrez voir et contacter les aidants disponibles.",
    "Sending request to:": "Envoi de la demande à :",
    "\\n                You have reached the maximum of %(limit)s contact unlocks\\n                per %(days)s-day period.\\n            ": "\\n                Vous avez atteint le maximum de %(limit)s déblocages de contact\\n                par période de %(days)s jours.\\n            ",
    "\\n    Hi %(name)s, here is your notification digest\\n    ": "\\n    Bonjour %(name)s, voici votre résumé de notifications\\n    ",
    "\\n    You have %(count)s new notification(s).\\n    ": "\\n    Vous avez %(count)s nouvelle(s) notification(s).\\n    ",
    "\\n                Page %(current)s of %(total)s\\n                ": "\\n                Page %(current)s sur %(total)s\\n                ",
    "\\n            You are about to unsubscribe <strong>%(email)s</strong> from\\n            <strong>%(type)s</strong> notifications.\\n            ": "\\n            Vous êtes sur le point de désabonner <strong>%(email)s</strong> des\\n            notifications <strong>%(type)s</strong>.\\n            ",
    "This unsubscribe link is invalid or has expired. Please check the link and try again, or manage your preferences from your account settings.": "Ce lien de désabonnement est invalide ou a expiré. Veuillez vérifier le lien et réessayer, ou gérer vos préférences depuis les paramètres de votre compte.",
    "Thank you for your message. We will get back to you shortly.": "Merci pour votre message. Nous vous répondrons dans les plus brefs délais.",
    "Please correct the errors below:": "Veuillez corriger les erreurs ci-dessous :",
    "Subject": "Objet",
    "Send Message": "Envoyer le Message",
    "Club location map": "Carte de localisation du club",
    "View larger map": "Voir une carte plus grande",
    "opens in a new window": "s'ouvre dans une nouvelle fenêtre",
    "Where to Find Us": "Comment Nous Trouver",
    "Direct Contacts": "Contacts Directs",
    "Opening Hours": "Heures d'Ouverture",
    "No events found.": "Aucun événement trouvé.",
}

if __name__ == "__main__":
    run_translation("fr", "Français", TRANSLATIONS)
