#!/usr/bin/env python3
"""
Batch-translate the German .po file for ClubCMS.
Source: English msgid → German msgstr
Cross-checked against Italian translations for consistency.
"""
from translate_engine import run_translation

# ──────────────────────────────────────────────────────────
#  TRANSLATION DICTIONARY  (English → German)
# ──────────────────────────────────────────────────────────
TRANSLATIONS = {
    # ── AppConfig verbose_name ──
    "Core": "Kern",
    "Events": "Veranstaltungen",
    "Federation": "Verband",
    "Members": "Mitglieder",
    "Mutual Aid": "Gegenseitige Hilfe",
    "Notifications": "Benachrichtigungen",
    "Website": "Webseite",

    # ── Model Meta verbose_name / verbose_name_plural ──
    "Federated Club": "Partnerclub",
    "Federated Clubs": "Partnerclubs",
    "External Event": "Externes Event",
    "External Events": "Externe Events",
    "External Event Interest": "Interesse an externem Event",
    "External Event Interests": "Interessen an externen Events",
    "External Event Comment": "Kommentar zu externem Event",
    "External Event Comments": "Kommentare zu externen Events",
    "Club User": "Club-Benutzer",
    "Club Users": "Club-Benutzer",
    "Event Registration": "Veranstaltungsanmeldung",
    "Event Registrations": "Veranstaltungsanmeldungen",
    "Event Favorite": "Event-Favorit",
    "Event Favorites": "Event-Favoriten",
    "Event page": "Veranstaltungsseite",

    # ── Events / Registration fields ──
    "Confirmed": "Bestätigt",
    "Waitlist": "Warteliste",
    "Pending": "Ausstehend",
    "Paid": "Bezahlt",
    "Refunded": "Erstattet",
    "Stripe": "Stripe",
    "PayPal": "PayPal",
    "Bank Transfer": "Banküberweisung",
    "User": "Benutzer",
    "Status": "Status",
    "Number of guests": "Anzahl der Gäste",
    "Payment status": "Zahlungsstatus",
    "Payment provider": "Zahlungsanbieter",
    "Payment ID": "Zahlungs-ID",
    "External payment reference from the provider.": "Externe Zahlungsreferenz des Anbieters.",
    "Payment session ID": "Zahlungssitzungs-ID",
    "Checkout Session ID (Stripe) or Order ID (PayPal).": "Checkout-Sitzungs-ID (Stripe) oder Auftrags-ID (PayPal).",
    "Payment amount": "Zahlungsbetrag",
    "Unique reference for bank transfers (e.g. EVT-00123-A7B3).": "Eindeutige Referenz für Banküberweisungen (z.B. EVT-00123-A7B3).",
    "Payment expires at": "Zahlung läuft ab am",
    "Deadline for bank transfer payments.": "Frist für Banküberweisungszahlungen.",
    "Guest": "Gast",
    "Days before event": "Tage vor der Veranstaltung",
    "Hours before event": "Stunden vor der Veranstaltung",
    "Minutes before event": "Minuten vor der Veranstaltung",
    "Discount percent": "Rabattprozent",
    "Label": "Bezeichnung",
    "Display label for this tier, e.g. 'Early Bird'.": "Anzeigebezeichnung für diese Stufe, z.B. 'Frühbucher'.",
    "The time offset must be greater than zero.": "Der Zeitversatz muss größer als Null sein.",
    "Added at": "Hinzugefügt am",
    "Registered": "Registriert",
    "Registered at": "Registriert am",
    "Cancelled": "Storniert",
    "Event": "Veranstaltung",
    "Payment reference": "Zahlungsreferenz",
    "Is registration deadline": "Ist Anmeldefrist",

    # ── Events notification messages ──
    "Payment expired: {event}": "Zahlung abgelaufen: {event}",
    "Your bank transfer for {event} was not received in time. Your registration has been cancelled.":
        "Ihre Banküberweisung für {event} wurde nicht rechtzeitig empfangen. Ihre Anmeldung wurde storniert.",
    "Spot available: {event}": "Platz verfügbar: {event}",
    "A spot has opened up! You have been promoted from the waitlist for {event}.":
        "Ein Platz ist frei geworden! Sie wurden von der Warteliste für {event} vorgerückt.",
    "Your membership does not include event registration. Please upgrade your membership.":
        "Ihre Mitgliedschaft beinhaltet keine Veranstaltungsanmeldung. Bitte aktualisieren Sie Ihre Mitgliedschaft.",
    "Please wait before toggling again.": "Bitte warten Sie, bevor Sie erneut umschalten.",
    "Payment instructions: {event}": "Zahlungsanweisungen: {event}",
    "Please complete the bank transfer of €{amount} with reference {ref} by {expires}.":
        "Bitte überweisen Sie €{amount} mit der Referenz {ref} bis zum {expires}.",
    "Payment service temporarily unavailable. Please try again.":
        "Zahlungsdienst vorübergehend nicht verfügbar. Bitte versuchen Sie es erneut.",

    # ── Federation model help_text ──
    "Display name of the partner club": "Anzeigename des Partnerclubs",
    "URL-safe identifier": "URL-sicherer Bezeichner",
    "Partner site base URL": "Basis-URL der Partnerseite",
    "Optional logo URL": "Optionale Logo-URL",
    "Their public API key (given to us)": "Ihr öffentlicher API-Schlüssel (an uns gegeben)",
    "Our key we gave them (auto-generated)": "Unser Schlüssel, den wir ihnen gaben (automatisch generiert)",
    "Share our events with this partner": "Unsere Veranstaltungen mit diesem Partner teilen",
    "Auto-approve imported events": "Importierte Veranstaltungen automatisch genehmigen",
    "Sanitized HTML": "Bereinigtes HTML",

    # ── Member form fields ──
    "Select member": "Mitglied auswählen",
    "Number of extra people coming with you (not counting yourself or your passenger). Example: 2":
        "Anzahl zusätzlicher Personen (ohne Sie selbst und Ihren Beifahrer). Beispiel: 2",
    "List each guest on a separate line. Example:\\nMario Rossi\\nLucia Bianchi":
        "Listen Sie jeden Gast in einer separaten Zeile auf. Beispiel:\\nMax Mustermann\\nErika Muster",
    "Allergies, dietary needs, special requests, or anything the organizers should know.":
        "Allergien, Ernährungsbedürfnisse, Sonderwünsche oder Informationen für die Veranstalter.",
    "Check this if someone will ride with you as a passenger on your motorcycle.":
        "Aktivieren Sie dies, wenn jemand als Beifahrer auf Ihrem Motorrad mitfährt.",
    "If your passenger is already a club member, enable this to select them from the list.":
        "Wenn Ihr Beifahrer bereits Clubmitglied ist, aktivieren Sie dies, um ihn aus der Liste auszuwählen.",
    "Example: Marco": "Beispiel: Max",
    "Example: Verdi": "Beispiel: Mustermann",
    "Example: marco.verdi@email.com": "Beispiel: max.mustermann@email.com",
    "Italian tax identification code, 16 characters. Example: VRDMRC85M01H501Z":
        "Italienische Steuernummer, 16 Zeichen. Beispiel: VRDMRC85M01H501Z",
    "Example: 1985-08-01": "Beispiel: 1985-08-01",
    "Name and phone number to call in case of emergency. Example: Anna Verdi +39 340 7654321":
        "Name und Telefonnummer für Notfälle. Beispiel: Anna Müller +49 170 1234567",
    "Your legal first name. Example: Maria": "Ihr offizieller Vorname. Beispiel: Maria",
    "Your family name. Example: Rossi": "Ihr Nachname. Beispiel: Müller",
    "Guest names": "Gästenamen",
    "Passenger first name": "Vorname des Beifahrers",
    "Emergency contact": "Notfallkontakt",
    "Start typing a name to search registered members.": "Beginnen Sie zu tippen, um registrierte Mitglieder zu suchen.",
    "Include country prefix. Example: +39 333 1234567": "Landesvorwahl einschließen. Beispiel: +49 170 1234567",
    "We will send your registration confirmation here.": "Wir senden Ihre Anmeldebestätigung hierher.",

    # ── Admin panels (members) ──
    "Personal": "Persönlich",
    "Identity": "Identität",
    "Address": "Adresse",
    "Membership": "Mitgliedschaft",
    "Privacy": "Datenschutz",

    # ── Member model fields ──
    "Username": "Benutzername",
    "First name": "Vorname",
    "Last name": "Nachname",
    "Email": "E-Mail",
    "Display name": "Anzeigename",
    "Phone": "Telefon",
    "Mobile": "Mobiltelefon",
    "Birth date": "Geburtsdatum",
    "Birth place": "Geburtsort",
    "Photo": "Foto",
    "Bio": "Biografie",
    "Fiscal code": "Steuernummer",
    "Document type": "Dokumenttyp",
    "Document number": "Dokumentnummer",
    "Document expiry": "Dokumentablauf",
    "City": "Stadt",
    "Province": "Provinz",
    "Postal code": "Postleitzahl",
    "Country": "Land",
    "Card number": "Kartennummer",
    "Membership date": "Mitgliedschaftsdatum",
    "Membership expiry": "Mitgliedschaftsablauf",
    "Is active": "Ist aktiv",
    "Products": "Produkte",
    "Show in directory": "Im Verzeichnis anzeigen",
    "Public profile": "Öffentliches Profil",
    "Show real name to members": "Echten Namen für Mitglieder anzeigen",
    "Newsletter": "Newsletter",
    "Email notifications": "E-Mail-Benachrichtigungen",
    "Push notifications": "Push-Benachrichtigungen",
    "News updates": "Neuigkeiten",
    "Event updates": "Veranstaltungsaktualisierungen",
    "Event reminders": "Veranstaltungserinnerungen",
    "Membership alerts": "Mitgliedschaftshinweise",
    "Partner updates": "Partneraktualisierungen",
    "Aid requests": "Hilfeanfragen",
    "Partner events": "Partnerveranstaltungen",
    "Partner event comments": "Kommentare zu Partnerveranstaltungen",
    "Digest frequency": "Zusammenfassungshäufigkeit",
    "Aid available": "Hilfe verfügbar",
    "Aid radius km": "Hilferadius (km)",
    "Aid location city": "Hilfestandort Stadt",
    "Aid coordinates": "Hilfekoordinaten",
    "Aid notes": "Hilfenotizen",

    # ── Antispam ──
    "Spam detected. Access denied.": "Spam erkannt. Zugang verweigert.",
    "This submission looks like spam.": "Diese Eingabe sieht nach Spam aus.",
    "Too many requests. Please try again later.": "Zu viele Anfragen. Bitte versuchen Sie es später erneut.",
    "Are you human?": "Sind Sie ein Mensch?",
    "Verify": "Bestätigen",
    "I am human": "Ich bin ein Mensch",
    "Verification failed. Please try again.": "Überprüfung fehlgeschlagen. Bitte versuchen Sie es erneut.",
    "Remember me": "Angemeldet bleiben",

    # ── Website / Page models ──
    "Home Page": "Startseite",
    "Content Page": "Inhaltsseite",
    "News Page": "Nachrichtenseite",
    "News Index Page": "Nachrichtenübersicht",
    "Gallery Page": "Galerieseite",
    "Gallery Index Page": "Galerieübersicht",
    "Events Index Page": "Veranstaltungsübersicht",
    "Contact Page": "Kontaktseite",
    "Title": "Titel",
    "Subtitle": "Untertitel",
    "Body": "Inhalt",
    "Image": "Bild",
    "Caption": "Bildunterschrift",
    "Author": "Autor",
    "Date": "Datum",
    "Published": "Veröffentlicht",
    "Draft": "Entwurf",
    "Summary": "Zusammenfassung",
    "Tags": "Schlagwörter",
    "Category": "Kategorie",
    "Categories": "Kategorien",
    "Slug": "Slug",
    "SEO Title": "SEO-Titel",
    "Search Description": "Suchbeschreibung",
    "Description": "Beschreibung",
    "Content": "Inhalt",
    "Location": "Ort",
    "Start date": "Startdatum",
    "End date": "Enddatum",
    "Start time": "Startzeit",
    "End time": "Endzeit",
    "All day": "Ganztägig",
    "Registration required": "Anmeldung erforderlich",
    "Max participants": "Maximale Teilnehmerzahl",
    "Price": "Preis",
    "Free": "Kostenlos",
    "Featured": "Hervorgehoben",
    "Promoted": "Beworben",
    "Featured image": "Titelbild",

    # ── StreamField blocks ──
    "Heading": "Überschrift",
    "Paragraph": "Absatz",
    "Quote": "Zitat",
    "Rich Text": "Formatierter Text",
    "Rich text": "Formatierter Text",
    "Link": "Link",
    "URL": "URL",
    "Button": "Schaltfläche",
    "Button text": "Schaltflächentext",
    "Button link": "Schaltflächenlink",
    "Call to Action": "Handlungsaufforderung",
    "Background color": "Hintergrundfarbe",
    "Background image": "Hintergrundbild",
    "Text color": "Textfarbe",
    "Alignment": "Ausrichtung",
    "Left": "Links",
    "Center": "Mitte",
    "Right": "Rechts",
    "Full width": "Volle Breite",
    "Card": "Karte",
    "Cards": "Karten",
    "Column": "Spalte",
    "Columns": "Spalten",
    "Section": "Abschnitt",
    "Hero": "Hero",
    "Hero section": "Hero-Bereich",
    "Embed": "Einbettung",
    "Embed URL": "Einbettungs-URL",
    "Video": "Video",
    "Document": "Dokument",
    "Documents": "Dokumente",
    "File": "Datei",
    "Download": "Herunterladen",
    "Gallery": "Galerie",
    "Slider": "Slider",
    "Testimonial": "Referenz",
    "Testimonials": "Referenzen",
    "Icon": "Symbol",
    "Feature": "Funktion",
    "Features": "Funktionen",
    "Table": "Tabelle",
    "Map": "Karte",
    "Code": "Code",
    "Accordion": "Akkordeon",
    "Tab": "Tab",
    "Tabs": "Tabs",
    "Spacer": "Abstandhalter",
    "Divider": "Trennlinie",
    "HTML": "HTML",
    "Raw HTML": "Rohes HTML",

    # ── Wagtail / Settings ──
    "Site Settings": "Seiteneinstellungen",
    "Site settings": "Seiteneinstellungen",
    "Site Name": "Seitenname",
    "Site name": "Seitenname",
    "Tagline": "Slogan",
    "Logo": "Logo",
    "Favicon": "Favicon",
    "Social Media": "Soziale Medien",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "Twitter": "Twitter",
    "YouTube": "YouTube",
    "LinkedIn": "LinkedIn",
    "Footer": "Fußzeile",
    "Footer text": "Fußzeilentext",
    "Copyright": "Urheberrecht",
    "Analytics": "Analytik",
    "Google Analytics ID": "Google Analytics-ID",
    "Theme": "Design",
    "Color scheme": "Farbschema",
    "Primary color": "Primärfarbe",
    "Secondary color": "Sekundärfarbe",
    "Accent color": "Akzentfarbe",
    "Dark mode": "Dunkelmodus",
    "Light mode": "Hellmodus",
    "Auto": "Automatisch",

    # ── Notifications ──
    "Notification": "Benachrichtigung",
    "Notification Type": "Benachrichtigungstyp",
    "Notification type": "Benachrichtigungstyp",
    "Message": "Nachricht",
    "Read": "Gelesen",
    "Unread": "Ungelesen",
    "Sent": "Gesendet",
    "Mark as read": "Als gelesen markieren",
    "Mark all as read": "Alle als gelesen markieren",
    "Delete": "Löschen",
    "No notifications": "Keine Benachrichtigungen",
    "Notification Settings": "Benachrichtigungseinstellungen",
    "Notification settings": "Benachrichtigungseinstellungen",
    "Enable email notifications": "E-Mail-Benachrichtigungen aktivieren",
    "Enable push notifications": "Push-Benachrichtigungen aktivieren",
    "Notification Preference": "Benachrichtigungspräferenz",
    "Notification Preferences": "Benachrichtigungspräferenzen",
    "Channel": "Kanal",
    "Channels": "Kanäle",

    # ── Mutual Aid ──
    "Aid Request": "Hilfeanfrage",
    "Aid Requests": "Hilfeanfragen",
    "Aid Offer": "Hilfsangebot",
    "Aid Offers": "Hilfsangebote",
    "Aid Category": "Hilfekategorie",
    "Aid Categories": "Hilfekategorien",
    "Urgency": "Dringlichkeit",
    "Low": "Niedrig",
    "Medium": "Mittel",
    "High": "Hoch",
    "Critical": "Kritisch",
    "Open": "Offen",
    "Closed": "Geschlossen",
    "In Progress": "In Bearbeitung",
    "Resolved": "Gelöst",
    "Latitude": "Breitengrad",
    "Longitude": "Längengrad",
    "Radius": "Radius",
    "Available": "Verfügbar",
    "Unavailable": "Nicht verfügbar",
    "Skills": "Fähigkeiten",
    "Equipment": "Ausrüstung",
    "Notes": "Notizen",
    "Active": "Aktiv",
    "Inactive": "Inaktiv",
    "Expires at": "Läuft ab am",
    "Created at": "Erstellt am",
    "Updated at": "Aktualisiert am",
    "Created by": "Erstellt von",

    # ── Common actions / UI ──
    "Save": "Speichern",
    "Cancel": "Abbrechen",
    "Edit": "Bearbeiten",
    "Add": "Hinzufügen",
    "Remove": "Entfernen",
    "Search": "Suchen",
    "Filter": "Filtern",
    "Sort": "Sortieren",
    "View": "Ansehen",
    "Details": "Details",
    "Back": "Zurück",
    "Next": "Weiter",
    "Previous": "Vorherige",
    "Submit": "Absenden",
    "Confirm": "Bestätigen",
    "Close": "Schließen",
    "Update": "Aktualisieren",
    "Yes": "Ja",
    "No": "Nein",
    "None": "Keine",
    "All": "Alle",
    "Name": "Name",
    "Type": "Typ",
    "Actions": "Aktionen",
    "Loading...": "Laden...",
    "Error": "Fehler",
    "Success": "Erfolg",
    "Warning": "Warnung",
    "Info": "Info",

    # ── Wagtail snippets ──
    "Snippet": "Snippet",
    "Snippets": "Snippets",
    "Menu item": "Menüeintrag",
    "Menu items": "Menüeinträge",
    "Navigation": "Navigation",
    "External link": "Externer Link",
    "Internal link": "Interner Link",
    "Page": "Seite",
    "Pages": "Seiten",
    "Parent page": "Übergeordnete Seite",
    "Order": "Reihenfolge",
    "Sort order": "Sortierreihenfolge",
    "Show in menu": "Im Menü anzeigen",

    # ── Uploads / Gallery ──
    "Upload": "Hochladen",
    "Uploads": "Uploads",
    "Album": "Album",
    "Albums": "Alben",
    "Upload date": "Hochladedatum",
    "File size": "Dateigröße",
    "File type": "Dateityp",
    "Width": "Breite",
    "Height": "Höhe",
    "Alt text": "Alternativtext",
    "Thumbnail": "Vorschau",

    # ── Partners ──
    "Partner": "Partner",
    "Partners": "Partner",
    "Partner Category": "Partnerkategorie",
    "Partner Categories": "Partnerkategorien",
    "Discount": "Rabatt",
    "Benefit": "Vorteil",
    "Benefits": "Vorteile",
    "Valid from": "Gültig ab",
    "Valid until": "Gültig bis",
    "Terms and conditions": "Allgemeine Geschäftsbedingungen",

    # ── Press Office ──
    "Press Release": "Pressemitteilung",
    "Press Releases": "Pressemitteilungen",

    # ── Registration form ──
    "Registration": "Registrierung",
    "Register": "Registrieren",
    "Login": "Anmelden",
    "Logout": "Abmelden",
    "Sign up": "Registrieren",
    "Sign in": "Anmelden",
    "Password": "Passwort",
    "Confirm password": "Passwort bestätigen",
    "Forgot password?": "Passwort vergessen?",
    "Reset password": "Passwort zurücksetzen",
    "Change password": "Passwort ändern",
    "Account": "Konto",
    "Profile": "Profil",
    "Settings": "Einstellungen",
    "Preferences": "Präferenzen",

    # ── Event-specific ──
    "Upcoming events": "Kommende Veranstaltungen",
    "Past events": "Vergangene Veranstaltungen",
    "No upcoming events": "Keine kommenden Veranstaltungen",
    "Event details": "Veranstaltungsdetails",
    "Register for event": "Zur Veranstaltung anmelden",
    "Cancel registration": "Anmeldung stornieren",
    "Registration closed": "Anmeldung geschlossen",
    "Event full": "Veranstaltung ausgebucht",
    "Spots available": "Plätze verfügbar",
    "Organizer": "Veranstalter",
    "Route": "Route",
    "Route map": "Routenkarte",
    "Distance": "Entfernung",
    "Difficulty": "Schwierigkeit",
    "Easy": "Einfach",
    "Moderate": "Mittel",
    "Hard": "Schwer",
    "Expert": "Experte",
    "GPX file": "GPX-Datei",
    "Route description": "Routenbeschreibung",
    "Waypoints": "Wegpunkte",
    "Departure": "Abfahrt",
    "Arrival": "Ankunft",
    "Duration": "Dauer",

    # ── Verification / Moderation ──
    "Verified": "Verifiziert",
    "Not verified": "Nicht verifiziert",
    "Verification": "Verifizierung",
    "Verification code": "Verifizierungscode",
    "Verification token": "Verifizierungstoken",
    "Approved": "Genehmigt",
    "Rejected": "Abgelehnt",
    "Pending review": "Überprüfung ausstehend",
    "Moderation": "Moderation",
    "Report": "Melden",
    "Reported": "Gemeldet",
    "Ban": "Sperren",
    "Banned": "Gesperrt",

    # ── Interest / Comment ──
    "Interested": "Interessiert",
    "Maybe": "Vielleicht",
    "Going": "Teilnehmen",
    "Interest level": "Interessensgrad",
    "Comment": "Kommentar",
    "Comments": "Kommentare",
    "Add comment": "Kommentar hinzufügen",
    "Edit comment": "Kommentar bearbeiten",
    "Delete comment": "Kommentar löschen",
    "Reply": "Antworten",

    # ── Sync / Federation ──
    "Last sync": "Letzte Synchronisierung",
    "Last error": "Letzter Fehler",
    "Is approved": "Ist genehmigt",
    "Source club": "Quellclub",
    "External ID": "Externe ID",
    "Event name": "Veranstaltungsname",
    "Location name": "Ortsname",
    "Location address": "Ortsadresse",
    "Event status": "Veranstaltungsstatus",
    "Image URL": "Bild-URL",
    "Detail URL": "Detail-URL",
    "Is hidden": "Ist verborgen",
    "Fetched at": "Abgerufen am",
    "Short code": "Kurzcode",
    "Base URL": "Basis-URL",
    "Logo URL": "Logo-URL",
    "API key": "API-Schlüssel",

    # ── Misc field labels ──
    "Scheduled": "Geplant",
    "Moved Online": "Online verlegt",
    "Postponed": "Verschoben",
    "EventScheduled": "Geplant",
    "EventCancelled": "Abgesagt",
    "EventPostponed": "Verschoben",
    "EventMovedOnline": "Online verlegt",
    "True": "Wahr",
    "False": "Falsch",
    "Enabled": "Aktiviert",
    "Disabled": "Deaktiviert",

    # ── SEO / JSON-LD ──
    "Structured data": "Strukturierte Daten",
    "Schema type": "Schematyp",
    "JSON-LD": "JSON-LD",
    "Open Graph": "Open Graph",
    "Twitter Card": "Twitter Card",
    "Canonical URL": "Kanonische URL",
    "Robots": "Robots",
    "Sitemap": "Sitemap",
    "sitemap.xml": "sitemap.xml",

    # ── Wagtail admin ──
    "Dashboard": "Dashboard",
    "Explorer": "Erkunden",
    "Images": "Bilder",
    "Search terms": "Suchbegriffe",
    "Search promotions": "Suchaktionen",
    "Redirects": "Weiterleitungen",
    "Users": "Benutzer",
    "Groups": "Gruppen",
    "Sites": "Webseiten",
    "Collections": "Sammlungen",
    "Workflows": "Arbeitsabläufe",
    "Tasks": "Aufgaben",
    "Locked pages": "Gesperrte Seiten",
    "Aging pages": "Veraltete Seiten",
    "Reports": "Berichte",

    # ── i18n / locale ──
    "Language": "Sprache",
    "English": "Englisch",
    "Italian": "Italienisch",
    "French": "Französisch",
    "German": "Deutsch",
    "Spanish": "Spanisch",
    "Select language": "Sprache auswählen",

    # ── Form validations ──
    "This field is required.": "Dieses Feld ist erforderlich.",
    "Enter a valid email address.": "Geben Sie eine gültige E-Mail-Adresse ein.",
    "Enter a valid URL.": "Geben Sie eine gültige URL ein.",
    "Enter a valid value.": "Geben Sie einen gültigen Wert ein.",
    "Ensure this value is greater than or equal to %(limit_value)s.": "Stellen Sie sicher, dass dieser Wert größer oder gleich %(limit_value)s ist.",
    "Ensure this value is less than or equal to %(limit_value)s.": "Stellen Sie sicher, dass dieser Wert kleiner oder gleich %(limit_value)s ist.",

    # ── Privacy / GDPR ──
    "I accept the <a href='/privacy/' target='_blank' rel='noopener'>terms and conditions</a>":
        "Ich akzeptiere die <a href='/privacy/' target='_blank' rel='noopener'>Allgemeinen Geschäftsbedingungen</a>",

    # ── Color Scheme choices ──
    "light": "hell",
    "dark": "dunkel",
    "auto": "automatisch",
    "Light": "Hell",
    "Dark": "Dunkel",

    # ── PWA / Push ──
    "Install app": "App installieren",
    "Subscribe to notifications": "Benachrichtigungen abonnieren",
    "Unsubscribe from notifications": "Benachrichtigungen abbestellen",
    "Offline": "Offline",
    "Online": "Online",
    "Update available": "Aktualisierung verfügbar",
    "Refresh": "Aktualisieren",

    # ── Contribution / Moderation ──
    "Contribution": "Beitrag",
    "Contributions": "Beiträge",
    "Contributor": "Mitwirkender",
    "Contributors": "Mitwirkende",
    "Suggestion": "Vorschlag",
    "Suggestions": "Vorschläge",
    "Pending approval": "Genehmigung ausstehend",

    # ── Time-related ──
    "Today": "Heute",
    "Tomorrow": "Morgen",
    "Yesterday": "Gestern",
    "This week": "Diese Woche",
    "Next week": "Nächste Woche",
    "This month": "Dieser Monat",
    "Next month": "Nächster Monat",
    "Daily": "Täglich",
    "Weekly": "Wöchentlich",
    "Monthly": "Monatlich",
    "Never": "Nie",

    # ── Product / membership tiers ──
    "Product": "Produkt",
    "Product name": "Produktname",
    "Product type": "Produkttyp",
    "Includes event registration": "Beinhaltet Veranstaltungsanmeldung",
    "Annual": "Jährlich",

    # ── Email subjects / messages ──
    "Welcome": "Willkommen",
    "Goodbye": "Auf Wiedersehen",
    "Thank you": "Vielen Dank",
    "Confirmation": "Bestätigung",
    "Reminder": "Erinnerung",
    "Alert": "Warnung",
    "Important": "Wichtig",
    "New": "Neu",

    # ── Common model field names as verbose_name ──
    "address": "Adresse",
    "city": "Stadt",
    "province": "Provinz",
    "postal code": "Postleitzahl",
    "country": "Land",
    "phone": "Telefon",
    "mobile": "Mobiltelefon",
    "email": "E-Mail",
    "first name": "Vorname",
    "last name": "Nachname",
    "display name": "Anzeigename",
    "birth date": "Geburtsdatum",
    "birth place": "Geburtsort",
    "photo": "Foto",
    "bio": "Biografie",
    "fiscal code": "Steuernummer",
    "document type": "Dokumenttyp",
    "document number": "Dokumentnummer",
    "document expiry": "Dokumentablauf",
    "card number": "Kartennummer",
    "membership date": "Mitgliedschaftsdatum",
    "membership expiry": "Mitgliedschaftsablauf",
    "is active": "ist aktiv",
    "show in directory": "im Verzeichnis anzeigen",
    "public profile": "öffentliches Profil",
    "show real name to members": "echten Namen für Mitglieder anzeigen",
    "newsletter": "Newsletter",
    "email notifications": "E-Mail-Benachrichtigungen",
    "push notifications": "Push-Benachrichtigungen",
    "news updates": "Neuigkeiten",
    "event updates": "Veranstaltungsaktualisierungen",
    "event reminders": "Veranstaltungserinnerungen",
    "membership alerts": "Mitgliedschaftshinweise",
    "partner updates": "Partneraktualisierungen",
    "aid requests": "Hilfeanfragen",
    "partner events": "Partnerveranstaltungen",
    "partner event comments": "Kommentare zu Partnerveranstaltungen",
    "digest frequency": "Zusammenfassungshäufigkeit",
    "aid available": "Hilfe verfügbar",
    "aid radius km": "Hilferadius (km)",
    "aid location city": "Hilfestandort Stadt",
    "aid coordinates": "Hilfekoordinaten",
    "aid notes": "Hilfenotizen",
    "products": "Produkte",

    # ── mutual_aid model strings ──
    "request": "Anfrage",
    "offer": "Angebot",
    "Roadside assistance": "Pannenhilfe",
    "Mechanical help": "Mechanische Hilfe",
    "Transport": "Transport",
    "Accommodation": "Unterkunft",
    "Medical": "Medizinisch",
    "Other": "Sonstiges",
    "other": "sonstiges",
    "Description of the problem or assistance needed": "Beschreibung des Problems oder der benötigten Hilfe",
    "Title of the aid request": "Titel der Hilfeanfrage",
    "Aid request": "Hilfeanfrage",
    "Aid offer": "Hilfsangebot",
    "Responder": "Helfer",
    "Requester": "Antragsteller",
    "Response": "Antwort",
    "Responses": "Antworten",
    "Aid Response": "Hilfsantwort",
    "Aid Responses": "Hilfsantworten",
    "Response message": "Antwortnachricht",
    "Estimated arrival": "Geschätzte Ankunft",
    "Can help": "Kann helfen",
    "On the way": "Unterwegs",
    "Arrived": "Angekommen",
    "Completed": "Abgeschlossen",
    "Did not show": "Nicht erschienen",

    # ── Notification types ──
    "event_registration": "veranstaltungsanmeldung",
    "event_reminder": "veranstaltungserinnerung",
    "event_update": "veranstaltungsaktualisierung",
    "membership_expiry": "mitgliedschaftsablauf",
    "aid_request": "hilfeanfrage",
    "aid_response": "hilfsantwort",
    "partner_event": "partnerveranstaltung",
    "system": "System",
    "general": "Allgemein",
    "email": "E-Mail",
    "push": "Push",
    "in_app": "in_app",
    "both": "beide",

    # ── Additional form/template strings ──
    "Are you sure?": "Sind Sie sicher?",
    "This action cannot be undone.": "Diese Aktion kann nicht rückgängig gemacht werden.",
    "No results found.": "Keine Ergebnisse gefunden.",
    "Showing %(start)s to %(end)s of %(total)s results": "Zeige %(start)s bis %(end)s von %(total)s Ergebnissen",
    "Page %(current)s of %(total)s": "Seite %(current)s von %(total)s",
    "Items per page": "Elemente pro Seite",
    "Apply": "Anwenden",
    "Reset": "Zurücksetzen",
    "Clear": "Leeren",
    "Select all": "Alle auswählen",
    "Deselect all": "Alle abwählen",
    "Export": "Exportieren",
    "Import": "Importieren",
    "CSV": "CSV",
    "PDF": "PDF",
    "Print": "Drucken",

    # ── Registration flow ──
    "Passenger": "Beifahrer",
    "Has passenger": "Hat Beifahrer",
    "Passenger is member": "Beifahrer ist Mitglied",
    "Passenger name": "Name des Beifahrers",
    "Number of extra guests": "Anzahl zusätzlicher Gäste",
    "Special requests": "Sonderwünsche",
    "Total": "Gesamt",
    "Subtotal": "Zwischensumme",
    "Tax": "Steuer",
    "Registration date": "Anmeldedatum",
    "Registration status": "Anmeldestatus",
    "Confirm registration": "Anmeldung bestätigen",
    "cancel": "abbrechen",
    "Extra content": "Zusätzlicher Inhalt",

    # ── More website model strings ──
    "Hero image": "Hero-Bild",
    "Intro": "Einleitung",
    "intro": "Einleitung",
    "Related pages": "Verwandte Seiten",
    "Related links": "Verwandte Links",
    "Sidebar": "Seitenleiste",
    "Header": "Kopfzeile",
    "Main content": "Hauptinhalt",
    "Call to action": "Handlungsaufforderung",
    "call to action": "Handlungsaufforderung",
    "Banner": "Banner",
    "Promo": "Werbung",
    "Highlight": "Hervorhebung",
    "Text": "Text",
    "text": "Text",
    "Block type": "Blocktyp",

    # ── Error messages ──
    "An error occurred.": "Ein Fehler ist aufgetreten.",
    "Permission denied.": "Zugriff verweigert.",
    "Not found.": "Nicht gefunden.",
    "Page not found": "Seite nicht gefunden",
    "Server error": "Serverfehler",
    "Bad request": "Ungültige Anfrage",
    "Forbidden": "Verboten",
    "Unauthorized": "Nicht autorisiert",
    "Service unavailable": "Dienst nicht verfügbar",

    # ── Pricing tiers ──
    "Early Bird": "Frühbucher",
    "Regular": "Regulär",
    "Late": "Nachzügler",
    "VIP": "VIP",
    "Standard": "Standard",
    "Premium": "Premium",
    "Basic": "Basis",

    # ── Additional wagtail/website fields ──
    "Published date": "Veröffentlichungsdatum",
    "Publish date": "Veröffentlichungsdatum",
    "Expire date": "Ablaufdatum",
    "Go live date": "Veröffentlichungsdatum",
    "First published at": "Erstveröffentlichung",
    "Last published at": "Letzte Veröffentlichung",
    "Latest revision created at": "Letzte Überarbeitung erstellt am",
    "Live": "Veröffentlicht",
    "Has unpublished changes": "Hat unveröffentlichte Änderungen",
    "Locked": "Gesperrt",
    "Locked by": "Gesperrt von",
    "Locked at": "Gesperrt am",

    # ── Menu/admin strings Wagtail ──
    "Menu label": "Menübezeichnung",
    "Admin display title": "Admin-Anzeigetitel",

    # ── Additional mutual aid ──
    "Accept": "Annehmen",
    "Reject": "Ablehnen",
    "Withdraw": "Zurückziehen",
    "Confirm arrival": "Ankunft bestätigen",
    "Mark as resolved": "Als gelöst markieren",
    "Request help": "Hilfe anfordern",
    "Offer help": "Hilfe anbieten",
    "Your location": "Ihr Standort",
    "Distance from you": "Entfernung von Ihnen",
    "km": "km",

    # ── Additional notification messages ──
    "You have %(count)s new notifications": "Sie haben %(count)s neue Benachrichtigungen",
    "No new notifications": "Keine neuen Benachrichtigungen",
    "View all notifications": "Alle Benachrichtigungen anzeigen",
    "Notification sent": "Benachrichtigung gesendet",
    "Notification deleted": "Benachrichtigung gelöscht",

    # ── Choices for document_type ──
    "ID Card": "Personalausweis",
    "Passport": "Reisepass",
    "Driving License": "Führerschein",

    # ── Additional registration ──
    "Check-in": "Check-in",
    "Checked in": "Eingecheckt",
    "Not checked in": "Nicht eingecheckt",
    "QR Code": "QR-Code",
    "Scan QR code": "QR-Code scannen",

    # ── Additional patterns ──
    "per year": "pro Jahr",
    "per month": "pro Monat",
    "valid": "gültig",
    "invalid": "ungültig",
    "required": "erforderlich",
    "optional": "optional",
    "default": "Standard",
    "custom": "benutzerdefiniert",
    "public": "öffentlich",
    "private": "privat",
    "visible": "sichtbar",
    "hidden": "verborgen",
    "enabled": "aktiviert",
    "disabled": "deaktiviert",

    # ══════════════════════════════════════════════════════
    #  PASS 2 — remaining strings
    # ══════════════════════════════════════════════════════

    # ── Membership card / QR ──
    "No membership card available.": "Keine Mitgliedskarte verfügbar.",
    "QR code generation not available.": "QR-Code-Generierung nicht verfügbar.",
    "Barcode generation not available.": "Barcode-Generierung nicht verfügbar.",
    "Your name": "Ihr Name",
    "Phone number": "Telefonnummer",
    "Email address": "E-Mail-Adresse",
    "Your current location": "Ihr aktueller Standort",
    "Description must be 5000 characters or fewer.": "Die Beschreibung darf maximal 5000 Zeichen enthalten.",
    "Why do you need access? (optional)": "Warum benötigen Sie Zugang? (optional)",
    "Role": "Rolle",
    "Emergency Contact": "Notfallkontakt",
    "Introduction": "Einleitung",
    "Emergency contacts": "Notfallkontakte",
    "Default map radius (km)": "Standard-Kartenradius (km)",
    "Enable federation": "Verband aktivieren",

    # ── Mutual Aid Pages ──
    "Mutual Aid Page": "Seite Gegenseitige Hilfe",
    "Mutual Aid Pages": "Seiten Gegenseitige Hilfe",
    "Show phone number": "Telefonnummer anzeigen",
    "Show mobile number": "Mobilnummer anzeigen",
    "Show WhatsApp availability": "WhatsApp-Verfügbarkeit anzeigen",
    "Show email address": "E-Mail-Adresse anzeigen",
    "Show exact location": "Genauen Standort anzeigen",
    "If disabled, only the city name is shown.": "Wenn deaktiviert, wird nur der Stadtname angezeigt.",
    "Show profile photo": "Profilfoto anzeigen",
    "Show bio": "Biografie anzeigen",
    "Show availability hours": "Verfügbarkeitszeiten anzeigen",
    "Aid Privacy Settings": "Hilfe-Datenschutzeinstellungen",

    # ── Urgency levels ──
    "Low - can wait": "Niedrig - kann warten",
    "Medium - within a day": "Mittel - innerhalb eines Tages",
    "High - urgent": "Hoch - dringend",
    "Emergency - immediate": "Notfall - sofort",
    "Accepted": "Akzeptiert",
    "In progress": "In Bearbeitung",

    # ── Aid issue types ──
    "Breakdown": "Panne",
    "Flat tire": "Reifenpanne",
    "Out of fuel": "Kein Kraftstoff",
    "Accident": "Unfall",
    "Need towing": "Abschleppdienst benötigt",
    "Need tools": "Werkzeug benötigt",
    "Need transport": "Transport benötigt",
    "Need accommodation": "Unterkunft benötigt",
    "Helper": "Helfer",
    "Requester name": "Name des Antragstellers",
    "Requester phone": "Telefon des Antragstellers",
    "Requester email": "E-Mail des Antragstellers",
    "Requester (if member)": "Antragsteller (wenn Mitglied)",
    "Issue type": "Problemtyp",
    "Where are you? Address or coordinates.": "Wo befinden Sie sich? Adresse oder Koordinaten.",

    # ── Federation access ──
    "From federation": "Vom Verband",
    "Federation access": "Verbandszugang",
    "Can contact helpers": "Kann Helfer kontaktieren",
    "External user ID": "Externe Benutzer-ID",
    "External display name": "Externer Anzeigename",
    "Contacts unlocked": "Kontakte freigeschaltet",
    "Access level": "Zugangsstufe",
    "Approved by": "Genehmigt von",
    "Federated Aid Access": "Verbands-Hilfezugang",
    "Federated Aid Access Grants": "Verbands-Hilfezugangsberechtigungen",
    "Denied": "Verweigert",
    "Federated access": "Verbandszugang",
    "Why are you requesting access?": "Warum beantragen Sie Zugang?",
    "Reviewed by": "Überprüft von",
    "Reviewed at": "Überprüft am",
    "Federated Aid Access Request": "Verbands-Hilfezugangsantrag",
    "Federated Aid Access Requests": "Verbands-Hilfezugangsanträge",
    "Contact Unlock": "Kontaktfreischaltung",
    "Contact Unlocks": "Kontaktfreischaltungen",
    "Active membership required.": "Aktive Mitgliedschaft erforderlich.",

    # ── Notification types ──
    "News published": "Nachricht veröffentlicht",
    "Event published": "Veranstaltung veröffentlicht",
    "Event reminder": "Veranstaltungserinnerung",
    "Weekend favorites": "Wochenend-Favoriten",
    "Registration opens": "Anmeldung öffnet",
    "Photo approved": "Foto genehmigt",
    "Membership expiring": "Mitgliedschaft läuft ab",
    "Partner news": "Partnernachrichten",
    "Partner event interest": "Partnerveranstaltungs-Interesse",
    "Partner event comment": "Partnerveranstaltungs-Kommentar",
    "Partner event cancelled": "Partnerveranstaltung abgesagt",
    "Mutual aid request": "Gegenseitige Hilfeanfrage",
    "Mutual aid access request": "Antrag auf Zugang zur gegenseitigen Hilfe",
    "Payment instructions": "Zahlungsanweisungen",
    "Payment confirmed": "Zahlung bestätigt",
    "Payment expired": "Zahlung abgelaufen",
    "Registration cancelled": "Anmeldung storniert",
    "Promoted from waitlist": "Von der Warteliste vorgerückt",
    "Push notification": "Push-Benachrichtigung",
    "In-app notification": "In-App-Benachrichtigung",
    "Failed": "Fehlgeschlagen",
    "Skipped": "Übersprungen",

    # ── Notification model fields (lowercase) ──
    "notification type": "Benachrichtigungstyp",
    "content type": "Inhaltstyp",
    "object ID": "Objekt-ID",
    "recipient": "Empfänger",
    "channel": "Kanal",
    "status": "Status",
    "title": "Titel",
    "body": "Inhalt",
    "scheduled for": "geplant für",
    "If set, notification will not be sent before this time.": "Wenn gesetzt, wird die Benachrichtigung nicht vor diesem Zeitpunkt gesendet.",
    "sent at": "gesendet am",
    "created at": "erstellt am",
    "error message": "Fehlermeldung",
    "notification": "Benachrichtigung",
    "notifications": "Benachrichtigungen",

    # ── Push subscriptions ──
    "user": "Benutzer",
    "endpoint": "Endpunkt",
    "Push service URL": "Push-Dienst-URL",
    "p256dh key": "p256dh-Schlüssel",
    "Client public encryption key": "Öffentlicher Verschlüsselungsschlüssel des Clients",
    "auth key": "Authentifizierungsschlüssel",
    "Client auth secret": "Client-Authentifizierungsgeheimnis",
    "active": "aktiv",
    "last used": "zuletzt verwendet",
    "user agent": "User-Agent",
    "push subscription": "Push-Abonnement",
    "push subscriptions": "Push-Abonnements",
    "token": "Token",
    "unsubscribe token": "Abmeldetoken",
    "unsubscribe tokens": "Abmeldetokens",
    "Invalid JSON body": "Ungültiger JSON-Inhalt",
    "Endpoint is required": "Endpunkt ist erforderlich",
    "Endpoint must use HTTPS": "Endpunkt muss HTTPS verwenden",
    "Encryption keys are required": "Verschlüsselungsschlüssel sind erforderlich",

    # ── StreamField blocks – gallery/media ──
    "Article gallery": "Artikelgalerie",
    "Event gallery": "Veranstaltungsgalerie",
    "Event location map": "Veranstaltungsort-Karte",
    "Card thumbnail image.": "Karten-Vorschaubild.",
    "Optional badge text (e.g. date, category label).": "Optionaler Badge-Text (z.B. Datum, Kategorielabel).",
    "Card title.": "Kartentitel.",
    "Short description text.": "Kurzer Beschreibungstext.",
    "Link to page": "Link zur Seite",
    "External URL": "Externe URL",
    "Used only if no internal page is selected.": "Wird nur verwendet, wenn keine interne Seite ausgewählt ist.",
    "Button / link label.": "Schaltflächen-/Linklabel.",
    "Optional section title above the grid.": "Optionaler Abschnittstitel über dem Raster.",
    "2 columns": "2 Spalten",
    "3 columns": "3 Spalten",
    "4 columns": "4 Spalten",
    "Number of columns on desktop.": "Anzahl der Spalten auf dem Desktop.",
    "Default": "Standard",
    "Outlined": "Umrandet",
    "Elevated / shadow": "Erhöht / Schatten",
    "Minimal": "Minimal",
    "Visual style for the cards.": "Visueller Stil für die Karten.",
    "Cards grid": "Kartenraster",

    # ── CTA block ──
    "CTA headline.": "CTA-Überschrift.",
    "Supporting text.": "Unterstützender Text.",
    "Button label.": "Schaltflächenlabel.",
    "Button page link": "Schaltflächen-Seitenlink",
    "Button external URL": "Schaltflächen-externe URL",
    "Primary colour": "Primärfarbe",
    "Gradient": "Farbverlauf",
    "Image background": "Bildhintergrund",
    "Background style for this section.": "Hintergrundstil für diesen Abschnitt.",
    "Background image (only used with 'Image background' style).": "Hintergrundbild (wird nur mit dem Stil 'Bildhintergrund' verwendet).",

    # ── Statistics block ──
    "The numeric value or short text (e.g. '1500+').": "Der numerische Wert oder Kurztext (z.B. '1500+').",
    "Description of the stat (e.g. 'Members').": "Beschreibung der Statistik (z.B. 'Mitglieder').",
    "Optional icon class name.": "Optionaler Symbol-Klassenname.",
    "Statistic": "Statistik",
    "Optional section title.": "Optionaler Abschnittstitel.",
    "Statistics": "Statistiken",

    # ── Testimonial / Quote block ──
    "The quote text.": "Der Zitattext.",
    "Name of the person quoted.": "Name der zitierten Person.",
    "Role or title of the author (e.g. 'President').": "Rolle oder Titel des Autors (z.B. 'Präsident').",
    "Optional portrait of the author.": "Optionales Porträt des Autors.",

    # ── Timeline block ──
    "Year or date label (e.g. '2015').": "Jahr oder Datumslabel (z.B. '2015').",
    "Event or milestone title.": "Veranstaltungs- oder Meilensteintitel.",
    "Detailed description of this event.": "Detaillierte Beschreibung dieser Veranstaltung.",
    "Timeline entry": "Zeitleisteneintrag",
    "Timeline entries": "Zeitleisteneinträge",
    "Timeline": "Zeitleiste",

    # ── Team block ──
    "Position or title.": "Position oder Titel.",
    "Short biography.": "Kurze Biografie.",
    "Team member": "Teammitglied",
    "Optional section title (e.g. 'Board of Directors').": "Optionaler Abschnittstitel (z.B. 'Vorstand').",
    "Team members": "Teammitglieder",
    "Team grid": "Team-Raster",

    # ── Newsletter block ──
    "Stay updated": "Bleiben Sie informiert",
    "Form heading.": "Formularüberschrift.",
    "Short text explaining what subscribers will receive.": "Kurzer Text, der erklärt, was Abonnenten erhalten.",
    "Subscribe": "Abonnieren",
    "Newsletter signup": "Newsletter-Anmeldung",

    # ── Alert block ──
    "Alert message content.": "Inhalt der Warnmeldung.",
    "Danger": "Gefahr",
    "Visual style and severity of the alert.": "Visueller Stil und Schweregrad der Warnung.",
    "Allow users to dismiss this alert.": "Benutzern erlauben, diese Warnung zu schließen.",

    # ── Slider / Hero slider ──
    "Slide background image.": "Slide-Hintergrundbild.",
    "Slide headline.": "Slide-Überschrift.",
    "Optional subtitle text.": "Optionaler Untertiteltext.",
    "CTA text": "CTA-Text",
    "CTA page link": "CTA-Seitenlink",
    "CTA external URL": "CTA-externe URL",
    "Slide": "Slide",
    "Slides": "Slides",
    "Automatically advance slides.": "Slides automatisch weiterschalten.",
    "Time between slides in milliseconds.": "Zeit zwischen Slides in Millisekunden.",
    "Half screen": "Halber Bildschirm",
    "Three-quarter screen": "Dreiviertel-Bildschirm",
    "Full screen": "Vollbild",
    "Slider height.": "Slider-Höhe.",
    "Show navigation arrows.": "Navigationspfeile anzeigen.",
    "Show dot indicators.": "Punktindikatoren anzeigen.",
    "Hero slider": "Hero-Slider",

    # ── Hero banner ──
    "Hero background image.": "Hero-Hintergrundbild.",
    "Small badge text above the title (e.g. 'Est. 2010').": "Kleiner Badge-Text über dem Titel (z.B. 'Gegr. 2010').",
    "Main headline.": "Hauptüberschrift.",
    "Supporting text below the title.": "Unterstützender Text unter dem Titel.",
    "Secondary CTA text": "Sekundärer CTA-Text",
    "Optional secondary button label.": "Optionales sekundäres Schaltflächenlabel.",
    "Secondary CTA page link": "Sekundärer CTA-Seitenlink",
    "Secondary CTA external URL": "Sekundäre CTA-externe URL",
    "Light overlay": "Helle Überlagerung",
    "Dark overlay": "Dunkle Überlagerung",
    "Gradient overlay": "Farbverlauf-Überlagerung",
    "Overlay style over the background image.": "Überlagerungsstil über dem Hintergrundbild.",
    "Bottom left": "Unten links",
    "Bottom right": "Unten rechts",
    "Position of the text overlay.": "Position der Textüberlagerung.",
    "Hero banner": "Hero-Banner",

    # ── Hero countdown ──
    "Select an event to count down to.": "Wählen Sie eine Veranstaltung für den Countdown.",
    "Optional background image. Falls back to event cover image.": "Optionales Hintergrundbild. Fällt auf das Event-Titelbild zurück.",
    "Override the event title in the hero.": "Veranstaltungstitel im Hero überschreiben.",
    "Hero countdown": "Hero-Countdown",

    # ── Hero video ──
    "URL to the video file (MP4 recommended).": "URL zur Videodatei (MP4 empfohlen).",
    "Displayed on mobile or when video cannot play.": "Wird auf Mobilgeräten oder bei nicht abspielbarem Video angezeigt.",
    "Mute the video (required for autoplay on most browsers).": "Video stummschalten (für Autoplay in den meisten Browsern erforderlich).",
    "Loop the video.": "Video in Schleife abspielen.",
    "Hero video": "Hero-Video",

    # ── Accordion block ──
    "Accordion panel header.": "Akkordeon-Kopfzeile.",
    "Panel content revealed when expanded.": "Inhalt, der beim Aufklappen angezeigt wird.",
    "Accordion item": "Akkordeon-Element",
    "Optional section title above the accordion.": "Optionaler Abschnittstitel über dem Akkordeon.",
    "Panels": "Panels",

    # ── Tab block ──
    "Tab label.": "Tab-Bezeichnung.",
    "Tab panel content.": "Tab-Inhalt.",

    # ── Two columns block ──
    "Left column": "Linke Spalte",
    "Right column": "Rechte Spalte",
    "50 / 50": "50 / 50",
    "33 / 67": "33 / 67",
    "67 / 33": "67 / 33",
    "25 / 75": "25 / 75",
    "75 / 25": "75 / 25",
    "Column width ratio.": "Spaltenbreitenverhältnis.",
    "Two columns": "Zwei Spalten",

    # ── Section block ──
    "Optional section heading.": "Optionale Abschnittsüberschrift.",
    "Section body content.": "Abschnittsinhalt.",
    "Secondary colour": "Sekundärfarbe",
    "Light grey": "Hellgrau",
    "Background style.": "Hintergrundstil.",
    "Small": "Klein",
    "Large": "Groß",
    "Extra large": "Extra groß",
    "Vertical padding.": "Vertikaler Abstand.",

    # ── Separator/spacer ──
    "Horizontal line": "Horizontale Linie",
    "Dots": "Punkte",
    "Blank space": "Leerraum",
    "Separator visual style.": "Trennlinien-Stil.",
    "Small (1rem)": "Klein (1rem)",
    "Medium (2rem)": "Mittel (2rem)",
    "Large (4rem)": "Groß (4rem)",
    "Extra large (6rem)": "Extra groß (6rem)",
    "Amount of vertical space.": "Menge an vertikalem Abstand.",

    # ── Gallery block ──
    "Optional caption displayed below the image.": "Optionale Bildunterschrift unter dem Bild.",
    "Gallery image": "Galeriebild",
    "Optional gallery title.": "Optionaler Galerietitel.",
    "6 columns": "6 Spalten",
    "Enable lightbox for full-size image viewing.": "Lightbox für Vollbildanzeige aktivieren.",
    "Auto (original)": "Automatisch (Original)",
    "Square (1:1)": "Quadratisch (1:1)",
    "Landscape (4:3)": "Querformat (4:3)",
    "Widescreen (16:9)": "Breitbild (16:9)",
    "Portrait (3:4)": "Hochformat (3:4)",
    "Thumbnail aspect ratio.": "Vorschau-Seitenverhältnis.",

    # ── Video embed ──
    "Paste a video URL (YouTube, Vimeo, etc.).": "Video-URL einfügen (YouTube, Vimeo usw.).",
    "Optional caption displayed below the video.": "Optionale Bildunterschrift unter dem Video.",
    "Autoplay the video (muted).": "Video automatisch abspielen (stumm).",
    "Video embed": "Video-Einbettung",

    # ── Image block ──
    "Centred": "Zentriert",
    "Float left": "Links ausgerichtet",
    "Float right": "Rechts ausgerichtet",
    "Image alignment within the content area.": "Bildausrichtung im Inhaltsbereich.",

    # ── Document list ──
    "Optional description of the document.": "Optionale Beschreibung des Dokuments.",
    "Section title for the document list.": "Abschnittstitel für die Dokumentenliste.",
    "Document list": "Dokumentenliste",

    # ── Map block ──
    "Display address (shown in the info popup).": "Anzeigeadresse (im Info-Popup angezeigt).",
    "Latitude,Longitude (e.g. '45.4642,9.1900').": "Breitengrad,Längengrad (z.B. '45.4642,9.1900').",
    "Map zoom level (1-20).": "Karten-Zoomstufe (1-20).",
    "Map height in pixels.": "Kartenhöhe in Pixeln.",
    "Optional marker label.": "Optionales Markierungslabel.",

    # ── Route / waypoints ──
    "Waypoint name (e.g. 'Passo dello Stelvio').": "Wegpunktname (z.B. 'Stilfser Joch').",
    "Optional address or location description.": "Optionale Adresse oder Ortsbeschreibung.",
    "Latitude,Longitude (e.g. '46.5287,10.4531').": "Breitengrad,Längengrad (z.B. '46.5287,10.4531').",
    "Start": "Start",
    "Waypoint": "Wegpunkt",
    "Fuel stop": "Tankstelle",
    "Food / restaurant": "Restaurant",
    "Photo spot": "Fotopunkt",
    "End": "Ziel",
    "Marker icon type on the map.": "Markierungssymboltyp auf der Karte.",
    "Route name.": "Routenname.",
    "Brief route description.": "Kurze Routenbeschreibung.",
    "At least two waypoints (start and end) are required.": "Mindestens zwei Wegpunkte (Start und Ziel) sind erforderlich.",
    "Scenic ride": "Panoramafahrt",
    "Touring": "Touring",
    "Sport / twisties": "Sport / Kurven",
    "Off-road / adventure": "Offroad / Abenteuer",
    "Commute / practical": "Pendeln / Praktisch",
    "Type of route.": "Routentyp.",
    "Approximate distance (e.g. '320 km').": "Ungefähre Entfernung (z.B. '320 km').",
    "Elevation gain (e.g. '2500 m').": "Höhengewinn (z.B. '2500 m').",
    "Estimated riding time (e.g. '5-6 hours').": "Geschätzte Fahrzeit (z.B. '5-6 Stunden').",
    "Challenging": "Anspruchsvoll",
    "Route difficulty level.": "Schwierigkeitsgrad der Route.",

    # ── Verification ──
    "Enter member card number": "Mitgliedskartennummer eingeben",
    "Verification type": "Überprüfungstyp",
    "Select which piece of information to verify against.": "Wählen Sie, welche Information überprüft werden soll.",
    "Verification value": "Überprüfungswert",
    "Enter the value to verify": "Wert zur Überprüfung eingeben",

    # ── Photo uploads ──
    "Photos": "Fotos",
    "Select up to 20 images (JPG, PNG, or WebP, max 10 MB each).": "Wählen Sie bis zu 20 Bilder (JPG, PNG oder WebP, max. 10 MB pro Bild).",
    "Title prefix": "Titelpräfix",
    "Optional prefix added to each photo title.": "Optionaler Präfix, der jedem Fototitel hinzugefügt wird.",
    "e.g. Summer Rally 2025": "z.B. Sommerrallye 2025",
    "Optionally link photos to an event.": "Fotos optional mit einer Veranstaltung verknüpfen.",
    "-- No event --": "-- Keine Veranstaltung --",
    "You can upload a maximum of %(max)d files at a time.": "Sie können maximal %(max)d Dateien gleichzeitig hochladen.",
    "File '%(name)s' exceeds the maximum size of 10 MB.": "Datei '%(name)s' überschreitet die Maximalgröße von 10 MB.",
    "File '%(name)s' is not an allowed format. Only JPG, PNG, and WebP are accepted.": "Datei '%(name)s' hat kein erlaubtes Format. Nur JPG, PNG und WebP werden akzeptiert.",

    # ── Home page ──
    "Hero title": "Hero-Titel",
    "Main headline displayed in the hero section.": "Hauptüberschrift im Hero-Bereich.",
    "Hero subtitle": "Hero-Untertitel",
    "Hero background image": "Hero-Hintergrundbild",
    "Primary CTA text": "Primärer CTA-Text",
    "Primary CTA link": "Primärer CTA-Link",
    "Primary CTA external URL": "Primäre CTA-externe URL",
    "Secondary CTA link": "Sekundärer CTA-Link",
    "Featured event": "Hervorgehobene Veranstaltung",
    "Select an EventDetailPage to highlight on the homepage.": "Wählen Sie eine Veranstaltungsseite für die Startseite.",
    "Call-to-action buttons": "Handlungsaufforderungs-Schaltflächen",
    "Featured content": "Hervorgehobener Inhalt",
    "Home page": "Startseite",
    "Home pages": "Startseiten",
    "Displayed below the page title.": "Unter dem Seitentitel angezeigt.",
    "Cover image": "Titelbild",

    # ── About page ──
    "About page": "Über-uns-Seite",
    "About pages": "Über-uns-Seiten",
    "Use team-member blocks here.": "Verwenden Sie hier Teammitglieder-Blöcke.",

    # ── Board page ──
    "Board page": "Vorstandsseite",
    "Board pages": "Vorstandsseiten",

    # ── News index ──
    "Optional content displayed above the article listing.": "Optionaler Inhalt über der Artikelliste.",
    "News index page": "Nachrichtenübersichtsseite",
    "News index pages": "Nachrichtenübersichtsseiten",
    "Introduction / excerpt": "Einleitung / Auszug",
    "Short summary shown in listings.": "Kurze Zusammenfassung in Listen.",
    "Display date": "Anzeigedatum",
    "Publication date shown to readers.": "Den Lesern angezeigte Veröffentlichungsdatum.",
    "Article metadata": "Artikelmetadaten",
    "Categorisation": "Kategorisierung",
    "News page": "Nachrichtenseite",
    "News pages": "Nachrichtenseiten",

    # ── Events page ──
    "Optional content above the event listing.": "Optionaler Inhalt über der Veranstaltungsliste.",
    "Events page": "Veranstaltungsseite",
    "Events pages": "Veranstaltungsseiten",
    "Short description shown in listings.": "Kurze Beschreibung in Listen.",
    "Start date & time": "Startdatum und -zeit",
    "End date & time": "Enddatum und -zeit",
    "Venue name": "Veranstaltungsort",
    "Coordinates": "Koordinaten",
    "Latitude,Longitude (e.g. '45.4642,9.1900')": "Breitengrad,Längengrad (z.B. '45.4642,9.1900')",
    "Registration open": "Anmeldung offen",
    "Registration deadline": "Anmeldefrist",
    "Max attendees": "Maximale Teilnehmerzahl",
    "0 = unlimited.": "0 = unbegrenzt.",
    "Event participation cost in EUR.  0 = free.": "Teilnahmekosten in EUR. 0 = kostenlos.",
    "Early-bird discount (%)": "Frühbucher-Rabatt (%)",
    "Early-bird deadline": "Frühbucher-Frist",
    "Percentage discount for active members.": "Prozentrabatt für aktive Mitglieder.",
    "Allow guest registration": "Gastanmeldung erlauben",
    "Meeting point": "Treffpunkt",
    "Where participants should gather before the event start.": "Wo sich die Teilnehmer vor Veranstaltungsbeginn treffen.",
    "Difficulty level": "Schwierigkeitsgrad",
    "Schedule": "Zeitplan",
    "Registration settings": "Anmeldeeinstellungen",
    "Pricing": "Preise",
    "Promote": "Bewerben",
    "Event detail page": "Veranstaltungsdetailseite",
    "Event detail pages": "Veranstaltungsdetailseiten",

    # ── Gallery page ──
    "Root collection": "Stammsammlung",
    "Starting collection for gallery display.  Sub-collections become albums.": "Ausgangssammlung für die Galerieansicht. Untersammlungen werden zu Alben.",
    "Gallery page": "Galerieseite",
    "Gallery pages": "Galerieseiten",

    # ── Contact page ──
    "Form title": "Formulartitel",
    "Success message": "Erfolgsmeldung",
    "Confirmation shown after form submission.": "Bestätigung nach dem Absenden des Formulars.",
    "Enable captcha": "Captcha aktivieren",
    "Honeypot + Time check": "Honeypot + Zeitprüfung",
    "Cloudflare Turnstile": "Cloudflare Turnstile",
    "hCaptcha": "hCaptcha",
    "Captcha provider": "Captcha-Anbieter",
    "Captcha site key": "Captcha-Seitenschlüssel",
    "Captcha secret key": "Captcha-Geheimschlüssel",
    "Anti-spam settings": "Anti-Spam-Einstellungen",
    "Anti-spam": "Anti-Spam",
    "Contact page": "Kontaktseite",
    "Contact pages": "Kontaktseiten",

    # ── Privacy page ──
    "Last updated": "Zuletzt aktualisiert",
    "Date the policy was last revised.": "Datum der letzten Richtlinienüberarbeitung.",
    "Privacy page": "Datenschutzseite",
    "Privacy pages": "Datenschutzseiten",

    # ── Transparency page ──
    "Use document-list and accordion blocks for organising documents.": "Verwenden Sie Dokumentenlisten- und Akkordeon-Blöcke zur Organisation von Dokumenten.",
    "Transparency page": "Transparenzseite",
    "Transparency pages": "Transparenzseiten",

    # ── Press page ──
    "Press email": "Presse-E-Mail",
    "Press phone": "Pressetelefon",
    "Press contact person": "Pressekontaktperson",
    "Press contact": "Pressekontakt",
    "Press page": "Pressseseite",
    "Press pages": "Presseseiten",

    # ── Partner index ──
    "Partner index page": "Partnerübersichtsseite",
    "Partner index pages": "Partnerübersichtsseiten",
    "ISO 3166-1 alpha-2 country code.": "ISO 3166-1 Alpha-2-Ländercode.",
    "Facebook URL": "Facebook-URL",
    "Instagram URL": "Instagram-URL",
    "LinkedIn URL": "LinkedIn-URL",
    "YouTube URL": "YouTube-URL",
    "Twitter / X URL": "Twitter / X-URL",
    "Partner owner": "Partnerinhaber",
    "User account that manages this partner page.": "Benutzerkonto, das diese Partnerseite verwaltet.",
    "Owner email": "Inhaber-E-Mail",
    "Contact email for the partner owner.": "Kontakt-E-Mail des Partnerinhabers.",
    "Show this partner prominently.": "Diesen Partner hervorheben.",
    "Display order": "Anzeigereihenfolge",
    "Lower numbers appear first.": "Niedrigere Zahlen erscheinen zuerst.",
    "Show on homepage": "Auf Startseite anzeigen",
    "Partnership start": "Partnerschaftsbeginn",
    "Partnership end": "Partnerschaftsende",
    "Leave blank for ongoing partnerships.": "Leer lassen für laufende Partnerschaften.",
    "Social media": "Soziale Medien",
    "Ownership": "Eigentum",
    "Display settings": "Anzeigeeinstellungen",
    "Social": "Soziales",
    "Display": "Anzeige",
    "Partner page": "Partnerseite",
    "Partner pages": "Partnerseiten",

    # ── Theme names ──
    "Velocity": "Velocity",
    "Heritage": "Heritage",
    "Terra / Eco": "Terra / Eco",
    "Zen": "Zen",
    "Clubs": "Clubs",
    "Tricolore": "Tricolore",

    # ── Site settings ──
    "Honeypot (no external service)": "Honeypot (kein externer Dienst)",
    "OpenStreetMap": "OpenStreetMap",
    "Google Maps": "Google Maps",
    "Mapbox": "Mapbox",
    "Human-readable name shown in the header / meta tags.": "Lesbarer Name in der Kopfzeile / Meta-Tags.",
    "Site description": "Seitenbeschreibung",
    "Default meta description for SEO.": "Standard-Meta-Beschreibung für SEO.",
    "Colour scheme": "Farbschema",
    "Logo (dark variant)": "Logo (dunkle Variante)",
    "Optional dark-background version of the logo.": "Optionale Logo-Version mit dunklem Hintergrund.",
    "Opening hours": "Öffnungszeiten",
    "TikTok URL": "TikTok-URL",
    "Navbar": "Navigationsleiste",
    "PWA name": "PWA-Name",
    "PWA short name": "PWA-Kurzname",
    "PWA description": "PWA-Beschreibung",
    "PWA icon 192x192": "PWA-Symbol 192x192",
    "PWA icon 512x512": "PWA-Symbol 512x512",
    "PWA theme colour": "PWA-Designfarbe",
    "PWA background colour": "PWA-Hintergrundfarbe",
    "CAPTCHA provider": "CAPTCHA-Anbieter",
    "CAPTCHA site key": "CAPTCHA-Seitenschlüssel",
    "CAPTCHA secret key": "CAPTCHA-Geheimschlüssel",
    "Map routing service": "Karten-Routing-Dienst",
    "Map API key": "Karten-API-Schlüssel",
    "Required for Google Maps / Mapbox.": "Erforderlich für Google Maps / Mapbox.",
    "Default map centre": "Standard-Kartenmittelpunkt",
    "Default map zoom": "Standard-Kartenzoom",
    "General": "Allgemein",
    "Branding": "Branding",
    "Progressive Web App": "Progressive Web App",
    "PWA": "PWA",
    "Anti-spam / CAPTCHA": "Anti-Spam / CAPTCHA",
    "Forms": "Formulare",
    "Map & routing": "Karte & Routing",
    "site settings": "Seiteneinstellungen",

    # ── Payment settings ──
    "Test": "Test",
    "Payment mode": "Zahlungsmodus",
    "Only credentials for the selected mode are used at runtime.": "Nur die Anmeldedaten des ausgewählten Modus werden zur Laufzeit verwendet.",
    "Stripe enabled (test)": "Stripe aktiviert (Test)",
    "Stripe public key (test)": "Öffentlicher Stripe-Schlüssel (Test)",
    "Stripe secret key (test)": "Geheimer Stripe-Schlüssel (Test)",
    "Stripe webhook secret (test)": "Stripe-Webhook-Geheimnis (Test)",
    "PayPal enabled (test)": "PayPal aktiviert (Test)",
    "PayPal client ID (test)": "PayPal-Client-ID (Test)",
    "PayPal secret (test)": "PayPal-Geheimnis (Test)",
    "Stripe enabled (live)": "Stripe aktiviert (Live)",
    "Stripe public key (live)": "Öffentlicher Stripe-Schlüssel (Live)",
    "Stripe secret key (live)": "Geheimer Stripe-Schlüssel (Live)",
    "Stripe webhook secret (live)": "Stripe-Webhook-Geheimnis (Live)",
    "PayPal enabled (live)": "PayPal aktiviert (Live)",
    "PayPal client ID (live)": "PayPal-Client-ID (Live)",
    "PayPal secret (live)": "PayPal-Geheimnis (Live)",
    "Bank transfer enabled": "Banküberweisung aktiviert",
    "Account holder": "Kontoinhaber",
    "IBAN": "IBAN",
    "BIC / SWIFT": "BIC / SWIFT",
    "Bank name": "Bankname",
    "Bank transfer instructions": "Überweisungsanweisungen",
    "Additional instructions shown to the user (e.g. 'Include the reference in the description').": "Zusätzliche Anweisungen für den Benutzer (z.B. 'Referenz im Verwendungszweck angeben').",
    "Bank transfer expiry (days)": "Überweisungsfrist (Tage)",
    "Days allowed for the user to complete the bank transfer.": "Tage, die dem Benutzer für die Überweisung eingeräumt werden.",
    "Active mode": "Aktiver Modus",
    "Mode": "Modus",
    "Stripe (test)": "Stripe (Test)",
    "PayPal (test)": "PayPal (Test)",
    "Test configuration": "Testkonfiguration",
    "Stripe (live)": "Stripe (Live)",
    "PayPal (live)": "PayPal (Live)",
    "Live configuration": "Live-Konfiguration",
    "Bank transfer": "Banküberweisung",
    "payment settings": "Zahlungseinstellungen",

    # ── Colour scheme snippet ──
    "Main brand colour (hex).": "Hauptmarkenfarbe (Hex).",
    "Secondary/accent brand colour (hex).": "Sekundäre/Akzent-Markenfarbe (Hex).",
    "Accent colour": "Akzentfarbe",
    "Accent highlight colour (hex).": "Akzent-Hervorhebungsfarbe (Hex).",
    "Surface colour": "Oberflächenfarbe",
    "Card/panel background colour (hex).": "Karten-/Panelhintergrundfarbe (Hex).",
    "Surface alt colour": "Alternative Oberflächenfarbe",
    "Alternate surface colour (hex).": "Alternative Oberflächenfarbe (Hex).",
    "Text primary": "Primärtext",
    "Main body text colour (hex).": "Haupttext-Farbe (Hex).",
    "Text muted": "Gedämpfter Text",
    "Secondary/lighter text colour (hex).": "Sekundäre/hellere Textfarbe (Hex).",
    "Enable if this is a dark colour scheme.": "Aktivieren, wenn dies ein dunkles Farbschema ist.",
    "Brand colours": "Markenfarben",
    "Surface colours": "Oberflächenfarben",
    "Text colours": "Textfarben",
    "colour scheme": "Farbschema",
    "colour schemes": "Farbschemata",

    # ── Navbar snippet ──
    "Show search": "Suche anzeigen",
    "navbar": "Navigationsleiste",
    "navbars": "Navigationsleisten",
    "Parent item": "Übergeordnetes Element",
    "Leave empty for top-level items. Select a parent for dropdown sub-items.": "Leer lassen für Elemente der obersten Ebene. Übergeordnetes Element für Dropdown-Unterelemente auswählen.",
    "Link page": "Verlinkungsseite",
    "Used only when no page is selected.": "Wird nur verwendet, wenn keine Seite ausgewählt ist.",
    "Open in new tab": "In neuem Tab öffnen",
    "Is CTA": "Ist CTA",
    "Render as a highlighted call-to-action button.": "Als hervorgehobene Handlungsaufforderungs-Schaltfläche anzeigen.",

    # ── Footer snippet ──
    "Twitter / X": "Twitter / X",
    "TikTok": "TikTok",
    "Short 'about' text displayed in the footer.": "Kurzer 'Über uns'-Text in der Fußzeile.",
    "Copyright text": "Urheberrechtstext",
    "Contact details": "Kontaktdaten",
    "Social links": "Soziale Links",
    "footer": "Fußzeile",
    "footers": "Fußzeilen",

    # ── FAQ snippet ──
    "Platform": "Plattform",
    "Question": "Frage",
    "Answer": "Antwort",
    "Optional grouping label for the FAQ.": "Optionale Gruppierungsbezeichnung für die FAQ.",
    "FAQ": "FAQ",
    "FAQs": "FAQs",

    # ── Testimonial snippet ──
    "Author name": "Autorenname",
    "Author role": "Autorenrolle",
    "Author photo": "Autorenfoto",
    "Show this testimonial more prominently.": "Diese Referenz hervorheben.",
    "testimonial": "Referenz",
    "testimonials": "Referenzen",

    # ── Category snippets ──
    "Colour": "Farbe",
    "Badge/label colour (hex).": "Badge-/Label-Farbe (Hex).",
    "news category": "Nachrichtenkategorie",
    "news categories": "Nachrichtenkategorien",
    "Motorcycle": "Motorrad",
    "Rally": "Rallye",
    "Meeting": "Treffen",
    "Charity": "Wohltätigkeit",
    "Race": "Rennen",
    "event category": "Veranstaltungskategorie",
    "event categories": "Veranstaltungskategorien",
    "photo tag": "Foto-Tag",
    "photo tags": "Foto-Tags",
    "partner category": "Partnerkategorie",
    "partner categories": "Partnerkategorien",

    # ── Press release snippet ──
    "Attachment": "Anhang",
    "PDF or document attachment.": "PDF- oder Dokumentanhang.",
    "Archived": "Archiviert",
    "press release": "Pressemitteilung",
    "press releases": "Pressemitteilungen",

    # ── Brand asset snippet ──
    "Font": "Schriftart",
    "Template": "Vorlage",
    "Preview image": "Vorschaubild",
    "brand asset": "Markenressource",
    "brand assets": "Markenressourcen",

    # ── Aid skill snippet ──
    "Mechanics": "Mechanik",
    "Logistics": "Logistik",
    "Emergency": "Notfall",
    "aid skill": "Hilfsfähigkeit",
    "aid skills": "Hilfsfähigkeiten",

    # ── Product snippet ──
    "Inactive products are hidden from the storefront.": "Inaktive Produkte sind in der Übersicht verborgen.",
    "Grants voting rights": "Gewährt Stimmrecht",
    "Grants gallery upload": "Gewährt Galerie-Upload",
    "Grants event access": "Gewährt Veranstaltungszugang",
    "Grants discount": "Gewährt Rabatt",
    "Percentage discount on events when grants_discount is on.": "Prozentrabatt auf Veranstaltungen, wenn grants_discount aktiviert ist.",
    "Product info": "Produktinfo",
    "Member privileges": "Mitgliederprivilegien",
    "product": "Produkt",

    # ── Photo upload model ──
    "Uploaded by": "Hochgeladen von",
    "Optionally link this photo to an event.": "Dieses Foto optional mit einer Veranstaltung verknüpfen.",
    "Approved at": "Genehmigt am",
    "Rejection reason": "Ablehnungsgrund",
    "Uploaded at": "Hochgeladen am",
    "photo upload": "Foto-Upload",
    "photo uploads": "Foto-Uploads",
    "approved": "genehmigt",
    "pending": "ausstehend",

    # ── Verification log ──
    "Not found": "Nicht gefunden",
    "Wrong data": "Falsche Daten",
    "Expired membership": "Abgelaufene Mitgliedschaft",
    "Partner user": "Partnerbenutzer",
    "The partner owner who performed this verification.": "Der Partnerinhaber, der diese Überprüfung durchgeführt hat.",
    "Which secondary factor was used for verification.": "Welcher sekundäre Faktor für die Überprüfung verwendet wurde.",
    "Result": "Ergebnis",
    "IP address": "IP-Adresse",
    "verification log": "Überprüfungsprotokoll",
    "verification logs": "Überprüfungsprotokolle",

    # ── Verification error messages ──
    "Access denied. Only partner owners and staff can verify members.": "Zugriff verweigert. Nur Partnerinhaber und Mitarbeiter können Mitglieder verifizieren.",
    "Rate limit exceeded. Maximum 20 verification attempts per hour.": "Ratenlimit überschritten. Maximal 20 Überprüfungsversuche pro Stunde.",
    "Account temporarily locked. Too many failed verification attempts. Please try again in 15 minutes.": "Konto vorübergehend gesperrt. Zu viele fehlgeschlagene Überprüfungsversuche. Bitte versuchen Sie es in 15 Minuten erneut.",
    "No member found with this card number.": "Kein Mitglied mit dieser Kartennummer gefunden.",
    "This member's membership has expired.": "Die Mitgliedschaft dieses Mitglieds ist abgelaufen.",
    "Member verified successfully.": "Mitglied erfolgreich verifiziert.",
    "N/A": "K.A.",
    "Verification failed. The provided information does not match our records.": "Überprüfung fehlgeschlagen. Die angegebenen Informationen stimmen nicht mit unseren Aufzeichnungen überein.",
    "Access denied. Your membership does not include gallery upload privileges.": "Zugriff verweigert. Ihre Mitgliedschaft beinhaltet keine Galerie-Upload-Berechtigungen.",
    "Rejected by moderator.": "Vom Moderator abgelehnt.",

    # ── Membership card template ──
    "Membership Card": "Mitgliedskarte",
    "Card No.": "Karten-Nr.",
    "Expires": "Läuft ab",
    "Barcode": "Strichcode",
    "Download PDF": "PDF herunterladen",
    "No membership card has been issued yet. Please contact the club administration.": "Es wurde noch keine Mitgliedskarte ausgestellt. Bitte kontaktieren Sie die Clubverwaltung.",

    # ── Member directory template ──
    "Member Directory": "Mitgliederverzeichnis",
    "Pagination": "Seitennummerierung",
    "No members are currently visible in the directory.": "Derzeit sind keine Mitglieder im Verzeichnis sichtbar.",

    # ── Auth templates ──
    "Welcome back": "Willkommen zurück",
    "Log in to access your profile, events, and club features.": "Melden Sie sich an, um auf Ihr Profil, Veranstaltungen und Club-Funktionen zuzugreifen.",
    "Forgot your password?": "Passwort vergessen?",
    "Don't have an account?": "Noch kein Konto?",
    "Are you sure you want to log out?": "Sind Sie sicher, dass Sie sich abmelden möchten?",
    "Go back to home": "Zurück zur Startseite",
    "Become a member": "Mitglied werden",
    "Choose the membership plan that best fits your needs. Combine multiple products to customize your ex": "Wählen Sie den Mitgliedschaftsplan, der am besten zu Ihnen passt. Kombinieren Sie mehrere Produkte, um Ihre Er",
    "Your plan": "Ihr Plan",
    "year": "Jahr",
    "Event registration": "Veranstaltungsanmeldung",
    "Voting rights": "Stimmrecht",
    "Gallery upload": "Galerie-Upload",
    "%(percent)s%% discount on events": "%(percent)s%% Rabatt auf Veranstaltungen",
    "Contact the club": "Club kontaktieren",
    "No membership plans available at this time.": "Derzeit keine Mitgliedschaftspläne verfügbar.",
    "Reset your password": "Passwort zurücksetzen",
    "Enter your email address and we'll send you a link to reset your password.": "Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen einen Link zum Zurücksetzen Ihres Passworts.",
    "Send reset link": "Link zum Zurücksetzen senden",
    "Back to login": "Zurück zur Anmeldung",
    "Active Member": "Aktives Mitglied",
    "Back to Directory": "Zurück zum Verzeichnis",
    "Create your account": "Konto erstellen",
    "Join the club and access events, member directory, and more.": "Treten Sie dem Club bei und nutzen Sie Veranstaltungen, Mitgliederverzeichnis und mehr.",
    "Already have an account?": "Bereits ein Konto?",

    # ── Registration confirmation ──
    "Registration Confirmed": "Anmeldung bestätigt",

    # ── Payment pages ──
    "Amount": "Betrag",
    "Bank Transfer Payment Required": "Banküberweisung erforderlich",
    "This is an automatic confirmation email. Please do not reply.": "Dies ist eine automatische Bestätigungsmail. Bitte antworten Sie nicht.",

    # ── Favorite events ──
    "My Favorite Events": "Meine Lieblingsveranstaltungen",
    "Upcoming": "Bevorstehend",
    "Archive": "Archiv",
    "My Registrations": "Meine Anmeldungen",
    "Events map": "Veranstaltungskarte",
    "Map view of your favorite events": "Kartenansicht Ihrer Lieblingsveranstaltungen",
    "Remove from favorites": "Aus Favoriten entfernen",
    "Download calendar file": "Kalenderdatei herunterladen",
    "ICS": "ICS",
    "You have not added any events to your favorites yet.": "Sie haben noch keine Veranstaltungen zu Ihren Favoriten hinzugefügt.",
    "Events Archive": "Veranstaltungsarchiv",
    "No past events in your favorites.": "Keine vergangenen Veranstaltungen in Ihren Favoriten.",

    # ── Payment flow ──
    "Payment": "Zahlung",
    "Bank Transfer Instructions": "Überweisungsanweisungen",
    "Transfer Details": "Überweisungsdetails",
    "Bank": "Bank",
    "Payment Reference": "Zahlungsreferenz",
    "Copy": "Kopieren",
    "Deadline": "Frist",
    "Back to my registrations": "Zurück zu meinen Anmeldungen",
    "Your payment was not completed. You can try again using the link below.": "Ihre Zahlung wurde nicht abgeschlossen. Sie können es über den Link unten erneut versuchen.",
    "Try again": "Erneut versuchen",
    "Choose Payment Method": "Zahlungsmethode wählen",
    "Credit / Debit Card": "Kredit-/Debitkarte",
    "Pay securely with Stripe": "Sicher mit Stripe bezahlen",
    "Pay with your PayPal account": "Mit Ihrem PayPal-Konto bezahlen",
    "Pay via SEPA bank transfer": "Per SEPA-Überweisung bezahlen",
    "Payment Confirmed": "Zahlung bestätigt",
    "Register for Event": "Zur Veranstaltung anmelden",
    "Member discount": "Mitgliedsrabatt",
    "Please correct the highlighted errors below.": "Bitte korrigieren Sie die markierten Fehler unten.",
    "Your Information": "Ihre Informationen",
    "Registration Details": "Anmeldedetails",
    "Registration Summary": "Anmeldeübersicht",

    # ── Federation / Partner events ──
    "Partner Events": "Partnerveranstaltungen",
    "Breadcrumb": "Brotkrümelnavigation",
    "Club": "Club",
    "View on Google Maps": "Auf Google Maps ansehen",
    "View on partner site": "Auf Partnerseite ansehen",
    "Events from our federated partner clubs.": "Veranstaltungen unserer Partnerclubs.",
    "Partner Club": "Partnerclub",
    "All clubs": "Alle Clubs",
    "Search events...": "Veranstaltungen suchen...",
    "No partner events found.": "Keine Partnerveranstaltungen gefunden.",
    "Clear filters": "Filter löschen",
    "Club Discussion": "Club-Diskussion",
    "Comments are visible only to our club members. They are not shared with the partner club.": "Kommentare sind nur für unsere Clubmitglieder sichtbar. Sie werden nicht mit dem Partnerclub geteilt.",
    "Delete this comment?": "Diesen Kommentar löschen?",
    "No comments yet. Be the first to start a discussion!": "Noch keine Kommentare. Starten Sie die Diskussion!",
    "Add a comment": "Kommentar hinzufügen",
    "Share your thoughts with fellow club members...": "Teilen Sie Ihre Gedanken mit anderen Clubmitgliedern...",
    "Post Comment": "Kommentar veröffentlichen",
    "Only active members can post comments.": "Nur aktive Mitglieder können Kommentare veröffentlichen.",
    "Are you interested?": "Sind Sie interessiert?",
    "going": "teilnehmen",
    "interested": "interessiert",
    "maybe": "vielleicht",
    "Only active members can express interest in partner events.": "Nur aktive Mitglieder können Interesse an Partnerveranstaltungen bekunden.",

    # ── Navbar template ──
    "Main navigation": "Hauptnavigation",
    "Toggle navigation": "Navigation umschalten",
    "Search...": "Suchen...",
    "Search the site": "Seite durchsuchen",
    "Submit search": "Suche absenden",
    "Membership card": "Mitgliedskarte",
    "My events": "Meine Veranstaltungen",
    "Member directory": "Mitgliederverzeichnis",

    # ── Mutual Aid access request ──
    "Request Access": "Zugang anfordern",
    "Request Access to Mutual Aid": "Zugang zur Gegenseitigen Hilfe anfordern",
    "Submit Request": "Antrag absenden",
    "radius": "Radius",
    "Send Request": "Anfrage senden",
    "Availability": "Verfügbarkeit",
    "WhatsApp": "WhatsApp",
    "Send message": "Nachricht senden",
    "Send Aid Request": "Hilfeanfrage senden",
    "Unlock Limit Reached": "Freischaltungslimit erreicht",
    "Contact Unlock Limit Reached": "Kontakt-Freischaltungslimit erreicht",
    "Please wait before unlocking more contacts, or use the contacts you have already unlocked.": "Bitte warten Sie, bevor Sie weitere Kontakte freischalten, oder nutzen Sie die bereits freigeschalteten Kontakte.",
    "Back to Mutual Aid": "Zurück zur Gegenseitigen Hilfe",
    "Emergency Contacts": "Notfallkontakte",
    "Check back later or contact the club directly.": "Schauen Sie später vorbei oder kontaktieren Sie den Club direkt.",

    # ── Notification digest template ──
    "Notification digest": "Benachrichtigungsübersicht",
    "View details": "Details anzeigen",
    "Notification history": "Benachrichtigungsverlauf",
    "ago": "vor",
    "No notifications yet.": "Noch keine Benachrichtigungen.",
    "Unsubscribe": "Abmelden",
    "Confirm unsubscribe": "Abmeldung bestätigen",
    "You can re-enable notifications at any time from your account settings.": "Sie können Benachrichtigungen jederzeit in Ihren Kontoeinstellungen wieder aktivieren.",
    "Invalid link": "Ungültiger Link",
    "Unsubscribed": "Abgemeldet",
    "You have been unsubscribed from these notifications. You will no longer receive them.": "Sie wurden von diesen Benachrichtigungen abgemeldet. Sie werden sie nicht mehr erhalten.",
    "If you change your mind, you can re-enable notifications from your": "Wenn Sie Ihre Meinung ändern, können Sie Benachrichtigungen wieder aktivieren in Ihren",
    "account settings": "Kontoeinstellungen",

    # ── Events filters ──
    "Event period": "Veranstaltungszeitraum",
    "Past": "Vergangen",
    "Event filters": "Veranstaltungsfilter",
    "Registration Open": "Anmeldung offen",

    # ── Remaining strings (pass 3) ──
    "Contact information": "Kontaktdaten",
    "\\n                Page %(current)s of %(total)s\\n            ": "\\n                Seite %(current)s von %(total)s\\n            ",
    "Choose the membership plan that best fits your needs. Combine multiple products to customize your experience.": "Wählen Sie den Mitgliedschaftsplan, der am besten zu Ihnen passt. Kombinieren Sie mehrere Produkte, um Ihr Erlebnis anzupassen.",
    "Your registration for <strong>%(event_title)s</strong> has been confirmed.": "Ihre Anmeldung für <strong>%(event_title)s</strong> wurde bestätigt.",
    "Please complete the bank transfer with reference <strong>%(ref)s</strong> before %(expires)s.": "Bitte überweisen Sie mit der Referenz <strong>%(ref)s</strong> vor dem %(expires)s.",
    "Please include the payment reference in the transfer description. Your registration will be confirmed once the payment is verified by the organiser.": "Bitte geben Sie die Zahlungsreferenz im Verwendungszweck an. Ihre Anmeldung wird bestätigt, sobald die Zahlung vom Organisator überprüft wurde.",
    "As a member of a federated partner club, you can request access to our mutual aid helpers directory.": "Als Mitglied eines Partnerclubs können Sie Zugang zu unserem Verzeichnis der Hilfeleistenden beantragen.",
    "Your request will be reviewed by our administrators. Once approved, you will be able to view and contact available helpers.": "Ihr Antrag wird von unseren Administratoren geprüft. Nach Genehmigung können Sie verfügbare Helfer sehen und kontaktieren.",
    "Sending request to:": "Anfrage wird gesendet an:",
    "\\n                You have reached the maximum of %(limit)s contact unlocks\\n                per %(days)s-day period.\\n            ": "\\n                Sie haben das Maximum von %(limit)s Kontaktfreischaltungen\\n                pro %(days)s-Tage-Zeitraum erreicht.\\n            ",
    "\\n    Hi %(name)s, here is your notification digest\\n    ": "\\n    Hallo %(name)s, hier ist Ihre Benachrichtigungszusammenfassung\\n    ",
    "\\n    You have %(count)s new notification(s).\\n    ": "\\n    Sie haben %(count)s neue Benachrichtigung(en).\\n    ",
    "\\n                Page %(current)s of %(total)s\\n                ": "\\n                Seite %(current)s von %(total)s\\n                ",
    "\\n            You are about to unsubscribe <strong>%(email)s</strong> from\\n            <strong>%(type)s</strong> notifications.\\n            ": "\\n            Sie sind dabei, <strong>%(email)s</strong> von\\n            <strong>%(type)s</strong>-Benachrichtigungen abzumelden.\\n            ",
    "This unsubscribe link is invalid or has expired. Please check the link and try again, or manage your preferences from your account settings.": "Dieser Abmeldelink ist ungültig oder abgelaufen. Bitte überprüfen Sie den Link und versuchen Sie es erneut, oder verwalten Sie Ihre Einstellungen in Ihren Kontoeinstellungen.",
    "Thank you for your message. We will get back to you shortly.": "Vielen Dank für Ihre Nachricht. Wir werden uns in Kürze bei Ihnen melden.",
    "Please correct the errors below:": "Bitte korrigieren Sie die folgenden Fehler:",
    "Subject": "Betreff",
    "Send Message": "Nachricht senden",
    "Club location map": "Club-Standortkarte",
    "View larger map": "Größere Karte anzeigen",
    "opens in a new window": "öffnet in einem neuen Fenster",
    "Where to Find Us": "So finden Sie uns",
    "Direct Contacts": "Direktkontakte",
    "Opening Hours": "Öffnungszeiten",
    "No events found.": "Keine Veranstaltungen gefunden.",
}

if __name__ == "__main__":
    run_translation("de", "Deutsch", TRANSLATIONS)
