# Generated by Django 5.2.12 on 2026-03-20 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventregistration_payment_amount_and_more'),
        ('website', '0020_logo_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfavorite',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text="Data e ora in cui l'evento è stato salvato.", verbose_name='Added at'),
        ),
        migrations.AlterField(
            model_name='eventfavorite',
            name='event',
            field=models.ForeignKey(help_text='Evento salvato nei preferiti.', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='website.eventdetailpage', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='eventfavorite',
            name='user',
            field=models.ForeignKey(help_text="Utente che ha salvato l'evento.", on_delete=django.db.models.deletion.CASCADE, related_name='favorite_events', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(help_text="Evento a cui si riferisce l'iscrizione.", on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='website.eventdetailpage', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='first_name',
            field=models.CharField(blank=True, help_text="Nome dell'ospite (registrazione senza account).", max_length=150, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='guest_names',
            field=models.TextField(blank=True, help_text='Nomi degli accompagnatori, uno per riga.', verbose_name='Guest names'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='guests',
            field=models.IntegerField(default=0, help_text='Numero di accompagnatori aggiuntivi.', verbose_name='Number of guests'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='has_passenger',
            field=models.BooleanField(default=False, help_text="L'iscritto viaggia con un passeggero.", verbose_name='Has passenger'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='last_name',
            field=models.CharField(blank=True, help_text="Cognome dell'ospite (registrazione senza account).", max_length=150, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='notes',
            field=models.TextField(blank=True, help_text="Note aggiuntive dell'iscritto (allergie, esigenze, ecc.).", verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='passenger_birth_date',
            field=models.DateField(blank=True, help_text='Data di nascita del passeggero.', null=True, verbose_name='Passenger birth date'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='passenger_email',
            field=models.CharField(blank=True, help_text='Email del passeggero.', max_length=254, verbose_name='Passenger email'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='passenger_emergency_contact',
            field=models.CharField(blank=True, help_text='Contatto di emergenza del passeggero.', max_length=255, verbose_name='Passenger emergency contact'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='passenger_first_name',
            field=models.CharField(blank=True, help_text='Nome del passeggero non socio.', max_length=150, verbose_name='Passenger first name'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='passenger_fiscal_code',
            field=models.CharField(blank=True, help_text='Codice fiscale del passeggero.', max_length=16, verbose_name='Passenger fiscal code'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='passenger_is_member',
            field=models.BooleanField(default=False, help_text='Il passeggero è un socio del club.', verbose_name='Passenger is a member'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='passenger_last_name',
            field=models.CharField(blank=True, help_text='Cognome del passeggero non socio.', max_length=150, verbose_name='Passenger last name'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='passenger_member',
            field=models.ForeignKey(blank=True, help_text='Seleziona il socio passeggero.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Passenger (member)'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='passenger_phone',
            field=models.CharField(blank=True, help_text='Telefono del passeggero.', max_length=30, verbose_name='Passenger phone'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Importo totale da pagare in euro.', max_digits=8, verbose_name='Payment amount'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('free', 'Free')], default='', help_text='Metodo di pagamento utilizzato.', max_length=20, verbose_name='Payment provider'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='pending', help_text='Stato del pagamento per questa iscrizione.', max_length=20, verbose_name='Payment status'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, help_text="Data e ora dell'iscrizione.", verbose_name='Registered at'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('waitlist', 'Waitlist')], default='registered', help_text="Stato corrente dell'iscrizione.", max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Utente iscritto. Vuoto per iscrizioni ospite.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='pricingtier',
            name='days_before',
            field=models.IntegerField(default=0, help_text="Giorni prima dell'evento per questa fascia.", verbose_name='Days before event'),
        ),
        migrations.AlterField(
            model_name='pricingtier',
            name='discount_percent',
            field=models.IntegerField(default=0, help_text='Percentuale di sconto applicata in questa fascia.', verbose_name='Discount percent'),
        ),
        migrations.AlterField(
            model_name='pricingtier',
            name='hours_before',
            field=models.IntegerField(default=0, help_text="Ore prima dell'evento per questa fascia.", verbose_name='Hours before event'),
        ),
        migrations.AlterField(
            model_name='pricingtier',
            name='minutes_before',
            field=models.IntegerField(default=0, help_text="Minuti prima dell'evento per questa fascia.", verbose_name='Minutes before event'),
        ),
    ]
