# Generated by Django 5.2.12 on 2026-03-22 09:51

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduzione')),
            ],
            options={
                'verbose_name': 'Indice Luoghi',
                'verbose_name_plural': 'Indici Luoghi',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PlaceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Tag Luogo',
                'verbose_name_plural': 'Tag Luoghi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlacePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('place_type', models.CharField(choices=[('clubhouse', 'Sede Club'), ('monument', 'Monumento'), ('square', 'Piazza'), ('poi', 'Punto di Interesse'), ('event_venue', 'Luogo Eventi'), ('accommodation', 'Alloggio'), ('restaurant', 'Ristorante')], default='poi', max_length=20, verbose_name='Tipo di luogo')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitudine')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitudine')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Città')),
                ('province', models.CharField(blank=True, max_length=5, verbose_name='Provincia')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='CAP')),
                ('country', models.CharField(default='IT', max_length=2, verbose_name='Paese (ISO 3166-1)')),
                ('short_description', models.CharField(blank=True, help_text='Usata nelle card e nei risultati di ricerca.', max_length=300, verbose_name='Descrizione breve')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Descrizione')),
                ('opening_hours', models.CharField(blank=True, help_text='Formato: Mo-Fr 09:00-18:00, Sa 10:00-14:00', max_length=255, verbose_name='Orari di apertura')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website_url', models.URLField(blank=True, verbose_name='Sito web')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Immagine di copertina')),
                ('tags', modelcluster.fields.ParentalManyToManyField(blank=True, to='places.placetag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Luogo',
                'verbose_name_plural': 'Luoghi',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PlaceGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250, verbose_name='Didascalia')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Immagine')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='places.placepage')),
            ],
            options={
                'verbose_name': 'Immagine galleria',
                'verbose_name_plural': 'Immagini galleria',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoutePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Descrizione breve')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Descrizione')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Distanza (km)')),
                ('estimated_duration', models.DurationField(blank=True, null=True, verbose_name='Durata stimata')),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Media'), ('hard', 'Difficile')], default='medium', max_length=20, verbose_name='Difficoltà')),
                ('gpx_file', models.FileField(blank=True, help_text='Traccia GPX del percorso', upload_to='routes/gpx/', verbose_name='File GPX')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Immagine di copertina')),
            ],
            options={
                'verbose_name': 'Percorso',
                'verbose_name_plural': 'Percorsi',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Nota tappa')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_appearances', to='places.placepage', verbose_name='Luogo')),
                ('route', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='places.routepage')),
            ],
            options={
                'verbose_name': 'Tappa',
                'verbose_name_plural': 'Tappe',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
