# Generated by Django 5.2.12 on 2026-03-20 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_add_contribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('upload', 'Upload'), ('register', 'Registration'), ('comment', 'Comment'), ('reaction', 'Reaction'), ('profile_update', 'Profile update'), ('login', 'Login')], help_text='Tipo di azione registrata nel log attività.', max_length=30, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text="Data e ora di registrazione dell'attività.", verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='target_content_type',
            field=models.ForeignKey(blank=True, help_text="Tipo di contenuto dell'oggetto collegato.", null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Target content type'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, help_text="ID dell'oggetto collegato a questa attività.", null=True, verbose_name='Target ID'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='target_title',
            field=models.CharField(blank=True, help_text="Titolo dell'oggetto collegato, salvato per riferimento rapido.", max_length=255, verbose_name='Target title'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='target_url',
            field=models.URLField(blank=True, help_text="URL dell'oggetto collegato, se disponibile.", verbose_name='Target URL'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(help_text="Utente che ha eseguito l'azione.", on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='Testo del commento.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(help_text="Tipo di contenuto dell'oggetto commentato.", on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e ora di creazione del commento.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='moderated_by',
            field=models.ForeignKey(blank=True, help_text='Moderatore che ha revisionato il commento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_comments', to=settings.AUTH_USER_MODEL, verbose_name='Moderated by'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Stato di moderazione: in attesa, approvato o rifiutato.', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(help_text="ID dell'oggetto commentato.", verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Commento genitore, se questo è una risposta.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.comment', verbose_name='Reply to'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text="Data e ora dell'ultima modifica.", verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(help_text='Utente autore del commento.', on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='body',
            field=models.TextField(help_text='Corpo del contributo. Supporta testo semplice.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('story', 'Story'), ('proposal', 'Event proposal'), ('announcement', 'Announcement')], help_text='Tipo di contributo: storia, proposta evento o annuncio.', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e ora di invio del contributo.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='moderated_by',
            field=models.ForeignKey(blank=True, help_text='Moderatore che ha revisionato il contributo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_contributions', to=settings.AUTH_USER_MODEL, verbose_name='Moderated by'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='moderation_note',
            field=models.TextField(blank=True, help_text="Nota del moderatore visibile all'autore.", null=True, verbose_name='Moderation note'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Stato di moderazione del contributo.', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='title',
            field=models.CharField(help_text='Titolo del contributo (max 255 caratteri).', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text="Data e ora dell'ultima modifica.", verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='user',
            field=models.ForeignKey(help_text='Utente autore del contributo.', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='content_type',
            field=models.ForeignKey(help_text="Tipo di contenuto dell'oggetto a cui è associata la reazione.", on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e ora in cui è stata lasciata la reazione.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='object_id',
            field=models.PositiveIntegerField(help_text="ID dell'oggetto a cui è associata la reazione.", verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('love', 'Love')], default='like', help_text='Tipo di reazione: Like o Love.', max_length=10, verbose_name='Reaction'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(help_text='Utente che ha lasciato la reazione.', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
