# Generated by Django 5.2.11 on 2026-02-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_homepage_hero_badge_alter_aboutpage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetailpage',
            name='latitude',
            field=models.FloatField(blank=True, editable=False, help_text='Auto-populated from coordinates.', null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='eventdetailpage',
            name='longitude',
            field=models.FloatField(blank=True, editable=False, help_text='Auto-populated from coordinates.', null=True, verbose_name='Longitude'),
        ),
    ]
