# Generated by Django 5.2.11 on 2026-02-13 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('website', '0007_add_lat_lng_to_eventdetailpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='hero_badge',
            field=models.CharField(blank=True, help_text="Small text above the title (e.g. 'Let's Talk').", max_length=50, verbose_name='Hero badge'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Optional background image for the page header.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='membership_cta_text',
            field=models.CharField(blank=True, help_text="E.g. 'Request Form'", max_length=50, verbose_name='Membership CTA button text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='membership_cta_url',
            field=models.URLField(blank=True, help_text='Link to membership form or page.', verbose_name='Membership CTA URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='membership_description',
            field=models.TextField(blank=True, help_text='Brief description of membership benefits.', verbose_name='Membership CTA description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='membership_price',
            field=models.CharField(blank=True, help_text="E.g. 'Annual fee €80'", max_length=50, verbose_name='Membership price'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='membership_title',
            field=models.CharField(blank=True, help_text="E.g. 'Become a Member'", max_length=100, verbose_name='Membership CTA title'),
        ),
    ]
