# Generated by Django 5.2.11 on 2026-02-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_add_contact_hero_and_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='membership_cta_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='membership_cta_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='membership_description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='membership_price',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='membership_title',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='membership_cta_text',
            field=models.CharField(blank=True, help_text="E.g. 'Request Form'", max_length=50, verbose_name='Membership CTA button text'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='membership_cta_url',
            field=models.URLField(blank=True, help_text='Link to membership form or page.', verbose_name='Membership CTA URL'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='membership_description',
            field=models.TextField(blank=True, help_text='Brief description of membership benefits.', verbose_name='Membership CTA description'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='membership_price',
            field=models.CharField(blank=True, help_text="E.g. 'Annual fee €80'", max_length=50, verbose_name='Membership price'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='membership_title',
            field=models.CharField(blank=True, help_text="E.g. 'Become a Member'", max_length=100, verbose_name='Membership CTA title'),
        ),
    ]
