# Generated by Django 5.2.11 on 2026-02-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_move_membership_to_contactpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_until',
            field=models.DateField(blank=True, help_text='Last date this product can be purchased. Leave empty for no limit.', null=True, verbose_name='Available until'),
        ),
        migrations.AddField(
            model_name='product',
            name='validity_days',
            field=models.IntegerField(default=365, help_text='Number of days the membership is valid after purchase.', verbose_name='Validity days'),
        ),
    ]
