# Generated by Django 5.2.11 on 2026-02-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_add_product_validity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_from',
            field=models.DateField(blank=True, help_text='First date this product can be purchased. Leave empty for no limit.', null=True, verbose_name='Available from'),
        ),
    ]
