# Generated by Django - TranslatableMixin for Product

import uuid
from django.db import migrations, models
import django.db.models.deletion


def populate_translation_fields(apps, schema_editor):
    """Populate translation_key and locale for existing products."""
    Product = apps.get_model('website', 'Product')
    Locale = apps.get_model('wagtailcore', 'Locale')
    
    # Get or create default locale (Italian)
    try:
        default_locale = Locale.objects.get(language_code='it')
    except Locale.DoesNotExist:
        # Fallback to first locale or English
        default_locale = Locale.objects.first()
        if not default_locale:
            default_locale = Locale.objects.create(language_code='it')
    
    for product in Product.objects.all():
        product.locale = default_locale
        product.translation_key = uuid.uuid4()
        product.save()


def reverse_populate(apps, schema_editor):
    """No reverse needed - fields will be dropped."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('website', '0011_add_product_available_from'),
    ]

    operations = [
        # Step 1: Add nullable fields
        migrations.AddField(
            model_name='product',
            name='locale',
            field=models.ForeignKey(
                blank=True,
                null=True,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='wagtailcore.locale',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='translation_key',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        
        # Step 2: Populate existing records
        migrations.RunPython(populate_translation_fields, reverse_populate),
        
        # Step 3: Make fields required
        migrations.AlterField(
            model_name='product',
            name='locale',
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='wagtailcore.locale',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        
        # Step 4: Remove old unique constraint on slug, add new constraints
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('translation_key', 'locale'), ('locale', 'slug')},
        ),
    ]
