# Generated by Django 5.2.12 on 2026-03-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_add_membership_plans_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpage',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitudine per la mappa (es. 45.6950).', null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitudine per la mappa (es. 9.6700).', null=True, verbose_name='Longitude'),
        ),
    ]
