# Generated by Django 5.2.12 on 2026-03-19 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('website', '0015_add_lat_lng_to_partnerpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpage',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Immagine di copertina mostrata tra il titolo e il contenuto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Cover image'),
        ),
    ]
