# Generated by Django 5.2.12 on 2026-03-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_add_cover_image_to_partnerpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='github_url',
            field=models.URLField(blank=True, help_text="URL del repository GitHub. Se compilato, mostra un badge 'Fork me on GitHub' nell'angolo in alto a destra.", verbose_name='GitHub repository URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tracking_code',
            field=models.TextField(blank=True, help_text='Codice di monitoraggio statistiche (es. Matomo, Google Analytics). Verrà inserito prima della chiusura </body>.', verbose_name='Tracking code'),
        ),
    ]
