# Generated by Django 5.2.12 on 2026-03-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_add_tracking_code_and_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='allow_ai_bots',
            field=models.BooleanField(default=False, help_text='Se disattivato, robots.txt bloccherà i bot AI (GPTBot, ChatGPT-User, Google-Extended, CCBot, Anthropic, Meta, Bytespider, PerplexityBot).', verbose_name='Allow AI bot crawling'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='canonical_domain',
            field=models.URLField(blank=True, help_text="Dominio canonico del sito (es. 'https://www.example.com'). Se vuoto il canonical URL usa il dominio della richiesta.", verbose_name='Canonical domain'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='robots_txt_extra',
            field=models.TextField(blank=True, help_text="Regole aggiuntive per robots.txt (es. 'Disallow: /private/'). Verranno aggiunte dopo le regole di base.", verbose_name='Additional robots.txt rules'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_indexing',
            field=models.BooleanField(default=True, help_text="Se disattivato, tutte le pagine avranno il meta tag 'noindex, nofollow'. Utile per siti in staging/anteprima.", verbose_name='Allow search engine indexing'),
        ),
    ]
