# Generated by Django 5.2.12 on 2026-03-20 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('website', '0018_seo_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pwa_icon_180',
            field=models.ForeignKey(blank=True, help_text='Icona per iOS home screen 180x180px (PNG).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Apple touch icon 180x180'),
        ),
    ]
