# Generated by Django 5.2.12 on 2026-03-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_pwa_icon_180'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_text',
            field=models.TextField(blank=True, default='', help_text='Testo mostrato accanto al logo nella navbar. Gli accapi vengono rispettati.', verbose_name='Logo text'),
        ),
    ]
