# Generated by Django 5.2.12 on 2026-03-22 18:04

import json

import wagtail.fields
from django.db import migrations


def convert_body_to_json(apps, schema_editor):
    """Convert existing plain-text body fields to StreamField JSON format."""
    SentNewsletter = apps.get_model("website", "SentNewsletter")
    for nl in SentNewsletter.objects.all():
        # If already valid JSON (array), skip
        try:
            data = json.loads(nl.body)
            if isinstance(data, list):
                continue
        except (json.JSONDecodeError, TypeError):
            pass
        # Convert plain text to a single text block
        old_text = nl.body or ""
        body_data = [{"type": "text", "value": f"<p>{old_text}</p>"}]
        nl.body = json.dumps(body_data)
        nl.save(update_fields=["body"])


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_sent_newsletter'),
    ]

    operations = [
        migrations.RunPython(convert_body_to_json, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sentnewsletter',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('text', 1), ('image', 5), ('button', 9), ('divider', 10), ('quote', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section heading.', 'icon': 'title', 'label': 'Heading', 'max_length': 255}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr'], 'icon': 'pilcrow', 'label': 'Text'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption below the image.', 'label': 'Caption', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Accessibility description of the image.', 'label': 'Alt text', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('alt_text', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Button text', 'max_length': 100}), 7: ('wagtail.blocks.URLBlock', (), {'label': 'Link URL'}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (blue)'), ('secondary', 'Secondary (grey)')], 'label': 'Style'}), 9: ('wagtail.blocks.StructBlock', [[('text', 6), ('url', 7), ('style', 8)]], {}), 10: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': '───', 'icon': 'horizontalrule', 'label': 'Divider'}), 11: ('wagtail.blocks.TextBlock', (), {'label': 'Quote text'}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who said this (optional).', 'label': 'Attribution', 'max_length': 200, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('text', 11), ('attribution', 12)]], {})}, help_text='Compose the newsletter using the available blocks.', verbose_name='Body'),
        ),
    ]
