# Generated by Django 5.2.12 on 2026-03-22 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_streamfield_newsletter_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.CharField(blank=True, help_text='Shown to subscribers when choosing categories.', max_length=255, verbose_name='Description')),
                ('is_default', models.BooleanField(default=False, help_text='Auto-selected for new subscribers.', verbose_name='Default')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'Newsletter category',
                'verbose_name_plural': 'Newsletter categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='sentnewsletter',
            options={'ordering': ['-created_at'], 'verbose_name': 'Newsletter', 'verbose_name_plural': 'Newsletters'},
        ),
        migrations.AddField(
            model_name='sentnewsletter',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If checked, this newsletter is visible in the public archive.', verbose_name='Public'),
        ),
        migrations.AddField(
            model_name='sentnewsletter',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='If set, the newsletter will be sent automatically at this date and time.', null=True, verbose_name='Scheduled for'),
        ),
        migrations.AlterField(
            model_name='sentnewsletter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent')], default='draft', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Newsletter categories this subscriber opted into.', related_name='subscriptions', to='website.newslettercategory', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='sentnewsletter',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletters', to='website.newslettercategory', verbose_name='Category'),
        ),
    ]
