# Generated by Django 5.2.12 on 2026-03-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_newsletter_categories_scheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetailpage',
            name='organizer_name',
            field=models.CharField(blank=True, help_text="Nome del Club o ente organizzatore dell'evento.", max_length=255, verbose_name='Organizer name'),
        ),
        migrations.AddField(
            model_name='eventdetailpage',
            name='organizer_url',
            field=models.URLField(blank=True, help_text="Sito web del Club federato dove l'evento è pubblicato.", verbose_name='Organizer URL'),
        ),
    ]
