# Generated by Django 5.2.12 on 2026-03-27 18:28

import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('website', '0025_event_organizer_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsAreaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introductory text for the events area landing page.', verbose_name='Introduction')),
            ],
            options={
                'verbose_name': 'Events Area Page',
                'verbose_name_plural': 'Events Area Pages',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
    ]
