# Generated by Django 5.2.12 on 2026-03-15 10:01

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FederationInfoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introductory text displayed below the page title.', verbose_name='Introduction')),
                ('how_it_works', wagtail.fields.StreamField([('step', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional section title.', 'max_length': 255, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Year or date label (e.g. '2015').", 'max_length': 20, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Event or milestone title.', 'max_length': 255, 'required': True}), 3: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Detailed description of this event.', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('year', 1), ('title', 2), ('description', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Timeline entries', 'min_num': 1}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'HTML id attribute (for anchor links).', 'label': 'Custom ID', 'max_length': 100, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Extra CSS classes separated by spaces.', 'label': 'Custom CSS class', 'max_length': 255, 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('light', 'Light'), ('dark', 'Dark'), ('primary', 'Primary colour')], 'label': 'Background'}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('md', 'Medium'), ('sm', 'Small'), ('lg', 'Large'), ('none', 'None')], 'label': 'Padding'}), 10: ('wagtail.blocks.StructBlock', [[('custom_id', 6), ('custom_class', 7), ('background', 8), ('padding', 9)]], {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('title', 0), ('items', 5), ('settings', 10)]], {})}, help_text='Steps explaining the federation process.', verbose_name='How it works')),
                ('faq', wagtail.fields.StreamField([('faq', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently asked questions', 'max_length': 255, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 500, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('question', 1), ('answer', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': 'Questions', 'min_num': 1}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'HTML id attribute (for anchor links).', 'label': 'Custom ID', 'max_length': 100, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Extra CSS classes separated by spaces.', 'label': 'Custom CSS class', 'max_length': 255, 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('light', 'Light'), ('dark', 'Dark'), ('primary', 'Primary colour')], 'label': 'Background'}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('md', 'Medium'), ('sm', 'Small'), ('lg', 'Large'), ('none', 'None')], 'label': 'Padding'}), 9: ('wagtail.blocks.StructBlock', [[('custom_id', 5), ('custom_class', 6), ('background', 7), ('padding', 8)]], {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('items', 4), ('settings', 9)]], {})}, verbose_name='FAQ')),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('cards_grid', 18), ('cta', 26), ('stats', 34), ('quote', 39), ('timeline', 45), ('team_grid', 56), ('newsletter_signup', 60), ('alert', 64), ('partners_grid', 73), ('table', 82), ('testimonials', 89), ('featured_pages', 95), ('faq', 101), ('pricing_table', 112), ('counter_up', 119), ('social_feed', 123), ('image', 126), ('gallery', 134), ('video_embed', 138), ('document', 141), ('document_list', 144), ('map', 150), ('accordion', 156), ('tabs', 161), ('two_columns', 165), ('section', 170), ('divider', 172), ('spacer', 174)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional section title above the grid.', 'max_length': 255, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Card thumbnail image.', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional badge text (e.g. date, category label).', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Card title.', 'max_length': 255, 'required': True}), 5: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short description text.', 'required': False}), 6: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Link to page', 'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'help_text': 'Used only if no internal page is selected.', 'label': 'External URL', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Read more', 'help_text': 'Button / link label.', 'max_length': 120, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 2), ('badge_text', 3), ('title', 4), ('text', 5), ('link_page', 6), ('link_url', 7), ('link_text', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'Cards', 'min_num': 1}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 columns'), ('3', '3 columns'), ('4', '4 columns')], 'help_text': 'Number of columns on desktop.'}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('outlined', 'Outlined'), ('elevated', 'Elevated / shadow'), ('minimal', 'Minimal')], 'help_text': 'Visual style for the cards.'}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'HTML id attribute (for anchor links).', 'label': 'Custom ID', 'max_length': 100, 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Extra CSS classes separated by spaces.', 'label': 'Custom CSS class', 'max_length': 255, 'required': False}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('light', 'Light'), ('dark', 'Dark'), ('primary', 'Primary colour')], 'label': 'Background'}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('md', 'Medium'), ('sm', 'Small'), ('lg', 'Large'), ('none', 'None')], 'label': 'Padding'}), 17: ('wagtail.blocks.StructBlock', [[('custom_id', 13), ('custom_class', 14), ('background', 15), ('padding', 16)]], {'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 1), ('cards', 10), ('columns', 11), ('style', 12), ('settings', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'CTA headline.', 'max_length': 255, 'required': True}), 20: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Supporting text.', 'required': False}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'Button label.', 'max_length': 120, 'required': True}), 22: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Button page link', 'required': False}), 23: ('wagtail.blocks.URLBlock', (), {'help_text': 'Used only if no internal page is selected.', 'label': 'Button external URL', 'required': False}), 24: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('primary', 'Primary colour'), ('dark', 'Dark'), ('light', 'Light'), ('gradient', 'Gradient'), ('image', 'Image background')], 'help_text': 'Background style for this section.'}), 25: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': "Background image (only used with 'Image background' style).", 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('title', 19), ('text', 20), ('button_text', 21), ('button_link', 22), ('button_url', 23), ('background_style', 24), ('background_image', 25), ('settings', 17)]], {}), 27: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional section title.', 'max_length': 255, 'required': False}), 28: ('wagtail.blocks.CharBlock', (), {'help_text': "The numeric value or short text (e.g. '1500+').", 'max_length': 50, 'required': True}), 29: ('wagtail.blocks.CharBlock', (), {'help_text': "Description of the stat (e.g. 'Members').", 'max_length': 100, 'required': True}), 30: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional icon class name.', 'max_length': 50, 'required': False}), 31: ('wagtail.blocks.StructBlock', [[('value', 28), ('label', 29), ('icon', 30)]], {}), 32: ('wagtail.blocks.ListBlock', (31,), {'label': 'Statistics', 'min_num': 1}), 33: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('primary', 'Primary colour'), ('dark', 'Dark'), ('light', 'Light')]}), 34: ('wagtail.blocks.StructBlock', [[('title', 27), ('stats', 32), ('background_style', 33), ('settings', 17)]], {}), 35: ('wagtail.blocks.TextBlock', (), {'help_text': 'The quote text.', 'required': True}), 36: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name of the person quoted.', 'max_length': 255, 'required': False}), 37: ('wagtail.blocks.CharBlock', (), {'help_text': "Role or title of the author (e.g. 'President').", 'max_length': 255, 'required': False}), 38: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional portrait of the author.', 'required': False}), 39: ('wagtail.blocks.StructBlock', [[('quote', 35), ('author', 36), ('role', 37), ('image', 38), ('settings', 17)]], {}), 40: ('wagtail.blocks.CharBlock', (), {'help_text': "Year or date label (e.g. '2015').", 'max_length': 20, 'required': True}), 41: ('wagtail.blocks.CharBlock', (), {'help_text': 'Event or milestone title.', 'max_length': 255, 'required': True}), 42: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Detailed description of this event.', 'required': False}), 43: ('wagtail.blocks.StructBlock', [[('year', 40), ('title', 41), ('description', 42)]], {}), 44: ('wagtail.blocks.ListBlock', (43,), {'label': 'Timeline entries', 'min_num': 1}), 45: ('wagtail.blocks.StructBlock', [[('title', 27), ('items', 44), ('settings', 17)]], {}), 46: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional section title (e.g. 'Board of Directors').", 'max_length': 255, 'required': False}), 47: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 48: ('wagtail.blocks.CharBlock', (), {'help_text': 'Position or title.', 'max_length': 255, 'required': False}), 49: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 50: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Short biography.', 'required': False}), 51: ('wagtail.blocks.EmailBlock', (), {'required': False}), 52: ('wagtail.blocks.CharBlock', (), {'max_length': 30, 'required': False}), 53: ('wagtail.blocks.StructBlock', [[('name', 47), ('role', 48), ('photo', 49), ('bio', 50), ('email', 51), ('phone', 52)]], {}), 54: ('wagtail.blocks.ListBlock', (53,), {'label': 'Team members', 'min_num': 1}), 55: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 columns'), ('3', '3 columns'), ('4', '4 columns')]}), 56: ('wagtail.blocks.StructBlock', [[('title', 46), ('members', 54), ('columns', 55), ('settings', 17)]], {}), 57: ('wagtail.blocks.CharBlock', (), {'default': 'Stay updated', 'help_text': 'Form heading.', 'max_length': 255}), 58: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short text explaining what subscribers will receive.', 'required': False}), 59: ('wagtail.blocks.CharBlock', (), {'default': 'Subscribe', 'max_length': 120}), 60: ('wagtail.blocks.StructBlock', [[('heading', 57), ('description', 58), ('button_text', 59), ('background', 33), ('settings', 17)]], {}), 61: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Alert message content.', 'required': True}), 62: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], 'help_text': 'Visual style and severity of the alert.'}), 63: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Allow users to dismiss this alert.', 'required': False}), 64: ('wagtail.blocks.StructBlock', [[('message', 61), ('alert_type', 62), ('dismissible', 63), ('settings', 17)]], {}), 65: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional section title (e.g. 'Our Partners').", 'max_length': 255, 'required': False}), 66: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional subtitle text.', 'max_length': 255, 'required': False}), 67: ('wagtail.blocks.CharBlock', (), {'label': 'Partner name', 'max_length': 255, 'required': True}), 68: ('wagtail.blocks.CharBlock', (), {'help_text': 'Short description or partner type.', 'label': 'Description', 'max_length': 255, 'required': False}), 69: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Logo', 'required': False}), 70: ('wagtail.blocks.URLBlock', (), {'label': 'Website URL', 'required': False}), 71: ('wagtail.blocks.StructBlock', [[('name', 67), ('description', 68), ('logo', 69), ('url', 70)]], {}), 72: ('wagtail.blocks.ListBlock', (71,), {'label': 'Partners', 'min_num': 1}), 73: ('wagtail.blocks.StructBlock', [[('title', 65), ('subtitle', 66), ('partners', 72), ('columns', 11), ('settings', 17)]], {}), 74: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional table caption.', 'max_length': 255, 'required': False}), 75: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 76: ('wagtail.blocks.ListBlock', (75,), {'label': 'Column headers', 'min_num': 1}), 77: ('wagtail.blocks.CharBlock', (), {'max_length': 500}), 78: ('wagtail.blocks.ListBlock', (77,), {'label': 'Cells', 'min_num': 1}), 79: ('wagtail.blocks.StructBlock', [[('cells', 78)]], {}), 80: ('wagtail.blocks.ListBlock', (79,), {'label': 'Rows', 'min_num': 1}), 81: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Alternate row background colours.', 'required': False}), 82: ('wagtail.blocks.StructBlock', [[('title', 74), ('headers', 76), ('rows', 80), ('striped', 81), ('settings', 17)]], {}), 83: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 84: ('wagtail.blocks.TextBlock', (), {'help_text': 'Testimonial text.', 'required': True}), 85: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title or role.', 'max_length': 255, 'required': False}), 86: ('wagtail.blocks.StructBlock', [[('quote', 84), ('name', 47), ('role', 85), ('avatar', 49)]], {}), 87: ('wagtail.blocks.ListBlock', (86,), {'label': 'Testimonials', 'min_num': 1}), 88: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('carousel', 'Carousel'), ('grid', 'Grid')]}), 89: ('wagtail.blocks.StructBlock', [[('title', 83), ('testimonials', 87), ('layout', 88), ('settings', 17)]], {}), 90: ('wagtail.blocks.PageChooserBlock', (), {'required': True}), 91: ('wagtail.blocks.CharBlock', (), {'help_text': 'Override the page title.', 'max_length': 255, 'required': False}), 92: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': "Override the page's default image.", 'required': False}), 93: ('wagtail.blocks.StructBlock', [[('page', 90), ('override_title', 91), ('override_image', 92)]], {}), 94: ('wagtail.blocks.ListBlock', (93,), {'label': 'Pages', 'max_num': 12, 'min_num': 1}), 95: ('wagtail.blocks.StructBlock', [[('title', 83), ('pages', 94), ('columns', 55), ('settings', 17)]], {}), 96: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently asked questions', 'max_length': 255, 'required': False}), 97: ('wagtail.blocks.CharBlock', (), {'max_length': 500, 'required': True}), 98: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 99: ('wagtail.blocks.StructBlock', [[('question', 97), ('answer', 98)]], {}), 100: ('wagtail.blocks.ListBlock', (99,), {'label': 'Questions', 'min_num': 1}), 101: ('wagtail.blocks.StructBlock', [[('title', 96), ('items', 100), ('settings', 17)]], {}), 102: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 103: ('wagtail.blocks.CharBlock', (), {'help_text': "Price text (e.g. '€50/year').", 'max_length': 50, 'required': True}), 104: ('wagtail.blocks.TextBlock', (), {'required': False}), 105: ('wagtail.blocks.ListBlock', (75,), {'label': 'Features'}), 106: ('wagtail.blocks.CharBlock', (), {'default': 'Choose plan', 'max_length': 120}), 107: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 108: ('wagtail.blocks.URLBlock', (), {'required': False}), 109: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Highlight this plan as recommended.', 'required': False}), 110: ('wagtail.blocks.StructBlock', [[('name', 102), ('price', 103), ('description', 104), ('features', 105), ('cta_text', 106), ('cta_link', 107), ('cta_url', 108), ('highlighted', 109)]], {}), 111: ('wagtail.blocks.ListBlock', (110,), {'label': 'Plans', 'max_num': 4, 'min_num': 1}), 112: ('wagtail.blocks.StructBlock', [[('title', 83), ('plans', 111), ('settings', 17)]], {}), 113: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Target number to count up to.', 'required': True}), 114: ('wagtail.blocks.CharBlock', (), {'help_text': "Text after number (e.g. '+', '%', 'k').", 'max_length': 20, 'required': False}), 115: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 116: ('wagtail.blocks.StructBlock', [[('value', 113), ('suffix', 114), ('label', 102), ('icon', 115)]], {}), 117: ('wagtail.blocks.ListBlock', (116,), {'label': 'Counters', 'min_num': 1}), 118: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('primary', 'Primary colour'), ('dark', 'Dark')]}), 119: ('wagtail.blocks.StructBlock', [[('title', 83), ('counters', 117), ('background_style', 118), ('settings', 17)]], {}), 120: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'X / Twitter'), ('youtube', 'YouTube')]}), 121: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL of the social profile or post to embed.', 'required': True}), 122: ('wagtail.blocks.IntegerBlock', (), {'default': 6, 'help_text': 'Maximum number of posts to display.', 'max_value': 12, 'min_value': 1}), 123: ('wagtail.blocks.StructBlock', [[('title', 83), ('platform', 120), ('embed_url', 121), ('max_posts', 122), ('settings', 17)]], {}), 124: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 125: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full width'), ('center', 'Centred'), ('left', 'Float left'), ('right', 'Float right')], 'help_text': 'Image alignment within the content area.'}), 126: ('wagtail.blocks.StructBlock', [[('image', 124), ('caption', 83), ('alignment', 125), ('settings', 17)]], {}), 127: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional gallery title.', 'max_length': 255, 'required': False}), 128: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption displayed below the image.', 'max_length': 255, 'required': False}), 129: ('wagtail.blocks.StructBlock', [[('image', 124), ('caption', 128)]], {}), 130: ('wagtail.blocks.ListBlock', (129,), {'label': 'Images', 'min_num': 1}), 131: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 columns'), ('3', '3 columns'), ('4', '4 columns'), ('6', '6 columns')], 'help_text': 'Number of columns on desktop.'}), 132: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Enable lightbox for full-size image viewing.', 'required': False}), 133: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('auto', 'Auto (original)'), ('1x1', 'Square (1:1)'), ('4x3', 'Landscape (4:3)'), ('16x9', 'Widescreen (16:9)'), ('3x4', 'Portrait (3:4)')], 'help_text': 'Thumbnail aspect ratio.'}), 134: ('wagtail.blocks.StructBlock', [[('title', 127), ('images', 130), ('columns', 131), ('lightbox', 132), ('aspect_ratio', 133), ('settings', 17)]], {}), 135: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste a video URL (YouTube, Vimeo, etc.).', 'required': True}), 136: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption displayed below the video.', 'max_length': 255, 'required': False}), 137: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Autoplay the video (muted).', 'required': False}), 138: ('wagtail.blocks.StructBlock', [[('video', 135), ('caption', 136), ('autoplay', 137), ('settings', 17)]], {}), 139: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 140: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional description of the document.', 'required': False}), 141: ('wagtail.blocks.StructBlock', [[('document', 139), ('description', 140)]], {}), 142: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section title for the document list.', 'max_length': 255, 'required': False}), 143: ('wagtail.blocks.ListBlock', (141,), {'label': 'Documents', 'min_num': 1}), 144: ('wagtail.blocks.StructBlock', [[('title', 142), ('documents', 143), ('settings', 17)]], {}), 145: ('wagtail.blocks.CharBlock', (), {'help_text': 'Display address (shown in the info popup).', 'max_length': 500, 'required': False}), 146: ('wagtail.blocks.CharBlock', (), {'help_text': "Latitude,Longitude (e.g. '45.4642,9.1900').", 'max_length': 100, 'required': True}), 147: ('wagtail.blocks.IntegerBlock', (), {'default': 14, 'help_text': 'Map zoom level (1-20).', 'max_value': 20, 'min_value': 1}), 148: ('wagtail.blocks.IntegerBlock', (), {'default': 400, 'help_text': 'Map height in pixels.'}), 149: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional marker label.', 'max_length': 255, 'required': False}), 150: ('wagtail.blocks.StructBlock', [[('address', 145), ('coordinates', 146), ('zoom', 147), ('height', 148), ('title', 149), ('settings', 17)]], {}), 151: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional section title above the accordion.', 'max_length': 255, 'required': False}), 152: ('wagtail.blocks.CharBlock', (), {'help_text': 'Accordion panel header.', 'max_length': 255, 'required': True}), 153: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Panel content revealed when expanded.', 'required': True}), 154: ('wagtail.blocks.StructBlock', [[('title', 152), ('content', 153)]], {}), 155: ('wagtail.blocks.ListBlock', (154,), {'label': 'Panels', 'min_num': 1}), 156: ('wagtail.blocks.StructBlock', [[('title', 151), ('items', 155), ('settings', 17)]], {}), 157: ('wagtail.blocks.CharBlock', (), {'help_text': 'Tab label.', 'max_length': 255, 'required': True}), 158: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Tab panel content.', 'required': True}), 159: ('wagtail.blocks.StructBlock', [[('title', 157), ('content', 158)]], {}), 160: ('wagtail.blocks.ListBlock', (159,), {'label': 'Tabs', 'min_num': 2}), 161: ('wagtail.blocks.StructBlock', [[('tabs', 160), ('settings', 17)]], {}), 162: ('wagtail.blocks.RichTextBlock', (), {'label': 'Left column', 'required': True}), 163: ('wagtail.blocks.RichTextBlock', (), {'label': 'Right column', 'required': True}), 164: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('50-50', '50 / 50'), ('33-67', '33 / 67'), ('67-33', '67 / 33'), ('25-75', '25 / 75'), ('75-25', '75 / 25')], 'help_text': 'Column width ratio.'}), 165: ('wagtail.blocks.StructBlock', [[('left_column', 162), ('right_column', 163), ('split', 164), ('settings', 17)]], {}), 166: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional section heading.', 'max_length': 255, 'required': False}), 167: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Section body content.', 'required': True}), 168: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('primary', 'Primary colour'), ('secondary', 'Secondary colour'), ('dark', 'Dark'), ('light', 'Light grey'), ('image', 'Image background')], 'help_text': 'Background style.'}), 169: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large'), ('xl', 'Extra large')], 'help_text': 'Vertical padding.'}), 170: ('wagtail.blocks.StructBlock', [[('title', 166), ('content', 167), ('background', 168), ('background_image', 25), ('padding', 169), ('settings', 17)]], {}), 171: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('line', 'Horizontal line'), ('dots', 'Dots'), ('space', 'Blank space')], 'help_text': 'Separator visual style.'}), 172: ('wagtail.blocks.StructBlock', [[('style', 171), ('settings', 17)]], {}), 173: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sm', 'Small (1rem)'), ('md', 'Medium (2rem)'), ('lg', 'Large (4rem)'), ('xl', 'Extra large (6rem)')], 'help_text': 'Amount of vertical space.'}), 174: ('wagtail.blocks.StructBlock', [[('size', 173), ('settings', 17)]], {})}, verbose_name='Additional content')),
                ('cta_text', models.CharField(blank=True, help_text='Label for the call-to-action button.', max_length=100, verbose_name='CTA button text')),
                ('cta_url', models.CharField(blank=True, default='/eventi/partner/', help_text='URL the CTA button links to.', max_length=200, verbose_name='CTA link')),
            ],
            options={
                'verbose_name': 'Federation Info Page',
                'verbose_name_plural': 'Federation Info Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='detail_url',
            field=models.URLField(blank=True, help_text="URL della pagina dell'evento sul sito partner."),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text="Data e ora di fine dell'evento.", null=True),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='event_name',
            field=models.CharField(help_text="Nome dell'evento come fornito dal partner.", max_length=255),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='event_status',
            field=models.CharField(choices=[('EventScheduled', 'Scheduled'), ('EventCancelled', 'Cancelled'), ('EventPostponed', 'Postponed'), ('EventMovedOnline', 'Moved Online')], default='EventScheduled', help_text="Stato corrente dell'evento.", max_length=20),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='external_id',
            field=models.CharField(help_text="ID univoco dell'evento nel sistema del partner.", max_length=100),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='fetched_at',
            field=models.DateTimeField(auto_now_add=True, help_text="Data del primo import dell'evento."),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='image_url',
            field=models.URLField(blank=True, help_text="URL dell'immagine di copertina."),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='is_approved',
            field=models.BooleanField(default=True, help_text="L'evento è visibile ai soci."),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text="Nascondi l'evento dall'elenco pubblico."),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='location_address',
            field=models.CharField(blank=True, help_text='Indirizzo completo del luogo.', max_length=500),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='location_lat',
            field=models.FloatField(blank=True, help_text='Latitudine della posizione.', null=True),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='location_lon',
            field=models.FloatField(blank=True, help_text='Longitudine della posizione.', null=True),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='location_name',
            field=models.CharField(blank=True, help_text="Nome del luogo dell'evento.", max_length=255),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='source_club',
            field=models.ForeignKey(help_text="Club partner che ha pubblicato l'evento.", on_delete=django.db.models.deletion.CASCADE, related_name='external_events', to='federation.federatedclub'),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='start_date',
            field=models.DateTimeField(help_text="Data e ora di inizio dell'evento."),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text="Data dell'ultimo aggiornamento."),
        ),
        migrations.AlterField(
            model_name='externaleventcomment',
            name='content',
            field=models.TextField(help_text='Testo del commento (non condiviso col partner).'),
        ),
        migrations.AlterField(
            model_name='externaleventcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data di creazione del commento.'),
        ),
        migrations.AlterField(
            model_name='externaleventcomment',
            name='external_event',
            field=models.ForeignKey(help_text='Evento esterno commentato.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='federation.externalevent'),
        ),
        migrations.AlterField(
            model_name='externaleventcomment',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Il commento è stato cancellato (soft delete).'),
        ),
        migrations.AlterField(
            model_name='externaleventcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text="Data dell'ultima modifica."),
        ),
        migrations.AlterField(
            model_name='externaleventcomment',
            name='user',
            field=models.ForeignKey(help_text='Socio autore del commento.', on_delete=django.db.models.deletion.CASCADE, related_name='event_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='externaleventinterest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text="Data di espressione dell'interesse."),
        ),
        migrations.AlterField(
            model_name='externaleventinterest',
            name='external_event',
            field=models.ForeignKey(help_text='Evento esterno di interesse.', on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='federation.externalevent'),
        ),
        migrations.AlterField(
            model_name='externaleventinterest',
            name='interest_level',
            field=models.CharField(choices=[('interested', 'Interested'), ('maybe', 'Maybe'), ('going', 'Going')], help_text="Livello di interesse per l'evento.", max_length=20),
        ),
        migrations.AlterField(
            model_name='externaleventinterest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text="Data dell'ultima modifica."),
        ),
        migrations.AlterField(
            model_name='externaleventinterest',
            name='user',
            field=models.ForeignKey(help_text='Socio che ha espresso interesse.', on_delete=django.db.models.deletion.CASCADE, related_name='event_interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='federatedclub',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data di creazione del record.'),
        ),
        migrations.AlterField(
            model_name='federatedclub',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Amministratore che ha aggiunto il club partner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='federatedclub',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Attiva la connessione con questo club partner.'),
        ),
        migrations.AlterField(
            model_name='federatedclub',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Il club partner è stato verificato e approvato.'),
        ),
        migrations.AlterField(
            model_name='federatedclub',
            name='last_error',
            field=models.TextField(blank=True, help_text='Ultimo messaggio di errore durante la sincronizzazione.'),
        ),
        migrations.AlterField(
            model_name='federatedclub',
            name='last_sync',
            field=models.DateTimeField(blank=True, help_text="Data e ora dell'ultima sincronizzazione eventi.", null=True),
        ),
    ]
