# Generated by Django 5.2.12 on 2026-03-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0002_add_federation_info_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='federatedclub',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the partner club (visible on federation page).'),
        ),
    ]
