# Generated by Django 5.2.12 on 2026-03-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0003_add_club_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='federatedclub',
            name='city',
            field=models.CharField(blank=True, help_text='City where the partner club is based.', max_length=100, verbose_name='City'),
        ),
    ]
