# Generated by Django 5.2.12 on 2026-03-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0004_add_city_to_federatedclub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federatedclub',
            name='logo_url',
            field=models.CharField(blank=True, help_text='Logo URL (external) or static path (e.g. /static/img/federation/logo.svg).', max_length=500),
        ),
    ]
