# Generated by Django 5.2.12 on 2026-03-27 00:53

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0005_change_logo_url_to_charfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='federationinfopage',
            name='cta_url',
        ),
        migrations.AddField(
            model_name='federationinfopage',
            name='events_intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Introductory text for the partner events listing page.', verbose_name='Events page introduction'),
        ),
        migrations.AddField(
            model_name='federationinfopage',
            name='events_per_page',
            field=models.PositiveIntegerField(default=12, help_text='Number of events to display per page.', verbose_name='Events per page'),
        ),
    ]
