# Generated by Django 5.2.11 on 2026-02-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_clubuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubuser',
            name='address',
            field=models.CharField(blank=True, help_text='Street address. Example: Via Roma 42', max_length=255),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='aid_available',
            field=models.BooleanField(default=False, help_text='Enable this to appear in the mutual aid helper directory.'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='aid_coordinates',
            field=models.CharField(blank=True, help_text='Latitude and longitude, comma-separated. Example: 45.4642,9.1900', max_length=50),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='aid_location_city',
            field=models.CharField(blank=True, help_text='The city where you are usually based for mutual aid.', max_length=100),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='aid_notes',
            field=models.TextField(blank=True, help_text='Additional information: tools, skills, vehicle type, availability hours.'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='aid_radius_km',
            field=models.PositiveIntegerField(default=25, help_text='Maximum distance in km you are willing to travel to help. Example: 25'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='aid_requests',
            field=models.BooleanField(default=True, help_text='Notifications when someone nearby requests mutual aid.'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='bio',
            field=models.TextField(blank=True, help_text='A short description about yourself. Visible on your profile page.'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Your date of birth. Used for birthday greetings and age-restricted events.', null=True),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='birth_place',
            field=models.CharField(blank=True, help_text='City or town where you were born.', max_length=100),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='city',
            field=models.CharField(blank=True, help_text='City or town of residence.', max_length=100),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='country',
            field=models.CharField(default='IT', help_text='Two-letter country code (ISO 3166-1). Example: IT', max_length=2),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='digest_frequency',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='How often to receive a digest email summarising your notifications.', max_length=10),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='display_name',
            field=models.CharField(blank=True, help_text='Choose a nickname that will be shown publicly instead of your real name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive notifications via email.'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='event_reminders',
            field=models.BooleanField(default=True, help_text='Receive a reminder before events you are registered for.'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='event_updates',
            field=models.BooleanField(default=True, help_text='Get notified about new events and changes to events you registered for.'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='membership_alerts',
            field=models.BooleanField(default=True, help_text='Alerts about membership expiry, renewal, and card updates.'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='mobile',
            field=models.CharField(blank=True, help_text='Mobile number with country prefix. Example: +39 333 1234567', max_length=30),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='news_updates',
            field=models.BooleanField(default=True, help_text='Get notified when new articles or announcements are published.'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='newsletter',
            field=models.BooleanField(default=False, help_text='Receive our periodic newsletter with club news and upcoming events.'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='partner_event_comments',
            field=models.BooleanField(default=True, help_text='Comments on partner events you showed interest in.'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='partner_events',
            field=models.BooleanField(default=True, help_text='Events published by federated partner clubs.'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='partner_updates',
            field=models.BooleanField(default=False, help_text='News and promotions from partner clubs.'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Landline number with country prefix. Example: +39 02 1234567', max_length=30),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='postal_code',
            field=models.CharField(blank=True, help_text='5-digit postal code. Example: 20100', max_length=5),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='province',
            field=models.CharField(blank=True, help_text='Two-letter province code. Example: MI', max_length=2),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='public_profile',
            field=models.BooleanField(default=False, help_text='When enabled, your profile page is visible to anyone, including non-members.'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='push_notifications',
            field=models.BooleanField(default=False, help_text='Receive push notifications in your browser (requires PWA support).'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='show_in_directory',
            field=models.BooleanField(default=False, help_text='When enabled, your display name appears in the member directory visible to other members.'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='show_real_name_to_members',
            field=models.BooleanField(default=False, help_text='When enabled, active members can see your real first and last name.'),
        ),
    ]
