# Generated by Django 5.2.11 on 2026-02-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_add_membership_request'),
        ('website', '0012_product_translatable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubuser',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='members', to='website.product', verbose_name='Products'),
        ),
    ]
