# Generated by Django 5.2.11 on 2026-02-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_products_to_manytomany'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubuser',
            name='card_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', help_text='Status of the membership card. Suspended cards can be reactivated.', max_length=20),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='card_status_changed',
            field=models.DateTimeField(blank=True, help_text='When the card status was last changed.', null=True),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='card_status_reason',
            field=models.TextField(blank=True, help_text='Reason for suspension or termination.'),
        ),
    ]
