# Generated by Django 5.2.12 on 2026-03-20 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_add_card_status'),
        ('wagtailimages', '0027_image_description'),
        ('website', '0020_logo_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubuser',
            name='card_number',
            field=models.CharField(blank=True, help_text='Numero tessera socio (generato automaticamente).', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='document_expiry',
            field=models.DateField(blank=True, help_text='Data di scadenza del documento.', null=True),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='document_number',
            field=models.CharField(blank=True, help_text='Numero del documento di identità.', max_length=50),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='document_type',
            field=models.CharField(blank=True, choices=[('id_card', 'ID Card'), ('license', "Driver's License"), ('passport', 'Passport')], help_text='Tipo di documento di identità.', max_length=20),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='fiscal_code',
            field=models.CharField(blank=True, help_text='Codice fiscale italiano (16 caratteri).', max_length=16),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='membership_date',
            field=models.DateField(blank=True, help_text='Data di prima iscrizione al club.', null=True),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='membership_expiry',
            field=models.DateField(blank=True, help_text='Data di scadenza della tessera.', null=True),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='photo',
            field=models.ForeignKey(blank=True, help_text='Foto profilo del socio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Prodotti/abbonamenti acquistati dal socio.', related_name='members', to='website.product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e ora di invio della richiesta.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text="Data e ora di elaborazione da parte dell'admin.", null=True, verbose_name='Processed at'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Amministratore che ha gestito la richiesta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Processed by'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='product',
            field=models.ForeignKey(help_text='Prodotto/abbonamento richiesto.', on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='website.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Stato della richiesta di adesione.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text="Data e ora dell'ultimo aggiornamento.", verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='user',
            field=models.ForeignKey(help_text='Socio che ha inviato la richiesta.', on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
