# Generated by Django 5.2.12 on 2026-03-27 14:42

import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_clubuser_card_number_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersAreaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introductory text displayed on the members area landing page.', verbose_name='Introduction')),
                ('directory_intro', wagtail.fields.RichTextField(blank=True, help_text='Text shown at the top of the member directory.', verbose_name='Directory introduction')),
                ('card_help_text', wagtail.fields.RichTextField(blank=True, help_text='Help text displayed on the membership card page.', verbose_name='Card help text')),
            ],
            options={
                'verbose_name': 'Members Area Page',
                'verbose_name_plural': 'Members Area Pages',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
    ]
